### ISSUE TITLE
Can't compile tutorial test with Embarcadero XE7 C++ Builder

### ISSUE THREAD

**Issue by BrendanSimon** [philsquared/Catch#1010]
## Description

I want to trial Catch using Embarcadero XE7 C++ Builder (a work tool) to see if it can be used for a new project that uses Jenkins for CI.

A simple test using the tutorial fails with a build error:

`[bcc32 Error] catch.hpp(4729): E2404 Dependent type qualifier 'CommandLine<ConfigData>' has no member type named 'Arg'
`

The error is reported at lines 4730 and 4713.

```
        friend void addOptName( Arg& arg, std::string const& optName )
        {
            if( optName.empty() )
                return;
            if( Detail::startsWith( optName, "--" ) ) {
                if( !arg.longName.empty() )
                    throw std::logic_error( "Only one long opt may be specified. '"
                        + arg.longName
                        + "' already specified, now attempting to add '"
                        + optName + "'" );
                arg.longName = optName.substr( 2 );
            }
            else if( Detail::startsWith( optName, "-" ) )
                arg.shortNames.push_back( optName.substr( 1 ) );
            else
                throw std::logic_error( "option must begin with - or --. Option was: '" + optName + "'" );
        }
        friend void setPositionalArg( Arg& arg, int position )
        {
            arg.position = position;
        }
```

I do not get that build error if I comment out the `#define CATCH_CONFIG_MAIN` statement.

### Steps to reproduce

Added a file `test_catch.cpp` (which contains the tutorial example) to an Embarcadero project, and the `catch.hpp` header file (`v1.10.0`), and tried to build a console application and get the following error:

`[bcc32 Error] catch.hpp(4729): E2404 Dependent type qualifier 'CommandLine<ConfigData>' has no member type named 'Arg'
`

**Any ideas how to resolve this?**

Would using an earlier version of the single header file help, or using the latest sources from github?

### Extra information

* Catch version: **v1.10.0 (single header file)**
* Operating System: **Windows 7**
* Compiler+version: **Embarcadero XE7 C++ Builder (32-bit)**
  * 32-bit version of compiler is proprietary and is `C++98` only.
  * 64-bit version of compiler is based on `clang` (`3.1+svn`) and has `C++11` features, and compiles ok.

```
$ bcc32.exe --version
Embarcadero C++ 6.90 for Win32 Copyright (c) 1993-2014 Embarcadero Technologies, Inc.
Revision 6.90.5338.34256

$ bcc64.exe --version
Embarcadero C++ 6.90 for Win64 Copyright (c) 2012-2014 Embarcadero Technologies, Inc.
Embarcadero Technologies Inc. bcc64 version 3.1 (34540.0798eef.0c4972a) (based on LLVM 3.1svn)
Target: x86_64-pc-win32-elf
Thread model: posix
```

**Comment by BrendanSimon** [comment]
I'll stick with the 64-bit clang compiler and/or try their free 32-bit clang compiler, which they recently announced as a free download (hopefully I can get it to integrate with the older XE7 IDE).

**Comment by horenmar** [comment]
I am going to close this for the same reason as #1015 (32-bit builder is C++98 non-conforming and not seen as worth supporting). If this is incorrect, please reopen the issue.
