### ISSUE TITLE
`Undefined symbol T` in class `Option`, reported with Embarcader XE 7 C++ Builder (32-bit)

### ISSUE THREAD

**Issue by BrendanSimon** [philsquared/Catch#1015]
## Description

A simple test using the tutorial fails with a build error:

```
[bcc32 Error] catch.hpp(3131): E2451 Undefined symbol 'T'
[bcc32 Error] catch.hpp(3131): E2109 Not an allowed type
```

The error is reported at line 3131.  The compiler seems to have trouble with `T` inside the `union` construct.

```
        union {
            char storage[sizeof(T)];

            // These are here to force alignment for the storage
            long double dummy1;
            void (*dummy2)();
            long double dummy3;
#ifdef CATCH_CONFIG_CPP11_LONG_LONG
            long long dummy4;
#endif
        };
```

I do not get that build error if I comment out the `#define CATCH_CONFIG_MAIN` statement.

**Any ideas how to fix this?**

### Steps to reproduce

Added a file `test_catch.cpp` (which contains the tutorial example) to an Embarcadero project, and the `catch.hpp` header file (`v1.10.0`), and tried to build a console application.

### Extra information

* Catch version: **v1.10.0 (single header file)**
* Operating System: **Windows 7**
* Compiler+version: **Embarcadero XE7 C++ Builder (32-bit)**
  * 32-bit version of compiler is proprietary and is `C++98` only.
  * 64-bit version of compiler is based on `clang` (`3.1+svn`) and has `C++11` features, and compiles ok.

```
$ bcc32.exe --version
Embarcadero C++ 6.90 for Win32 Copyright (c) 1993-2014 Embarcadero Technologies, Inc.
Revision 6.90.5338.34256

$ bcc64.exe --version
Embarcadero C++ 6.90 for Win64 Copyright (c) 2012-2014 Embarcadero Technologies, Inc.
Embarcadero Technologies Inc. bcc64 version 3.1 (34540.0798eef.0c4972a) (based on LLVM 3.1svn)
Target: x86_64-pc-win32-elf
Thread model: posix
```

**Comment by philsquared** [comment]
Wow! Borland C++ lives on! I've not used that for over 20 years!
So the 32-bit compiler appears to be virtually unchanged from the Borland days, AFAICS - and all new investment is in the 64-bit compiler which, as you say, is based on clang anyway.
There was an effort (#104), some years ago now, to maintain a fork for Borland Builder (which, I presume, would transfer to the Embarcadero version) - but, AFAIK, that was never kept up (there were some PRs that I would have needed to accept that made me nervous).

There was also a VC6 fork that was maintained for some time (maybe even a couple of years) - but even that was abandoned as untenable.
So I think the bottom line is that the 32-bit compiler is unsupported by Catch - but the 64-bit one should be fine.
Note that this is not about C++98 vs C++11. The issues with the Borland/ Embarcadero (32-bit) compiler are about missing _C++98_ conformance.

Sorry if that's not what you wanted to hear.
Of course if you're eager to plough on, and maintain your own fork you're entirely free to do so.

**Comment by BrendanSimon** [comment]
Not really that keen.  It's just a tool that we use at work.  I managed to get another single header test framework to compile with just a one line change, so thought it might be simple for Catch to be ported too.

Embarcadero is reasonably good at what it does, but C++ is a second class citizen to Delphi (which we don't use).  Even the recent clang version has been stuck at v3.3 for quite a while (so no C++14 support).  

Now, I do remember that Embarcadero recently sent an email/advert stating they have released a free downloadable version of a 32-bit clang port (I think for the 10.1 Berlin or 10.2 Tokyo releases), so I might give that a go and see if I can get the XE7 IDE to play nice with that.  That would be a better option than using the legacy 32-bit compiler.

**Comment by philsquared** [comment]
Good luck! Please let us know if that works out - in case anyone else has the same issue.
If you're not using the Delphi integration is there any reasons or you to stick with Embarcadero at all? Moving to vanilla clang would seem to solve this (and probably other) problem(s).

**Comment by BrendanSimon** [comment]
It's historical a choice for the company.  Apparently it was the best IDE by far at the time it was chosen, and is used for RAD development and simulation of C code used in embedded targets.  The support for Android, macOS, iOS, Linux, Windows seems advantageous (though we've only ever targeted Windows).  There's also a reasonable library of code that gets reused, as well as a comfort and knowledge base built up with senior developers, so the effort to switch to something else is a factor.

**Comment by horenmar** [comment]
Since this has been "Wont fix" for over a month, I am going to close it.
