### ISSUE TITLE
REQUIRE does not recognize brace-constructor

### ISSUE THREAD

**Issue by Artalus** [philsquared/Catch#1019]
## Description
I have the following test:

    SCENARIO("from two points") {
        GIVEN("2 zero vectors") {
            vec2 a{}, b{};
            SECTION("result is zero") {
                REQUIRE(vec2::from_two_points(a,b) == vec2{0,0});
            }
        }
    }

which fails to compile. VS Intellisense highlights the whole `REQUIRE` line saying `Expected a '}'` and `Cannot resolve symbol endExpression`.

The output of compiler:

    1>path\vec2_test.cpp(74): warning C4002: too many actual parameters for macro 'REQUIRE'
    1>path\vec2_test.cpp(74): error C3329: syntax error: expected '}' not ')'
    1>path\vec2_test.cpp(74): error C2440: 'initializing': cannot convert from 'initializer list' to 'vec2'
    1>path\vec2_test.cpp(74): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    1>path\vec2_test.cpp(74): error C2228: left of '.endExpression' must have class/struct/union
    1>path\vec2_test.cpp(74): error C2059: syntax error: ';'
    1>path\vec2_test.cpp(74): error C2143: syntax error: missing ')' before ';'

### Steps to reproduce
This source.cpp fails to compile:

    #define CATCH_CONFIG_MAIN
    #include <catch.hpp>

    struct v{
        v(int,int) {}
        friend bool operator==(const v&lhs, const v&rhs) {return true;}
    };
    TEST_CASE("t") {
        REQUIRE(v(1,2) == v(3,4)); // compiles
        REQUIRE(v(1,2) == v{3,4}); // doesn't
        REQUIRE(v{1,2} == v(3,4)); // doesn't
        REQUIRE(v{1,2} == v{3,4}); // doesn't
    }

### Extra information
* Catch version: **v1.9.6**
* Operating System: **Win7x64**
* Compiler+version: **VS 2017 Community 15.3.0**

**Comment by philsquared** [comment]
This is because the macros are interpreting the commas within the braces as argument separators for the macro itself.
This has been solved in Catch2, which relies on variadic templates - and so can reconstruct the whole expression again. Best thing to do is to move to that. It's on the `catch2` branch for now - but will become the mainline soon (aiming for next week).

**Comment by Artalus** [comment]
Thank you, using `()` instead of `{}` is not a problem for now. Will wait for PSA about Catch2 release!
