### ISSUE TITLE
Cannot compile for UWP (Universal Windows Platform)

### ISSUE THREAD

**Issue by michaelcowan** [philsquared/Catch#1020]
### Description
I am porting an existing project that makes use of Catch to [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/whats-a-uwp). When compiling I get the following errors (amongst others):
```
error C3861: 'AddVectoredExceptionHandler': identifier not found
error C3861: 'SetThreadStackGuarantee': identifier not found
error C3861: 'RemoveVectoredExceptionHandler': identifier not found
error C3861: 'SetThreadStackGuarantee': identifier not found
error C3861: 'GetStdHandle': identifier not found
error C2065: 'CONSOLE_SCREEN_BUFFER_INFO': undeclared identifier
```
It would seem that UWP does not supply these classes.

### Steps to reproduce
1. Using VS2017 create a new UWP App
    _File -> New Project -> Installed -> Visual C++ -> Windows Universal ->DirectX 11 App (Universal Windows)_
2. Add _catch.hpp_ to the project
3. Include the header
```c
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"
```
4. Compile

### Extra information

* Catch version: **v1.9.6** also tried **v2.0.0-develop.3**

**Comment by horenmar** [comment]
Interesting. I guess it makes sense that Win32 APIs when building for UWPs, but I wonder why `CONSOLE_SCREEN_BUFFER_INFO` is not present either. Can UWP applications run in console?

**Comment by michaelcowan** [comment]
@horenmar Looking at the templates available and a quick Google seems to suggest that you _cannot_ create console application using UWP. This makes sense to me as the point in UWP (as I understand it) is that the 'App' can run on Desktop, Tablet, Phone, Console etc

**Comment by horenmar** [comment]
This should be fixed in Catch 2

**Comment by michaelcowan** [comment]
@horenmar Thats awesome, thanks very much!
I have manually tried this change and everything compiles as expected. 

I think maybe we got our wires crossed about the console though. Although I don't think you can create a console only App using UWP, it is still possible to write to the console output window using `OutputDebugString`.

**Comment by michaelcowan** [comment]
@horenmar I tried release [v2.0.0-develop.4](https://github.com/philsquared/Catch/releases/tag/v2.0.0-develop.4) and now I am getting:
```
error C2039: 'OutputDebugStringA': is not a member of '`global namespace''
```

Its also worth noting that when I replace this with my own `writeToDebugConsole` method, it is never actually called.

**Comment by CBaiz** [comment]
I had the same problem with OutputDebugStringA on Windows with Visual Studio 2017 in a console application project..
Solved it by writing this:


#include <windows.h>
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

**Comment by horenmar** [comment]
That is weird. We forward declared `OutputDebugStringA` to avoid including `windows.h` in the common path, so it looks like the final single include header gets stitched wrong.

**Comment by horenmar** [comment]
Can you check whether the attached single include works for you?
[catch.zip](https://github.com/philsquared/Catch/files/1338118/catch.zip)

**Comment by CBaiz** [comment]
I've tested it without `#include <windows.h>` and it works like a charm.
Good work and nice reaction time 👍

**Comment by michaelcowan** [comment]
@horenmar That build works for me too using UWP. Still no console output though. When a test fails all that is shown is 
```
Exception thrown at 0x00007FF9B3149E08 in testapp.exe: Microsoft C++ exception: Catch::TestFailureException at memory location 0x000000774BAFC554
```
And its lost in a lot of other debug output.

**Comment by horenmar** [comment]
@michaelcowan Well, UWP apps do not provide proper stdout, you will have to redirect it yourself to wherever.

We could do it as well, but the only place that is at least semi-guaranteed to exist is the debug output and that can already be pretty full.

**Comment by michaelcowan** [comment]
@horenmar A quick look at the Catch source and I can see its using `::OutputDebugStringA(...)` which _is_ available in UWP. Is it possible for UWP to be able to use this too without running into the issues with the exception handling originally reported?

To be clear, In my UWP application I can simply:

```C++
#include <windows.h>
// snip
    ::OutputDebugStringA("test");
```

**Comment by horenmar** [comment]
@michaelcowan I know. However, the debug output can already be quite noisy, thus I think it is better to let our user redirect stdout to wherever is most appropriate for their application (or use `-o`). I am willing to be convinced otherwise though.

**Comment by michaelcowan** [comment]
@horenmar Because I'm working on several platforms at once, it was consistency I was looking for.
I am using a config like this:
```cpp
Catch::ConfigData config;
config.showDurations = Catch::ShowDurations::Always;
config.useColour = Catch::UseColour::No;
session.useConfigData(config);
```
For iOS (XCode) the test results are written to the Output window.
For Windows and UWP the test results are not.

I found though that I can have all platforms write results to their output windows by adding:
```cpp
config.outputFilename = "%debug";
```

I'm not sure if this is a bug or not but from a user experience I expected all platforms to work the same.

That said I'm more than happy with the [build](https://github.com/philsquared/Catch/files/1338118/catch.zip)  you provided as it does exactly what I need with this tiny tweak.

Thanks for all the help and the impressively speedy updates - its really appreciated 👍

**Comment by horenmar** [comment]
@michaelcowan You could argue that the inconsistency stems from inconsistent behaviour between XCode and Visual Studio. By default, Catch writes its output to stdout. UWP apps do not show stdout anywhere, but it can be redirected by `freopen` and the like. It just so happens that XCode redirects stdout to its debug output on its own, while VS doesn't.

However, as you found out, you can ask Catch to redirect the output to a file (including a special file, `%debug`). Under everything that is not Visual Studio, the `%debug` file just writes to stdout. For Visual Studio, we use `OutputDebugStringA`, which does place the output to its debug output.

**Comment by michaelcowan** [comment]
@horenmar Yup, agreed. That makes sense to me.

**Comment by philsquared** [comment]
Is there anything outstanding on this issue?
@michaelcowan are you reasonably happy with where we are now?

**Comment by michaelcowan** [comment]
@philsquared Absolutely!

**Comment by philsquared** [comment]
Cool - thanks
