### ISSUE TITLE
Status of VS2005 (VC++ 8.0) support

### ISSUE THREAD

**Issue by mloskot** [philsquared/Catch#1029]
## Description

One user of our project reported (https://github.com/SOCI/soci/pull/593#issuecomment-331418068) that Catch is causing compilation failures with VC++ 8.0 from VS2005

```
2>test-odbc-access.cpp
2>C:\Github\hrabe\soci\tests\common-tests.h(573) : warning C4003: not enough actual parameters for macro 'SECTION'
2>C:\Github\hrabe\soci\tests\common-tests.h(573) : error C2059: syntax error : ')'
```

The [supported compilers wiki](https://github.com/philsquared/Catch/wiki/What-compilers-does-CATCH-work-with) has not been updated for ~4 years now.

Is VC++ 8.0 supported by Catch v1.9.6 or later?

### Extra information

* Catch version: **v1.9.6**
* Operating System: Windows
* Compiler+version: Visual C++ 8.0

**Comment by hrabe** [comment]
Still persists with **Catch v1.10.0** and may be related to https://connect.microsoft.com/VisualStudio/feedback/details/380090/variadic-macro-replacement

**Comment by mloskot** [comment]
The same issue happens with the later Catch v1.10.0

I assume such very old compilers are no longer supported.

Fair and perfectly understandable, but could anyone list minimum required version of GCC, clang, MSVC?

**Comment by horenmar** [comment]
Finally got back to working on Catch.

Looking at the linked issue, the largest problem is with macros that have an optional second argument for description, correct? For `TEST_CASE`s and variants, we recommend giving proper tags anyway, but `SECTION`s have the second argument too, that as far as I know, nobody uses. However, removing it would risk significant backward compatibility breakage.

As to the actual question, I don't think there is an authoritative enumeration of supported compilers short of Travis/AppVeyor list, which is not necessarily complete anyway -- ie I am fairly sure that VS 2010 is supported, but can't get it on AppVeyor.

**Comment by mloskot** [comment]
> Looking at the linked issue, the largest problem is with macros that have an optional second argument for description, correct? 

Yes.
The BW rationale makes sense.

> at least gcc 4.4 - gcc 6, clang 3.4 - clang 3.8 and VS 2013 - 2017 are supported.

Fair. I'll refer to the CI next time

Thanks!
