### ISSUE TITLE
How to extend custom MatcherBase

### ISSUE THREAD

**Issue by mwpowellhtx** [philsquared/Catch#1038]
Hello,

Using v1.10. Took me 30 minutes to more or less come up to speed, but it's working pretty decently now. Thanks for the great library!

Okay, now the substantive question. I want to specialize Catch::MatcherBase for one of my application exceptions, so I started with the boilerplate stuff,

```C++
class MyExceptionMatcher : public Catch::MatcherBase<MyException> {
public:

    MyExceptionMatcher() : MatcherBase() {}

    virtual bool match(const MyException& ex) const {
        return true; // TODO: TBD: or some other condition...
    }

    virtual std::string describe() const {
        return std::string("compose some description about the matcher")
    }
};
```

All that more or less based on the [docs](http://github.com/philsquared/Catch/blob/master/docs/matchers.md).

However, now the compiler is reporting the following exception:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2672	'Catch::ResultBuilder::captureMatch': no matching overloaded function found	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	129	
Error (active)		no instance of function template "Catch::ResultBuilder::captureMatch" matches the argument list	sock	g:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	129	
Error	C2893	Failed to specialize function template 'void Catch::ResultBuilder::captureMatch(const ArgT &,const MatcherT &,const char *)'	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	129	
```

So it would seem my work is not finished; however, I am not finding [instructions](http://github.com/philsquared/Catch/blob/master/docs/matchers.md) around this bit of detail.

Would it be possible to have the docs refreshed with the up-to-date knowledge? Or at least the changes to/from versions?

Thank you...

**Comment by mwpowellhtx** [comment]
This seems to all revolve around the macro [INTERNAL_CHECK_THAT](http://github.com/philsquared/Catch/blob/cd30dd1a70923c6a264d07a6c88229447e425590/include/internal/catch_capture.hpp#L175), however, would you mind providing a little guidance, or update the docs like I said, concerning just what/how I should be specializing the template method? I mean, this requires some access to the guts of ``Catch::ResultBuilder``, does it not?

**Comment by mwpowellhtx** [comment]
After [doing a little background reading around partial template specializations](http://stackoverflow.com/questions/30530364/explicit-specialization-of-member-function-template-in-source-file), it seems like I may need to do something such as this, near to my *Custom Matcher* struct:

```C++
namespace Catch {
    template<typename ArgT>
    inline void ResultBuilder::captureMatch<ArgT, nng_exception_matcher>(
        ArgT const& arg, nng_exception_matcher const& matcher, char const* matcherString) {
    }
}
```

I figure I need to allow for the ``ArgT`` on account that should be resolved by the ``INTERNAL_CHECK_THAT`` macro parameter.

However, this is still causing exceptions:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2768	'Catch::ResultBuilder::captureMatch': illegal use of explicit template arguments	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	55	
Error (active)		no instance of function template "Catch::ResultBuilder::captureMatch" matches the argument list	sock	g:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	132	
Error	C2244	'Catch::ResultBuilder::captureMatch': unable to match function definition to an existing declaration	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	55	
Error	C2672	'Catch::ResultBuilder::captureMatch': no matching overloaded function found	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	132	
Error	C2893	Failed to specialize function template 'void Catch::ResultBuilder::captureMatch(const ArgT &,const MatcherT &,const char *)'	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	132	
```

**Comment by mwpowellhtx** [comment]
@philsquared In and of the implementation itself, at least gauging by the [captureMatch implementation](http://github.com/philsquared/Catch/blob/a53ea307239095920270af807938e7870fa36362/include/internal/catch_result_builder.h#L122), it seems like maybe this should do the trick, however, I'm not sure the pass through ``arg`` quite aligns with the template function expectations. I could be missing something, but would you mind clarifying?

```C++
namespace Catch {
    template <>
    inline void ResultBuilder::captureMatch<nng::nng_exception, nng_exception_matcher>(
        nng::nng_exception const& ex, nng_exception_matcher const& matcher, char const* matcherString) {

        MatchExpression<nng::nng_exception const&, nng_exception_matcher const&> expr(ex, matcher, matcherString);
        setResultType(matcher.match(ex));
        endExpression(expr);
    }
}
```

Still with compiler errors, however:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2893	Failed to specialize function template 'void Catch::ResultBuilder::captureMatch(const ArgT &,const MatcherT &,const char *)'	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	145	
Error (active)		no instance of function template "Catch::ResultBuilder::captureMatch" matches the argument list	sock	g:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	145	
Error	C2672	'Catch::ResultBuilder::captureMatch': no matching overloaded function found	sock	G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\core\sock.cpp	145	
```

**Comment by mwpowellhtx** [comment]
@philsquared Reviewing the [ExceptionTests](http://github.com/philsquared/Catch/blob/master/projects/SelfTest/ExceptionTests.cpp), I wonder if I may be misunderstanding the role of a Custom Matcher. In other words, I want to "match" exceptions of mine based on some of their members. It seems like maybe that is not its purpose, but I could be wrong.

**Comment by philsquared** [comment]
Hi @mwpowellhtx,
I’m just returning from travelling, on my phone, but will try to respond briefly for now.

Regarding Matchers you shouldn’t need to do anything with captureMatch, or anything else internal to Catch. As long as your matches derive from MatcherBase, that should be all that’s needed. So I’m not sure what’s happening in your case. Could you show the usage?

Regarding the intent, if you’re trying to match exceptions then Matchers are not the right approach (unless you’ve caught the exception and now just treating it as any other object). There are a set of exception-oriented assertions, as you have now seen in the exception tests (they should be documented too).

Perhaps you could give a bit more detail about what you’re trying to do?

**Comment by horenmar** [comment]
As Phil said, Catch 1 Matchers do not work with thrown exception (you can match them after you catch the exceptions though). Catch 2 does provide an assertion for matching thrown exception, IIRC it is `REQUIRE_THROWS_MATCHES(expression, exception type, matcher for given exception type)`.

**Comment by mwpowellhtx** [comment]
@philsquared I would like to catch an exception with X-y-z conditions. However, reviewing the docs further, I'm not sure that's quite the purpose of *Matchers*. Rather, they are literally for comparing the template *arg* on the LHS, so to speak. That being said, is there a more natural way to evaluate said exceptions in a more natural way. By that I mean other than by:

```C++
CATCH_TRANSLATE_EXCEPTION(nng::nng_exception& ex) {
    /* Translating from std::exception parlance, we have:
    http://www.cplusplus.com/reference/exception/exception/what/ */
    return ex.what();
}
```

In other words, I've got a couple of members in the exception itself that I would like to evaluate inline with the macro.

Something like:

```C++
REQUIRE_THROWS_HAVING(/*do something*/, nng::nng_exception(ec_eanerr));
```

Something like this where I provide an exception against which to compare. From which you ought to be able to derive decltype, etc, etc, for expansion, and so on.

**Comment by mwpowellhtx** [comment]
@horenmar Yes, I am pulling v1.10 during my build process at the moment (i.e. Catch 1, I suppose). Yes, Catch 2, that might be interesting to look at.

@philsquared Although still in "development", how stable are those releases would you say if I pulled to those hash(es)?

**Comment by horenmar** [comment]
@mwpowellhtx Runtime-wise, Catch 2 should be stable. We have had some trouble with the stitching script making the single header release uncompilable under specific compile-time flag combinations (mostly UWP), but in general, it should work.

**Comment by mwpowellhtx** [comment]
@philsquared Okay, thanks for the response. I take to mean
the v2.0.0-develop.4 tag is stable enough. I will give that a try, thanks
again!

**Comment by philsquared** [comment]
Hi @mwpowellhtx - did you get anywhere with this?
Do we need to keep this ticket open, or are you happy for now?

**Comment by mwpowellhtx** [comment]
@philsquared I could not find the ``REQUIRE_THROWS_MATCHES`` macro (or ``CHECK_THROWS_MATCHES``). As far as I know I am pulling against the *HEAD*. I've been able to shoehorn in a macro of my own extending *Catch* for my own use: in this case, matching exceptions. It's a bit crude, bit it "works", for now.

**Comment by philsquared** [comment]
@mwpowellhtx it's on the catch2 branch

**Comment by mwpowellhtx** [comment]
@philsquared I see, that explains it. Yes, I'm not interested in being that close to the bleeding edge, just yet. It's exciting enough pulling against the *HEAD*. ;-) That said, when it's officially tagged with a deployed version, I'll definitely want to pull against that.

Closing for now. Thanks for the heads up.

**Comment by philsquared** [comment]
np. I'm trying to get Catch2 onto master as soon as possible!

**Comment by mwpowellhtx** [comment]
@philsquared There will be much celebrating (re: my 'Python affectations...).
