### ISSUE TITLE
Provide support for std::chrono::duration comparisons

### ISSUE THREAD

**Issue by mwpowellhtx** [philsquared/Catch#1039]
I have a *timed-section-impl* structure which wraps some section of arbitrary functional code (i.e. std::function) in a timed block. However, I get the following failure afterwards.

```C++
REQUIRE(after >= (before + timeout));
REQUIRE(after < (before + timeout * 2));
```

Where ``before`` and ``after`` are both *high_resolution_clock::now()* results, ``before`` and ``after`` the functional callback, respectively.

First is, the requirement is failing properly. However, the expansion doesn't know what to do with duration operands.

```
<path/to>/tests/timed_section_
impl.hpp(37): FAILED:
  REQUIRE( after >= (before + timeout) )
with expansion:
  {?} >= {?}
```

**Comment by horenmar** [comment]
We should be able to do that, but it will likely end up disabled by default, we would have to drag the `<chrono>` header into every file otherwise.

_It actually might be a good idea to make all std stringification specializations optional_

**Comment by mwpowellhtx** [comment]
@horenmar Thanks! I consider this a LOW priority, however, as contrasted with threading support. That one is a HUGE deal right now.

**Comment by horenmar** [comment]
This is now in Catch 2 branch.

**Comment by mwpowellhtx** [comment]
@horenmar Wow, thanks! I was going to suggest, I would be okay with a second include shimming in ``std::chrono`` support if it adds that much overhead.

Something like:

```C++
#include <catch/catch_std_chrono.hpp>
```

**Comment by horenmar** [comment]
It is disabled by default, [see documentation](https://github.com/philsquared/Catch/blob/catch2/docs/configuration.md#enabling-stringification)

**Comment by philsquared** [comment]
This is not in the single include, too.
@mwpowellhtx does this close your issue?

**Comment by mwpowellhtx** [comment]
@philsquared Looks good, thanks so much.

**Comment by philsquared** [comment]
Thanks!

**Comment by dan-ryan** [comment]
Anyone else having trouble turning this option on?
