### ISSUE TITLE
Query: Is there a Regex Matcher?

### ISSUE THREAD

**Issue by mwpowellhtx** [philsquared/Catch#1040]
I'd like to match a string based on whether its Regex can be found? Is something like that available OOB? I don't think it would be difficult to write one, but wanted to check first. Thanks!

**Comment by horenmar** [comment]
There is not.

**Comment by rustyx** [comment]
There is now, so for posterity, adding a [link to the docs](https://github.com/catchorg/Catch2/blob/devel/docs/matchers.md) and an example:

```c++
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>
using namespace Catch::Matchers;

TEST_CASE("my test") 
{
    std::string str = "Some value to test";

    REQUIRE_THAT(str, Matches(".*\bvalue\b.*"));
}
```
