### ISSUE TITLE
--section <section name> always runs the first

### ISSUE THREAD

**Issue by mwpowellhtx** [philsquared/Catch#1046]
I have a test module in the following form:

```C++
TEST_CASE("Run some tests", "[abc][foo]") {
    // ...
}
TEST_CASE("Run some other tests", "[def][bar]") {
    // ...
}
```

If I understood how to use the tags, the default one is the first, but I should be able to string several together.

I run the following, no problem:

```
cls && .\mytests.exe --section foo
```

So far so good. But when I run the following, the first test case is run:

```
cls && .\mytests.exe --section bar
```

**Comment by horenmar** [comment]
You are confusing tags and sections.

To select by tags, just write them out: `tests.exe [foo]`. A similar mechanism works for test cases: `"Run some other tests"`. Specific details, like how to specify tag "A" but NOT tag "B", can be found in the [documentation](https://github.com/philsquared/Catch/blob/master/docs/test-cases-and-sections.md#tags).

**Comment by mwpowellhtx** [comment]
Ah, I see. Thanks!
