### ISSUE TITLE
Text style (tab/space, trailing spaces)

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#105]
I noticed some files use the tab character, whereas most use spaces.
Also I've seen lines with trailing spaces, which I normally let my editor truncate.

I try to follow the style surrounding the location where I want to make a change, however because of the above, that's made more involved than necessary.

Therefore it maybe helpful to choose whichever one of tab and space and truncate trailing spaces.

my 0.02€

---

Files with tab characters:
- include/internal/catch_approx.hpp
- include/internal/catch_common.h
- include/internal/catch_debugger.hpp
- include/internal/catch_expression.hpp
- include/internal/catch_generators.hpp
- include/internal/catch_stream.hpp
- projects/SelfTest/ConditionTests.cpp
- projects/SelfTest/MiscTests.cpp
- projects/VS2008/TestCatch/TestCatch/TestCatch.cpp
- projects/VS2010/TestCatch/TestCatch/TestCatch.cpp
- projects/runners/iTchRunner/internal/iTchRunnerAppDelegate.h

**Comment by horenmar** [comment]
These things never end, I just found trailing whitespace in 8 files and tabs instead of spaces in 7. 😄
