### ISSUE TITLE
[Reporter] compact reporter misses parentheses for REQUIRE_FALSE() report

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#1051]
In a report of the compact reporter (`--reporter compact`):
```
REQUIRE_FALSE( x != x );
```
yields
```
passed: !x != x for: !(1 != 1)
---------^-----^
```

instead of
```
passed: !(x != x) for: !(1 != 1)
---------^------^
```
I'll create a PR to correct this later.

**Comment by martinmoene** [comment]
@horenmar It appears the effect follows from `AssertionResult::getExpression()` in [`internal/catch_assertionresult.cpp(58)`](https://github.com/philsquared/Catch/blob/c2b7bd15c092e2528f52bf26046e3c55ca629392/include/internal/catch_assertionresult.cpp#L58) and [dates from 5 years ago](https://github.com/philsquared/Catch/blame/c2b7bd15c092e2528f52bf26046e3c55ca629392/include/internal/catch_assertionresult.cpp#L58).

`getExpression()` is used in:
- [`catch_reporter_compact.hpp(202)`](https://github.com/philsquared/Catch/blob/c2b7bd15c092e2528f52bf26046e3c55ca629392/include/reporters/catch_reporter_compact.cpp#L202)
- [`catch_reporter_tap.hpp(180)`](https://github.com/philsquared/Catch/blob/c2b7bd15c092e2528f52bf26046e3c55ca629392/include/reporters/catch_reporter_tap.hpp#L180)
- [`catch_reporter_xml.cpp(124)`](https://github.com/philsquared/Catch/blob/c2b7bd15c092e2528f52bf26046e3c55ca629392/include/reporters/catch_reporter_xml.cpp#L124)

? Would it be ok for all reporters to change
```
return '!' + std::string(m_info.capturedExpression);
```
in
```
return "!(" + std::string(m_info.capturedExpression) + ")";
```

**Comment by philsquared** [comment]
Yep - that all seems reasonable. I've applied the fix to both 1.x and Catch2 branches - thanks for that!

**Comment by martinmoene** [comment]
Thanks Phil!
