### ISSUE TITLE
2.0.0d5 is missing a #pragma warning(pop), confusing VS, disabling warnings in code including catch

### ISSUE THREAD

**Issue by jamespharvey20** [philsquared/Catch#1072]
Using v2.0.0-develop.5, on Visual Studio 2017 15.5 Preview 2, seeing: 

    single_include\catch.hpp(978): warning C5032: detected #pragma warning(push) with no corresponding #pragma warning(pop)

It appears Visual Studio gets its warning state all confused when a `#include` has mismatching `push`/`pop` statements.  For me, it's having the effect of dramatically decreasing the warning level in any of my code that includes `catch.hpp`.  (I think it has the effect of setting the warning level to 0.)

I did look through the structure of the `#pragma warhing(push|pop)`, as shown below.  It's right.

I also get some warnings that aren't temporarily disabled.  So, I've commented out all of the `#pragma warning(push|pop)` statements, and I'm wrapping it with a `#pragma warning(push, 0)` temporarily.

    :    24 #ifdef __clang__
    :    25 #   ifdef __ICC
    :    26 #       pragma warning(push)
    ...
    :    28 #   else
    ...
    :    45 #endif
    ...
    :   532 #ifdef _MSC_VER
    :   533 #pragma warning(push)
    ...
    :   535 #endif
    ...
    :   970 #ifdef _MSC_VER
    :   971 #pragma warning(pop)
    :   972 #endif
    ....
    :   977 #ifdef  _MSC_VER
    :   978 #pragma warning(push)
    ...
    :   983 #endif
    ....
    :  7961 #if defined(_MSC_VER)
    :  7962 #pragma warning(push)
    ...
    :  7964 #endif
    ...    
    :  7974 #if defined(_MSC_VER)
    :  7975 #pragma warning(pop)
    :  7976 #endif
    ...
    : 11936 #ifdef __clang__
    : 11937 #    ifdef __ICC
    : 11938 #        pragma warning(pop)
    : 11939 #    else
    ...
    : 11944 #540 

And, here's the warnings that show with `catch.hpp` as-is, in files that include it without `#define CATCH_CONFIG_MAIN`:

    catch.hpp(158): warning C4668: 'WINAPI_FAMILY' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    catch.hpp(158): warning C4668: 'WINAPI_FAMILY_APP' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    catch.hpp(978): warning C5032: detected #pragma warning(push) with no corresponding #pragma warning(pop)

And, here's the warnings that show with `catch.hpp` included after `#define CATCH_CONFIG_MAIN`:

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\winbase.h(7356): warning C5039: 'TpSetCallbackCleanupGroup': pointer or reference to potentially throwing function passed to extern C function under -EHc. Undefined behavior may occur if this function throws an exception.
catch.hpp(7169): error C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.12.25816\include\exception(17): note: see declaration of 'std::uncaught_exception'
catch.hpp(10604): warning C4061: enumerator 'Catch::`anonymous-namespace'::Duration::Unit::Auto' in switch of enum 'Catch::`anonymous-namespace'::Duration::Unit' is not explicitly handled by a case label
  catch.hpp(10556): note: see declaration of 'Catch::`anonymous-namespace'::Duration::Unit'
catch.hpp(10604): warning C4061: enumerator 'Catch::`anonymous-namespace'::Duration::Unit::Nanoseconds' in switch of enum 'Catch::`anonymous-namespace'::Duration::Unit' is not explicitly handled by a case label
  catch.hpp(10556): note: see declaration of 'Catch::`anonymous-namespace'::Duration::Unit'
catch.hpp(10620): warning C4061: enumerator 'Catch::`anonymous-namespace'::Duration::Unit::Auto' in switch of enum 'Catch::`anonymous-namespace'::Duration::Unit' is not explicitly handled by a case label
  catch.hpp(10556): note: see declaration of 'Catch::`anonymous-namespace'::Duration::Unit'
catch.hpp(11559): warning C4061: enumerator 'Catch::ResultWas::Exception' in switch of enum 'Catch::ResultWas::OfType' is not explicitly handled by a case label
  catch.hpp(1132): note: see declaration of 'Catch::ResultWas::OfType'
catch.hpp(11559): warning C4061: enumerator 'Catch::ResultWas::Unknown' in switch of enum 'Catch::ResultWas::OfType' is not explicitly handled by a case label
  catch.hpp(1132): note: see declaration of 'Catch::ResultWas::OfType'
catch.hpp(11559): warning C4061: enumerator 'Catch::ResultWas::Ok' in switch of enum 'Catch::ResultWas::OfType' is not explicitly handled by a case label
  catch.hpp(1132): note: see declaration of 'Catch::ResultWas::OfType'
catch.hpp(11559): warning C4061: enumerator 'Catch::ResultWas::FailureBit' in switch of enum 'Catch::ResultWas::OfType' is not explicitly handled by a case label
  catch.hpp(1132): note: see declaration of 'Catch::ResultWas::OfType'
catch.hpp(11559): warning C4061: enumerator 'Catch::ResultWas::ExpressionFailed' in switch of enum 'Catch::ResultWas::OfType' is not explicitly handled by a case label
  catch.hpp(1132): note: see declaration of 'Catch::ResultWas::OfType'
catch.hpp(11559): warning C4061: enumerator 'Catch::ResultWas::DidntThrowException' in switch of enum 'Catch::ResultWas::OfType' is not explicitly handled by a case label
  catch.hpp(1132): note: see declaration of 'Catch::ResultWas::OfType'
catch.hpp(4857): warning C4583: 'Catch::clara::detail::ResultValueBase<T>::m_value': destructor is not implicitly called
          with
          [
              T=Catch::clara::detail::ParseState
          ]
  catch.hpp(4857): note: while compiling class template member function 'Catch::clara::detail::ResultValueBase<T>::~ResultValueBase(void)'
          with
          [
              T=Catch::clara::detail::ParseState
          ]
  catch.hpp(5117): note: see reference to function template instantiation 'Catch::clara::detail::ResultValueBase<T>::~ResultValueBase(void)' being compiled
          with
          [
              T=Catch::clara::detail::ParseState
          ]
  catch.hpp(4874): note: see reference to class template instantiation 'Catch::clara::detail::ResultValueBase<T>' being compiled
          with
          [
              T=Catch::clara::detail::ParseState
          ]
  catch.hpp(5114): note: see reference to class template instantiation 'Catch::clara::detail::BasicResult<Catch::clara::detail::ParseState>' being compiled
catch.hpp(978): warning C5032: detected #pragma warning(push) with no corresponding #pragma warning(pop)
```

**Comment by horenmar** [comment]
Thanks, I've found the missing `warning(pop)` and added it back.

I've also guarded the usage of `WINAPI_FAMILY` macros with a check whether they are defined. Can you test the attached single include?

[catch.zip](https://github.com/philsquared/Catch/files/1426615/catch.zip)

**Comment by jamespharvey20** [comment]
Thanks!  Compiles clean in a file including it without `#define CATCH_CONFIG_MAIN`.  With the define, of course, has the other warnings still.

**Comment by horenmar** [comment]
@jamespharvey20 Do you enable C4061 explicitly, or does the new Preview version turn it on for `/W4`?


Anyway, I'll probably just add it to suppression and ensure that C4062 is enabled for our builds.

**Comment by horenmar** [comment]
I am going to mark this as resolved. If you want warnings above warning level `/W4` silenced, please open up a dedicated issue.

**Comment by jamespharvey20** [comment]
@horenmar, I use `/Wall` and explicitly disable warnings that I'll never want to know or do anything about (4820, padding added for alignment, etc.)  I respect if a library doesn't want to be `/Wall` compliant, but usually hope they will be.  So, I'll open up dedicated issues but respect if it becomes a "won't fix".

c672512 does take care of those warnings.

**Comment by horenmar** [comment]
@jamespharvey20 `/Wall` is not supported, because STL does not support it either and AFAIK there is no `-isystem` analog for `cl.exe`. However, we are willing to fix specific warnings, if they seem sane enough (C4820 is not).

**Comment by bnason-nf** [comment]
Hi @horenmar,

Would you maybe be willing to add a minor patch something like the one below to deal with projects that use /Wall but include catch.hpp? If so I'm happy to create a new issue and/or a pull request for that.

Thanks,
Benbuck

```
diff --git a/single_include/catch2/catch.hpp b/single_include/catch2/catch.hpp
index b1b2411d..2f690494 100644
--- a/single_include/catch2/catch.hpp
+++ b/single_include/catch2/catch.hpp
@@ -43,6 +43,9 @@
 #    pragma GCC diagnostic push
 #    pragma GCC diagnostic ignored "-Wunused-variable"
 #    pragma GCC diagnostic ignored "-Wpadded"
+#elif defined _MSC_VER
+#    pragma warning(push, 3)
+#    pragma warning(disable:5045) // Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
 #endif
 // end catch_suppress_warnings.h
 #if defined(CATCH_CONFIG_MAIN) || defined(CATCH_CONFIG_RUNNER)
@@ -1652,6 +1655,7 @@ struct ratio_string<std::milli> {
 #pragma warning(disable:4018) // more "signed/unsigned mismatch"
 #pragma warning(disable:4312) // Converting int to T* using reinterpret_cast (issue on x64 platform)
 #pragma warning(disable:4180) // qualifier applied to function type has no meaning
+#pragma warning(disable:4868) // compiler may not enforce left-to-right evaluation order in braced initializer list
 #endif

 namespace Catch {
@@ -14354,6 +14358,8 @@ using Catch::Detail::Approx;
 #    endif
 #elif defined __GNUC__
 #    pragma GCC diagnostic pop
+#elif defined _MSC_VER
+#    pragma warning(pop)
 #endif

 // end catch_reenable_warnings.h
```
