### ISSUE TITLE
commandline to filter section names

### ISSUE THREAD

**Issue by atultripathy** [philsquared/Catch#110]
Hi, 
It would be great if we could provide a command line option similar to -t "testname" 
eg. -c "sectionname" 
I have a set of test cases where i have written 

TEST_CASE(testname){
 SECTION("UNIT_login" ,"description"){}
 SECTION("SUBMIT_login" ,"description"){}
}

SO if i have to run only the sections with SUBMIT in their name i could specify 
-c "SUBMIT*"
testname is corresponding to the login function that is being tested.
This would be of great help.

**Comment by phcerdan** [comment]
Same request here. What about a new macro: SECTION.("visualizeTag", "description") hidden by default, so it runs only when specific command line argument is provided, ie. -st "visualizeTag".
Cannot that be implemented using if statements? However, it would require to have user provided command line arguments.

**Comment by philsquared** [comment]
It took a while but, for anyone still watching this ticket, the ability to run specific sections is in.
See: https://github.com/philsquared/Catch/blob/master/docs/command-line.md#run-section
Note the caveats there.
