### ISSUE TITLE
Windows crtdbg support

### ISSUE THREAD

**Issue by hpesoj** [philsquared/Catch#120]
Microsoft's functions found in <crtdbg.h> can be used to diff the state of the heap in order to detect memory leaks.  Attempting to use this in combination with your CATCH framework (which is fantastic btw -- apart from the lack of documentation) is proving difficult, as the unit test macros seem to allocate memory on the heap.  Here is the class I am using:

```
#include <crtdbg.h>

class MemoryCheck
{
private:
  _CrtMemState m_oldState;

public:
  MemoryCheck()
  {
    _CrtMemCheckpoint(&m_oldState);
  }

  ~MemoryCheck()
  {
    _CrtMemState newState;
    _CrtMemState stateDiff;

    _CrtMemCheckpoint(&newState);
    int isDifferent = _CrtMemDifference(&stateDiff, &m_oldState, &newState);

    REQUIRE(isDifferent == 0);
  }
};
```

This doesn't work:

```
{
  MemoryCheck memoryCheck;
  REQUIRE(true);
}
```

But this does work:

```
REQUIRE(true);
{
  MemoryCheck memoryCheck;
  REQUIRE(true);
}
```

And so does this:

```
REQUIRE(true);
{
  MemoryCheck memoryCheck;
  REQUIRE(true);
  REQUIRE(1 == int(1));
}
```

But this doesn't:

```
REQUIRE(true);
{
  MemoryCheck memoryCheck;
  REQUIRE(true);
  REQUIRE(int(1) == int(1));
}
```

But this does:

```
REQUIRE(true);
REQUIRE(int(1) == int(1));
{
  MemoryCheck memoryCheck;
  REQUIRE(true);
  REQUIRE(int(1) == int(1));
}
```

I guess this is due to different allocation being made for different types of expression.

But anyway, my question is whether it is possible to reliably incorporate this kind of memory check into a CATCH unit test, or if it could be made to work?  Thanks for your help.

**Comment by gnobbi** [comment]
Is there any update i ran into the same Problem.

**Comment by horenmar** [comment]
I have integrated Windows crtdbg leak checking with Catch in a branch and it will probably go into the next release.

For now it is supported only when Catch supplies its own main.
