### ISSUE TITLE
won't compile with embedded gcc 3.4.2

### ISSUE THREAD

**Issue by wbullaughey** [philsquared/Catch#142]
gcc 3.4.2 is old but its what we used for our embedded system. It gets errors like:
error: call of overloaded `compare(const unsigned int&, const int&)' is ambiguous

**Comment by horenmar** [comment]
If someone opens a PR which adds support on an overly old compiler, without breaking the current ones and adding too much maintenance burden, it can get merged, but I don't think either of us will be trying to keep mainline support for it.
