### ISSUE TITLE
Between generator really only works for ints

### ISSUE THREAD

**Issue by dhait** [philsquared/Catch#147]
Try `between(0.1, 0.9)`
It's not clear what this even means, so the results are definitely unexpected.

A better approach might be be something like this:
    `between(0.1, 0.9, 0.1)`
where the third parameter is a step size.

**Comment by horenmar** [comment]
The (undocumented and unfinished) generators in Catch 1 (the current version) are considered deprecated. They are coming back in Catch 2 (rewrite dropping compatibility with C++98), but until then, there is no more support for them.
