### ISSUE TITLE
Fix for vc2005 warning C4312: 'reinterpret_cast' : conversion from 'int' to 'ClassName *' of greater size

### ISSUE THREAD

**Issue by RossBencina** [philsquared/Catch#148]
Fixes the following MSVC 2005 warning when doing tests like
```cpp
ClassName *p = 0;

REQUIRE( p != 0 );
```
`warning C4312: 'reinterpret_cast' : conversion from 'int' to 'ClassName *' of greater size`

int needs to be cast to intptr_t apparently:

old:
```cpp
// pointer to int (when comparing against NULL)
    template<Operator Op, typename T> bool compare( int lhs, T\* rhs ) {
-        return Evaluator<T*, T*, Op>::evaluate( reinterpret_cast<T_>( lhs ), rhs );
    }
    template<Operator Op, typename T> bool compare( T_ lhs, int rhs ) {
-        return Evaluator<T*, T*, Op>::evaluate( lhs, reinterpret_cast<T*>( rhs ) );
    }
```
new:
```cpp
// pointer to int (when comparing against NULL)
    template<Operator Op, typename T> bool compare( int lhs, T\* rhs ) {
+        return Evaluator<T*, T*, Op>::evaluate( reinterpret_cast<T_>( (intptr_t)lhs ), rhs );
    }
    template<Operator Op, typename T> bool compare( T_ lhs, int rhs ) {
+       return Evaluator<T*, T*, Op>::evaluate( lhs, reinterpret_cast<T*>( (intptr_t)rhs ) );
    }
```

**Comment by philsquared** [comment]
I'm not sure what happened to this one in the intervening years - sorry about that.
@RossBencina is it still of any relevance to you?

**Comment by horenmar** [comment]
It still exists when Catch's SelfTest is compiled by MSVC 2015 U3 for x64.

```
<snip>\include\internal\catch_evaluate.hpp(160): warning C4312: 'reinterpret_cast': conversion from 'int' to 'ClassName *' of greater size
  <snip>\include\internal\catch_expression_lhs.hpp(110): note: see reference to function template instantiation 'bool Catch::Internal::compare<Catch::Internal::IsEqualTo,ClassName>(T *,int)' being compiled
          with
          [
              T=ClassName
          ]
  <snip>\include\internal\catch_expression_lhs.hpp(108): note: while compiling class template member function 'void Catch::BinaryExpression<T,Catch::Internal::IsEqualTo,const int &>::endExpression(void) const'
          with
          [
              T=ClassName *const &
          ]
  <snip>\projects\SelfTest\TrickyTests.cpp(383): note: see reference to function template instantiation 'void Catch::BinaryExpression<T,Catch::Internal::IsEqualTo,const int &>::endExpression(void) const' being compiled
          with
          [
              T=ClassName *const &
          ]
  <snip>\projects\SelfTest\TrickyTests.cpp(383): note: see reference to class template instantiation 'Catch::BinaryExpression<T,Catch::Internal::IsEqualTo,const int &>' being compiled
          with
          [
              T=ClassName *const &
          ]
```

**Comment by lightmare** [comment]
Why don't you cant the pointer to `intptr_t` instead?

**Comment by philsquared** [comment]
@lightmare aside from the fact that `intptr_t` is only available from C99 or C++11, IIRC this issue comes up when you do something like:

`REQUIRE( myObj == NULL ); `

`NULL` expands to 0, which gets deduced in the template as an `int` then later compared against the pointer. So it needs to be cast to the pointer type it's being compared against for it to compile cleanly.

**Comment by lightmare** [comment]
Catch already includes `<stdint.h>` for `uint64_t`, and fakes it on windows; can just as well fake `intptr_t`.

**Comment by philsquared** [comment]
As I said it's not actually about that. The int is coming to us from the expansion of `NULL`

**Comment by lightmare** [comment]
That doesn't answer my original question: why not cast the pointer instead?
```c++
template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
        return Evaluator<intptr_t, intptr_t, Op>::evaluate( reinterpret_cast<intptr_t>( lhs ), rhs );
}
```
Apart from the fact that it's as unreliable as casting `int` to pointer, at least it won't trigger warnings.

**Comment by philsquared** [comment]
Hmm... looking at that "fakes it for Windows" code that doesn't look terribly sensible. I'll have to review that.
If, as you're saying, casting to `intptr_t` (or a "fake version") avoids the warning that may be something to consider.

**Comment by horenmar** [comment]
There is a simple reason I decided to disable the warning for MSVC, rather than cast the pointer to `intptr_t`, it doesn't take dependency on a non-standard header/define, especially since we recently had to add various workarounds for cygwin and MinGW (ie 1ca8cefa9afa94f8323a9b7c2e67b16894c32fdd, c6178601c5c87b50e3114b8a8043d1ee6dfb4041, others).
