### ISSUE TITLE
Help for configuring reporter

### ISSUE THREAD

**Issue by sriluxman** [philsquared/Catch#156]
Hi,
I would like to try Catch for unit testing on a embedded platform. We have our own IDE (GCC V4.1.2).
Catch was really impressive coz within few seconds I was able to run unit tests streamed the result to http service and view it using a web browser.
But the problem is - I have no idea how to get different formats of report (xml for eg). (There will be no command line support)
Also the tests will be run in a real-time target system.so I would like to configure the runner in realtime.
Is it possible to get some data regarding this?
(in short, how to configure the reporter format and test runner(without using command line options)). Thanks!

**Comment by horenmar** [comment]
As far as I can tell, this has been mostly solved back in 2013 and there

**Comment by gelldur** [comment]
Now we have: `CATCH_CONFIG_DEFAULT_REPORTER`
https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#default-reporter

Example usage:
```
option(CATCH_INSTALL_DOCS "" OFF)
set(CATCH_CONFIG_DEFAULT_REPORTER "compact" CACHE STRING "" FORCE)
set(CATCH_CONFIG_ENABLE_ALL_STRINGMAKERS 1 CACHE BOOL "" FORCE)

fetchcontent_declare(Catch2
	GIT_SHALLOW TRUE
	GIT_REPOSITORY https://github.com/catchorg/Catch2.git
	GIT_TAG v3.5.0)

fetchcontent_makeavailable(Catch2)
```
