### ISSUE TITLE
OR tags didn't do what I expected

### ISSUE THREAD

**Issue by colonelsammy** [philsquared/Catch#165]
The following was tested using the Integration branch.  Perhaps I defined the tags incorrectly (I was guessing!) ?

```
TEST_CASE("one/1", "[t1][t2]")
{
    REQUIRE(true);
    SECTION("t1/1","[t3][t4]")
    {
        REQUIRE(true);
    }
}

TEST_CASE("one/2", "[t1]")
{
    REQUIRE(true);
}

TEST_CASE("one/3", "[t1]")
{
    REQUIRE(true);
}

TEST_CASE("one/4", "[t2]")
{
    REQUIRE(true);
} 
```

I've run this with the following, which work as expected except for 'OR', which apparently only runs the first 3 test cases.  What have I done wrong?

```
 -s -g [t1]
 -s -g [t1][t2]
 -s -g [t1],[t2]
 -s -g [t2] 
```

**Comment by horenmar** [comment]
This has been since fixed in master.
