### ISSUE TITLE
Benchmarking tests?

### ISSUE THREAD

**Issue by cloderic** [philsquared/Catch#167]
I'm a happy user of Catch and I'm looking for the same kind of simplicity for performance test.

I've found that: http://bruun.co/2012/02/07/easy-cpp-benchmarking

I like the unit test like approach, a way to log the results to a history file would also be nice. 

Short story long I think it would be a nice addition to Catch. 

Any plan for this kind of features?

**Comment by cviebig** [comment]
+1

**Comment by horenmar** [comment]
Since this is not going into Catch Classic, but might get into Catch 2 at some point, I am going to close it in favour of #852.
