### ISSUE TITLE
Unsigned values don't report the same way

### ISSUE THREAD

**Issue by colonelsammy** [philsquared/Catch#168]
This is irritating, but not really a problem.  The result of comparing an unsigned value against a hex literal outputs the lhs as hex and the rhs as decimal even though the hex literal was on the rhs in the original expression :-O :

  REQUIRE( bits == 0x00800002 )
with expansion:
  0x800003 == 8388610

It does at least put the hex value in the REQUIRE block...but it should be consistent in the expansion.

I guess I would like to have hex output if either side is a hex literal but I imagine that would be significantly more work!  Not sure what Octal would do either...

**Comment by horenmar** [comment]
I created a follow-up issue with current state of reporting, closing this one.
