### ISSUE TITLE
Signed-ness issues on AIX compiler

### ISSUE THREAD

**Issue by jbrwilkinson** [philsquared/Catch#170]
The following code:

``` c++
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
#include <vector>

TEST_CASE("To/Sign/Or/Not/To/Sign", "who ever uses this bit")
{
  std::vector<int> vec;
  REQUIRE(vec.size() == 0);
}
```

Produces this compile output when compiled on AIX:

"../misc/Catch/include/internal/catch_console_colour.hpp", line 17.24: 1540-0198 (W) The omitted keyword "private" is assumed for base class "NonCopyable".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.29: 1540-0219 (S) The call to "Internal::compare<0>" has no best match.
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.52: 1540-1228 (I) Argument number 1 is an lvalue of type "const unsigned long".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.59: 1540-1228 (I) Argument number 2 is an lvalue of type "const int".
"../misc/Catch/include/internal/catch_evaluate.hpp", line 83.10: 1540-1202 (I) No candidate is better than "Catch::Internal::compare<0,unsigned long,int>(const unsigned long &, const int &)".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.52: 1540-1231 (I) The conversion from argument number 1 to "const unsigned long &" uses "the identity conversion".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.59: 1540-1231 (I) The conversion from argument number 2 to "const int &" uses "the identity conversion".
"../misc/Catch/include/internal/catch_evaluate.hpp", line 91.32: 1540-1202 (I) No candidate is better than "Catch::Internal::compare<0>(unsigned long, int)".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.52: 1540-1231 (I) The conversion from argument number 1 to "unsigned long" uses "an lvalue-to-rvalue transformation".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 84.59: 1540-1231 (I) The conversion from argument number 2 to "int" uses "an lvalue-to-rvalue transformation".
"../misc/Catch/include/internal/catch_expression_lhs.hpp", line 82.30: 1540-0700 (I) The previous message was produced while processing "Catch::ExpressionLhs<const unsigned long &>::captureExpression<0,int>(const int &)".
"unsigned.cpp", line 5.2: 1540-0700 (I) The previous message was produced while processing "TestCaseFunction_catch_internal_5()".
gmake: **\* [unsigned.ibm.o] Error 1
gmake: Target `build' not remade because of errors.

The fix is trivial:

``` c++
  REQUIRE(vec.size() == 0U);
```

...but tracking down the offending line of code is hard in a large test.

**Comment by philsquared** [comment]
This is a really old ticket - sorry I never responded the first time around.
I don't have access to AIX to try this now - but obviously Catch has changed substantially in the intervening years - so I'm going to close this on the basis that, if it's still an issue, someone else will report it again.
Obviously if you're watching this and have any other information feel free to re-open.
