### ISSUE TITLE
test case names mangled in test list output

### ISSUE THREAD

**Issue by wichert** [philsquared/Catch#177]
I tend to put the name of the thing being tested in the name of the test case. That resulted in those code for some [libpqxx](http://pqxx.org/development/libpqxx/) extensions:

``` c++
TEST_CASE("pqxx::string_traits<boost::uuids::uuid>", "UUID conversion") {
    ...
}

TEST_CASE("pqxx::string_traits<map<string,string>>", "HSTORE conversion") {
    ...
}
```

Printing the list of known tests with `-l tests` shows that catch mangled the names:

```
$ ./runtests -l tests  pg::escape
  pg::unescape
  pqxx::string_traits<boost::uuids::uu-
  id>
  pqxx::string_traits<map<string
  ,string>>
  LRU
```

**Comment by philsquared** [comment]
Obviously this is a very old issue. I'm not sure when, but it was also a long time ago that I changed the layout in question so it didn't try to fit the tags in a separate column.
Therefore I'm going to close this issue.
