### ISSUE TITLE
please git tag versions of catch

### ISSUE THREAD

**Issue by kapouer** [philsquared/Catch#197]
It is easier for distributors (like debian) to package software
when it has been properly tagged.
By the way, do you think catch is ready to be distributed in debian/testing ?

Regards,
Jérémy.

**Comment by DavidEGrayson** [comment]
I started a discussion there: https://groups.google.com/forum/?fromgroups#!topic/catch-forum/Z03uq5ujRgQ

**Comment by philsquared** [comment]
Following up - I've now fully committed to Semantic Versioning - and started tagging builds.

**Comment by DavidEGrayson** [comment]
Great!  I'll fix my MSYS2 package to use version 1.2.0!

**Comment by kapouer** [comment]
Great ! i've just uploaded updated debian package.
I suppose i can close this now.
