### ISSUE TITLE
catch.hpp can generate a biblical flood of warnings

### ISSUE THREAD

**Issue by alienscience** [philsquared/Catch#208]
Hello,
   I compile using g++ (4.8.0) with the following flags:

```
  g++ -Wall -pedantic -Weffc++
```

The version of catch.hpp that was generated as follows:

```
   Generated: 2013-10-23 15:34:32.120349
```

gives 308 warnings.

Lifes probably too short to worry about them. Especially in such a useful test framework.

However, they are a pain and hide warnings that I care about in my own code.

Would it be possible to add the following lines to the catch.hpp header that is available for download?

```
#ifdef __GNUC__
#pragma GCC system_header
#endif
```

This would turn off all warnings for users of the catch.hpp header no matter what their compiler flags are set to.

**Comment by socantre** [comment]
@samaursa To get the compile command Xcode is executing you can go to the Xcode log navigator (Command-8, I think), select the log for the relevant build, select the compile step that produces the warnings, and press the disclosure button. This will show the entire command Xcode issues to do the compilation.

See the screen shot [here](http://stackoverflow.com/a/18173138/365496).

**Comment by horenmar** [comment]
Compiling Catch with `g++ -Wall -pedantic -Weffc++` currently gives no warnings, so I am going to close this.
