### ISSUE TITLE
Can't use INFO macro in other macro

### ISSUE THREAD

**Issue by Slonegg** [philsquared/Catch#209]
For example, if you want to use approximate comparison and print arguments.

```
#define CHECK_IS_APPROX(E1, E2, rtol)\
    {\
        INFO(#E1 << " :=\n" << E1)\
        INFO(#E2 << " :=\n" << E2)\
        CHECK( isApprox(E1, E2, rtol) );\
    }
```

This leads to multiple declarations of Catch::ScopedMessage.

**Comment by philsquared** [comment]
It's been a long time, but I believe the `__COUNTER__` change should have made this possible (I tried the example out and it works for me now).

Is anyone still watching this who has a comment?
I'll close this soon otherwise.

**Comment by horenmar** [comment]
Since there has been no follow-up in a month, I am going to close this issue.
