### ISSUE TITLE
generators don't work in sections

### ISSUE THREAD

**Issue by philsquared** [philsquared/Catch#21]
Title says it all.
A generator within a section only seems to "generate" its first value. I suspect this is because generators and sections both cause test_cases to rerun - and section reruns presumably trump generator reruns.

**Comment by nathanaeljones** [comment]
Generators are pretty useful. Any plans for this?

**Comment by philsquared** [comment]
The unfinished, undocumented, generators implementation in current Catch is deprecated.
Generators will be a feature of Catch2, taking advantage of C++11 features.
The groundwork for interop with Section tracking has already been laid, but the direction I want to take generators in is going to be much easier - and more powerful - with C++11.
So I'm going to close this ticket now.
