### ISSUE TITLE
Running tests in parallel - Segfaults

### ISSUE THREAD

**Issue by dirvine** [philsquared/Catch#218]
Catch compiled with clang and the -fsanitize=address will give 
==472==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0xXXXXXXXXXX

This warning can be removed by setting (in linux/osx)
export ASAN_OPTIONS=alloc_dealloc_mismatch=0

However it's not a great idea and should possibly be addressed. If you run any tests in parallel then there are many random errors (read after free, segfaults etc.) a lot related to reading a pointer that's invalid. I think it has to do with the iostream access. 

I hope this is an obvious issue, I will try and get a look later on but in the meantime I hope this helps. 

Running catch's own tests in parallel (use a simple loop of std::async) will give many errors and if compiled again with -fsanitise=address in clang will give output similar to below: 
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
# ASAN:SIGSEGV

==32583==ERROR: AddressSanitizer: SEGV on unknown address 0x00000024 (pc 0x085332af sp 0xb06ecd40 bp 0xb06ecf38 T208)
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
ASAN:SIGSEGV
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
ASAN:SIGSEGV
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
ASAN:SIGSEGV
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
==32583==AddressSanitizer: while reporting a bug found another one.Ignoring.
ASAN:SIGSEGV

**Comment by horenmar** [comment]
Catch is not thread safe and currently is not meant to be. This means that only one thread can go through Catch's control structures, like REQUIRE, SECTION, etc.

I will take a look if ASAN still complains tomorrow.

**Comment by horenmar** [comment]
Asan leak-checker complains, so I will fill a new bug against that.
