### ISSUE TITLE
Dealing with failure: assertions/terminate

### ISSUE THREAD

**Issue by gnzlbg** [philsquared/Catch#220]
Right now there aren't any _documented_ ways of checking that my program fails correctly when no exceptions are involved. In particular, calls to `std::terminate` and to `assert()` (in debug mode only, i.e. when `NDEBUG` is not defined). 

In google-test one can do:  EXPECT_DEATH/EXPECT_DEBUG_DEATH to test for failure in general and failure in debug mode only as well as to test that the correct failure message is printed (although for asserts I always write a regexp that catches everything).

Note: a workaround is to define your ASSERT macro to throw an exception and _hope_ that no-one catches it. But this is just a workaround.

**Comment by gnzlbg** [comment]
Catch came up on reddit today and I mentioned the lack of this feature as basically the only thing that I missed from GTest (not that I went back to GTest just because of it tho). I know it is complicated to achieve this in a portable way, I just wanted to ask if there has been some progress on this.

**Comment by martinmoene** [comment]
[gnzlbg's comment on reddit](https://www.reddit.com/r/cpp/comments/3eozv4/a_game_of_tag_catch_c_automated_test_cases_in/cthl2jl).

**Comment by horenmar** [comment]
_This is copy pasted from #219 linked issue._

Since we have recently merged a signal rework, I decided to test this issue.

Given this source code against single-include `catch.hpp` generated from current master,
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <cassert>
#include <exception>

TEST_CASE("TEST-terminate", "[.term]"){
    SECTION("First") {
        std::terminate();
    }
}

TEST_CASE("TEST-assert", "[.ass]") {
    SECTION("First"){
        assert(false && "Hello");
    }
}
```
ran like this ` ./a.out -s -r compact [.ass]`, I get this output
```
a.out: test.cpp:15: void ____C_A_T_C_H____T_E_S_T____3(): Assertion `false && "Hello"' failed.
test.cpp:14: failed: fatal error condition with message: 'SIGABRT - Abort (abnormal termination) signal'
Failed 1 test case, failed 1 assertion.

Aborted (core dumped)
```
which shows failure at line 14, which is the line of "First" section macro.

If I run the code like this `./a.out -s -r compact [.term]`, I get this:
```
terminate called without an active exception
test.cpp:8: failed: fatal error condition with message: 'SIGABRT - Abort (abnormal termination) signal'
Failed 1 test case, failed 1 assertion.

Aborted (core dumped)
```
which also shows the failure at the correct section.


Seeing this, I am inclined to close this issue.

**Comment by philsquared** [comment]
Unlike #219, this issue is about testing for a fatal error - *then continuing*!
AFAICS that can only be achieved by going out of process (as the earlier parts of the thread discussed). So I think we need to leave this open (or close in favour of a single issue on the matter).

**Comment by horenmar** [comment]
Oh right. It seemed weird that the same person would open two issues about the same thing, but not weirder than other things I've seen in the issue backlog.

**Comment by kgreenek** [comment]
Major +1 for this feature. This is the one thing I miss from GTest. It's really important to be able to test that asserts happen when they should imo. Right now I have to use BOOST_ASSERT (or similar macro) as a workaround.

**Comment by horenmar** [comment]
Since this will not be added to Catch Classic, but might be added to Catch 2 at some point, I opened #853 instead.
