### ISSUE TITLE
Virtual function override warnings with nvcc

### ISSUE THREAD

**Issue by StephanDollberg** [philsquared/Catch#223]
Hi, 

When compiling the basic 

```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

example with the CUDA compiler nvcc (using .cu extension to not invoke the host compiler) I get the following warning

> catch.hpp(7058): warning: function "Catch::IStreamingReporter::testRunEnded(const Catch::TestRunStats &)" is hidden by "Catch::JunitReporter::testRunEnded" -- virtual function override intended?

It refers to the all-include file build version 13.

Maybe it's a problem with nvcc, any ideas? I am using nvcc from CUDA 5.5.

**Comment by philsquared** [comment]
This is quite old and in the meantime (a) the reports have been heavily refactored and (b) I've introduced `CATCH_OVERRIDE` to mark virtual overrides as such on supporting compilers.
The JUnitReporter uses `virtual` and `CATCH_OVERRIDE` throughout. So I believe this can be closed.

**Comment by horenmar** [comment]
Since there has been no follow-up in a month, I am going to close this issue.

**Comment by leimao** [comment]
This seems to be an NVCC issue. Switching to GCC becomes fine.
