### ISSUE TITLE
New feature request: Unicode (UTF-8) string literals as identifiers

### ISSUE THREAD

**Issue by pepr** [philsquared/Catch#238]
I am workin on a BDDtool that is already capable to produce Catch test skeletons out of the *.feature file. The problem is that .feature files should be the interface to people who need not to be programmers; however, thery may be quite good in their human language, and the human language may use non-ASCII characters. This way, they write the scenario definitions using some accented letters (not speaking about languages with completely different glyphs -- like the Russian language, Arabic, Korean, Japanese, Chinese, etc.) See this example of the output to Windows CMD console:

![catchoutputofnonascii](https://f.cloud.github.com/assets/1481366/2096600/4b4e0390-8f09-11e3-8a74-4cf0e2b8ee9e.png)

Are there any ideas how to introduce a mechanism that would work with UTF-8 sources the same way as with ASCII sources? The ASCII is UTF-8 automatically, anyway. The problem is that it would be nice if the narrow string literals could be transparently converted to wide string objects or literals so that the user need not to care. As far as I know Qt does something like that via implementing its own string. Anyway, Catch is more special case and it could possibly be solved by some simpler method (like wrapping it with macro that prepends L"to the string literal" and use the wstring ways to work with the string.

P.S. Thanks for the Catch. It is amazing how simple it could be to install and write tests when compared with CppUnit.

**Comment by Trass3r** [comment]
VS2015 finally implements C++11 unicode literals.
