### ISSUE TITLE
testing specific SECTION

### ISSUE THREAD

**Issue by paleozogt** [philsquared/Catch#276]
Given a test like this:

``` cpp
TEST_CASE("example") {
    SECTION("foo") {
        REQUIRE(true);

        SECTION("bar") {
            REQUIRE(true);
        }

        SECTION("baz") {
            REQUIRE(true);
        }
    }
}
```

I'd like to be able to run a specific section such as the "bar" section, either by specifying a tag or by "path" (.e.g., "example/foo/bar").  (Since `SCENARIO`/`GIVEN`/`THEN` is sort of the same as `TEST_CASE`/`SECTION`, I assume they'd inherit the same behavior.)

There's lots of reasons for this, but in my case I tend to have some pretty deeply nested `SECTIONS` with lots of stack-based setup (per Catch's advice, I've avoided class fixtures, which I feel makes the tests more readable).  When I'm developing a feature or chasing down a bug, I need to run only one of the "leaf" `SECTION`s-- running the others can be a waste of time (quite literally in the case of long tests).

See the ["How do I test a particular SECTION?"](https://groups.google.com/forum/?fromgroups#!searchin/catch-forum/section/catch-forum/hZlY90dftw8/KJhemWlZ3hMJ) discussion on the Catch google group for more details.

**Comment by horenmar** [comment]
This is in, see https://github.com/philsquared/Catch/blob/master/docs/command-line.md#run-section. Do note the limitations though.
