### ISSUE TITLE
Catch build 41 link error for ObjC++

### ISSUE THREAD

**Issue by bdb** [philsquared/Catch#278]
I have a very small .mm file that does a few tests with CATCH() macros.

I just updated to build 41 and now my test binary fails to link with:

Undefined symbols for architecture x86_64:
  "Catch::toString(NSString\* const&)", referenced from:
      Catch::ExpressionResultBuilder& Catch::ExpressionLhs<long const&>::captureExpression<(Catch::Internal::Operator)1, NSString_>(NSString_ const&)

I was using build 33 previously.
Xcode 5.1.1

I checked the header and it seems the toString() on line 7165 should be the implementation needed. So I'm not sure what's going on.

The only tests that I have where an NSString\* is a direct arg are like the following:

NSString *string = ...
CATCH(nil != string);

**Comment by horenmar** [comment]
I am unable to check this one on my own, can someone else try if it is still relevant?

I'd expect its not, but apparently someone referenced this only couple of months ago.

**Comment by bdb** [comment]
I've hit this again with 1.5.7 and had to work around it. Not sure why it cropped up again. Upgrading to 1.6.0 is on my todo list.

**Comment by philsquared** [comment]
Glad to see you're still watching, @bdb - but sorry to hear you're still having problems (or having them again).
I very much doubt anything relevant has changed between 1.5.7 and 1.6.0 - although it's always worth getting confirmation.
I'll try this again myself. I know I wasn't able to reproduce it before, but it looks like since I was last looking at this you posted your compiler flags, so I'll see if using those makes the difference.

**Comment by bdb** [comment]
Thanks Phil, I'm on Xcode 8.2.1 now. My workaround was the same as above, I simple removed const from the toString() functions.

Against 1.5.7
`@@ -1594,7 +1594,7 @@ std::string toString( std::nullptr_t );
 
 #ifdef __OBJC__
     std::string toString( NSString const * const& nsstring );
-    std::string toString( NSString * CATCH_ARC_STRONG const& nsstring );
+    std::string toString( NSString * CATCH_ARC_STRONG & nsstring );
     std::string toString( NSObject* const& nsObject );
 #endif
 
@@ -8202,7 +8202,7 @@ std::string toString( std::nullptr_t ) {
             return "nil";
         return "@" + toString([nsstring UTF8String]);
     }
-    std::string toString( NSString * CATCH_ARC_STRONG const& nsstring ) {
+    std::string toString( NSString * CATCH_ARC_STRONG & nsstring ) {
         if( !nsstring )
             return "nil";
         return "@" + toString([nsstring UTF8String]);
-- `

**Comment by bdb** [comment]
1.6 has the same issue and the same patch fixes it.

**Comment by kainjow** [comment]
Looks like to reproduce all you need is for main() to be in a C++ file, not Objective-C++. Then you'll get the error. ARC/MRC doesn't seem to be relevant.

**Comment by kainjow** [comment]
I wrote a minimum reproducible case:

Two main files `main.cpp` and `main.mm`, each with exact contents:

    #define CATCH_CONFIG_MAIN
    #include "catch.hpp"

and a a test file `test.mm`:

    #include "catch.hpp"
    TEST_CASE("test") {
        NSString *msg = @"test";
        CHECK(msg != (NSString*)nil);
    }

Then I used this `Makefile`:

    LDFLAGS := -stdlib=libc++ -framework Foundation
    
    all: mm_noarc mm_arc cpp_noarc cpp_arc
    
    mm_noarc:
    	clang++ main.mm test.mm -o $@ $(LDFLAGS)
    
    mm_arc:
    	clang++ -fobjc-arc main.mm test.mm -o $@ $(LDFLAGS)
    
    cpp_noarc:
    	clang++ main.cpp test.mm -o $@ $(LDFLAGS)
    
    cpp_arc:
    	clang++ -fobjc-arc main.cpp test.mm -o $@ $(LDFLAGS)
    
    clean:
    	rm -rf mm_noarc mm_arc cpp_noarc cpp_arc

The cpp_* targets will fail with current Catch, and pass with the fix from @bdb.

I tested with ARC/MRC just to see if those were related, but they are not. Still not clear why it fails. I've never seen `const` used with any of Cocoa's APIs, so it's probably best to avoid it altogether.
