### ISSUE TITLE
handle cross platform system exceptions (eg AV)

### ISSUE THREAD

**Issue by philsquared** [philsquared/Catch#3]

**Comment by obfuscated** [comment]
Hello,

I've just discovered that Catch doesn't have one of the most important features any decent test framework must have - catching crashes. I don't know how you've managed to use catch successfully, so many years without them, but I cannot!

I've tried the develop branch and there segmentation faults are caught correctly.
So, is there any chance that you'll merge the signal handling for unix that is available in the develop branch to the master branch?

**Comment by Darelbi** [comment]
Nice catch to Catch, for me it is not a problem since I use Catch with
CTest so crashes are already detected by CTest.

2015-02-25 13:16 GMT+01:00 obfuscated <notifications@github.com>:

**Comment by horenmar** [comment]
There has been a lot of discussion, bugs found and some changes since, so I am going to close this.

Bugs found in current Catch's support for signals/SEH can go into new issues.
