### ISSUE TITLE
Segmentation fault if two methods of same text fixture have same name.

### ISSUE THREAD

**Issue by lucidguppy** [philsquared/Catch#303]
https://github.com/lucidguppy/BowlingKata

commit :  156255cc75ee5cd1e89c38c91013e93f90125929

If two methods have the same name it does a segmentation fault.  It might be nice to have a static assert to check for this somehow.

**Comment by horenmar** [comment]
Since there has been no followup, I am going to close this and assume it works. If not, please reopen.
