### ISSUE TITLE
TAP reporter

### ISSUE THREAD

**Issue by daxim** [philsquared/Catch#309]
I request that Catch supports the Test Anything Protocol report output format.

**Comment by frostyfrog** [comment]
*subscribes to receive updates* +1, needed for "make check" with GNU automake

**Comment by frostyfrog** [comment]
*ping* I'm not entirely sure how good that last commit is. I did, however, make a quick and dirty first pass which (I think) follows the basic standard... If youu think it looks good @philsquared, then I could send a pull request your way. I'm not entirely confident in my commit and C++ abilities.

**Comment by trws** [comment]
@frostyfrog: did you ever put in a pull request from that branch?

**Comment by frostyfrog** [comment]
Now I have >_>

**Comment by horenmar** [comment]
I merged it to master + done some neccessary fixups (documentation pending). Any issues in the implementation should go to a new issue.
