### ISSUE TITLE
Compile error GCC < 4.6

### ISSUE THREAD

**Issue by SebDyn** [philsquared/Catch#314]
Hi I upgraded today from 1.0b43 to 1.0b53.

I get a compile error on older compilers, e.g. GCC 4.4 on CentOS 5.4 complaining about the unknown CPP directive "#pragma directive".

Could you please add the code
`#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)`
when using these CPP directives. This resolves the issue at least for GCC 4.4.

Best regards
Sebastian

**Comment by horenmar** [comment]
IIRC this has been since fixed, so I am going to close this unless someone still has the problem.
