### ISSUE TITLE
Catch is susceptible to VC12 bug: do-while loop within range-based-for fails to compile.

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#315]
Compiling:

``` C++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE( "Syntax error with VC12", "" )
{
    for ( auto x : { 1 , 2, 3 } )
        REQUIRE( x < 3.14 );
}
```

yields:

```
range-for-catch.cpp(7) : error C2059: syntax error : '}'
```

This VC12 behaviour is reported as [do-while loop within range-based-for fails to compile](https://connect.microsoft.com/VisualStudio/feedbackdetail/view/955887).

See also [Range-for, with try/catch statement, not compiling](https://connect.microsoft.com/VisualStudio/feedbackdetail/view/874705).

Workaround for users of Catch:

``` C++
TEST_CASE( "Enclose in block to compile with VC12", "" )
{
    for ( auto x : { 1 , 2, 3 } )
    {
        REQUIRE( x < 3.14 );
    }
}
```

With Catch `REQUIRE` expanded and simplified this boils down to:

``` C++
void fail()
{
    for ( auto x: { 1, 2, 3 } )
        do
        {
            try { }
            catch( std::exception const & ) {} 
        }
        while ( false );
}
```

Workaround is to enclose `do {} while();` in block:

``` C++
void pass()
{
    for ( auto x: { 1, 2, 3 } )
    {
        do
        {
            try { }
            catch( std::exception const & ) {} 
        }
        while ( false );
    }
}
```

This changes `REQUIRE()` from an iteration statement into a compound statement. What consequences may this have, if any?

**Comment by Trass3r** [comment]
Should be closed then.

**Comment by martinmoene** [comment]
mmm, 
- will not fix, and
- useful information for some users of Catch

When closing the issue, the information moves out of sight; what to do?

**Comment by horenmar** [comment]
I am going to add this into documentation, instead of keeping the issue open.

**Comment by philsquared** [comment]
I imagine the number of people affected by this at this point is significantly fewer (VS2012 wasn't one of those notorious versions that people got stuck on, as a rule).
