### ISSUE TITLE
No way to run an individual section

### ISSUE THREAD

**Issue by wichert** [philsquared/Catch#327]
When debugging I often want to run a specific test method only. This is currently not possible, so as a workaround I find myself often copying a test method to a new temporary test case. That works, but isn't very pleasant.

An option to allow tagging of test methods (and suites if #320 is implemented) in combination with a new option to the test runner to filter methods (`-m <filter>` perhaps?) would be much appreciated.

**Comment by vadz** [comment]
It would indeed be very useful to be able to use `"Tokenizer/Constructors/Copy constructor"` on command line, i.e. select the section to run by name.

**Comment by vpicaver** [comment]
A fix to this issue would be very nice. Some of my test cases take a long time to run, and it would be useful to run a particular section in a test case.

**Comment by philsquared** [comment]
@vpicaver - you might be better off splitting longer runner tests (which are presumably not unit tests) into separate `TEST_CASE`s, or possibly `TEST_CASE_METHOD`s (which are more "traditional" x-unit style fixtures).

**Comment by vpicaver** [comment]
The SECTION helps me set up the problem and re-use code. I'll have to look into TEST_CASE_METHOD

**Comment by philsquared** [comment]
Yeah, that's what `SECTION`s are for and I would usually recommend them - but given your usage and current constraints `TEST_CASE_METHOD` may be better suited (you can create a class that use as a fixture that holds the common state and setup code - just like traditional x-unit test runners).

**Comment by vpicaver** [comment]
Okay cool, makes sense. Catch has saved me a bunch time, btw.

**Comment by horenmar** [comment]
This is actually in master now, albeit a bit limited, so I am going to close this.

**Comment by onqtam** [comment]
Since I'm working on the same issue I'd like to note that the following:

```c++
TEST_CASE( "Test" ) {
    cout << "root" << endl;
    SECTION( "sa" ) {
        cout << "sa" << endl;
        SECTION( "sb" ) {
            cout << "sb" << endl;
        }
        SECTION( "sc" ) {
            cout << "sc" << endl;
        }
    }
    SECTION( "sd" ) {
        cout << "sd" << endl;
    }
}
```

when ran like this: ```a -c sa -c sb``` will output the following:

```
root
sa
sb
root
sa
root
```

So it enters the test case 3 times - when in reality it should only once.

**Comment by philsquared** [comment]
Hi @onqtam, 
Have you implemented `-c` in doctest too, then?
The reason for this behaviour is that all `-c` is doing is acting as a filter. It's still attempting to discover all the sections leading up to the first "miss". It could be changed to realise when it has executed all (usually the only) leaf sections within the filter and stop looking for me. Perhaps it should do that - thanks for the observation.

**Comment by onqtam** [comment]
@philsquared just did - in the dev branch, but mine is a bit different - see the associated [issue](https://github.com/onqtam/doctest/issues/57)

Anyway I first noticed the behavior I reported here while implementing the filtering in doctest - then I moved the filtering up a bit inside of my Subcase constructor (analogous to Section in Catch) and I no longer re-enter the test case if all other subcases that were not traversed didn't match the filtering criteria
