### ISSUE TITLE
Infinite loop on REQUIRE when MSVC builds without EHsc enabled

### ISSUE THREAD

**Issue by inequity** [philsquared/Catch#338]
Using REQUIRE at all for me seems to always cause an infinite loop. I am compiling with MSVC 2010 (version 16.00). Compiling with exception handling enabled fixes this. Maybe this isn't a bug, but if so, you guys should specify somewhere that exception handling is **required**. (It is not apparent in the tutorial that this library is using exceptions at all). 

It would appear that the config might allow a way to skip throwing (`virtual bool allowThrows() const        { return !m_data.noThrow; }`), but alas this is also not documented anywhere. 

I work in video games, and games tend to avoid exception handling at all costs. Enabling it for our tests projects isn't a huge deal, but the ideal situation would be tests who's compile flags match that of our real-world code.

This code repros it for me:

```
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.h"

TEST_CASE("Reproducing infinite loop", "")
{
    int a = 1;
    REQUIRE(a == 2);

    a = 2;
    CHECK(a == 2);
}
```

**Comment by horenmar** [comment]
Compiling without exceptions is not planned to be supported within Catch in the conceivable future.
