### ISSUE TITLE
Display unrecognised types with typeid(o).name() instead of {?} ?

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#347]
Catch currently reports types it doesn't know how to report as `"{?}"` (in StringMakerBase).

[xUnit++](https://bitbucket.org/moswald/xunit/wiki/Home) reports  these cases using `typeid(T).name()`, limited in length.

In [lest](https://github.com/martinmoene/lest), instead of reporting "{?}" I now do: `return std::string("[type: ") + typeid(obj).name() + "]";`

Would something similar be useful for Catch too?

---

Example:

``` C++
struct MyType { bool operator==(MyType const &) const { return false; } };

TEST_CASE( "Error involving MyType", "[fail]" ) {
    MyType a, b;
    REQUIRE( a == b );
}
```

MSVC:

```
unknown-type.cpp(15): failed: Error involving MyType: a == b for [type: struct MyType] == [type: struct MyType]
```

GNUC:

```
unknown-type.cpp:15: failed: Error involving MyType: a == b for [type: 6MyType] == [type: 6MyType]
```

**Comment by horenmar** [comment]
This is a bit old, but unlikely to be implemented in Catch Classic, as we try to support compiling without RTTI (don't look at me, I think its stupid).
