### ISSUE TITLE
infinite loop with latest libstd++

### ISSUE THREAD

**Issue by kirkshoop** [philsquared/Catch#352]
This bug causes `std::uncaught_exception()` to always return `true` once a `std::exception_ptr` has been passed to  `std::rethrow_exception()`
[Bug 62258 - uncaught_exception() equals to `true' after rethrow_exception()](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=62258)

The issue is that this [line](https://github.com/philsquared/Catch/blob/785db43bb2cd64bfe795ba1c6adef8b82b85430d/include/internal/catch_runner_impl.hpp#L180) in `Catch` causes an early return from the destructor even when no exception is in flight.

While pathological, it would be nice if `Catch` defended against infinite loops. `std::terminate()` would be fine with me.

**Comment by joto** [comment]
Is this the same as #271?

**Comment by philsquared** [comment]
For anyone still watching this issue - I've committed some changes (on Develop) that may address it. Please let me know either way if you try it.
