### ISSUE TITLE
Generators working yet?

### ISSUE THREAD

**Issue by ibell** [philsquared/Catch#362]
I find myself very often using an anti-pattern like the below code to iterate over a set of inputs that should or should not throw exceptions.  It's cludgy, not the least since you have to both update the number of inputs and add the inputs to the list.  

If I could use C++11, it would be slightly less painful since I could just initialize a std::vectorstd::string directly, but I need to support MSVC2008 for use with python 2.7, so no C++11.  

There was talk before about generators, has that progressed to a working state?

``` C++
#if defined(ENABLE_CATCH)
TEST_CASE("Check inputs to get_global_param_string","[get_global_param_string]")
{
    const int num_good_inputs = 8;
    std::string good_inputs[num_good_inputs] = {"version", "gitrevision", "fluids_list", "incompressible_list_pure", "incompressible_list_solution", "mixture_binary_pairs_list","parameter_list","predefined_mixtures"};
    std::ostringstream ss3c;
    for (int i = 0; i<num_good_inputs; ++i){
        ss3c << "Test for" << good_inputs[i];
        SECTION(ss3c.str(), ""){          
            CHECK_NOTHROW(CoolProp::get_global_param_string(good_inputs[i]));  
        };
    }
    CHECK_THROWS(CoolProp::get_global_param_string(""));
};
#endif
```

**Comment by bcachet** [comment]
Hello

Is there any news about **generators** ?

I tend to have the same approach but actually it's not working.
Generator will be the best solution for this purpose.

**Comment by horenmar** [comment]
The (undocumented and unfinished) generators in Catch 1 (the current version) are considered deprecated. They are coming back in Catch 2 (rewrite dropping compatibility with C++98), but until then, there is no support for them.
