### ISSUE TITLE
Catch disables some warnings in non-Catch code

### ISSUE THREAD

**Issue by ebiggers** [philsquared/Catch#365]
Hi,

I experienced a problem where neither gcc nor clang was warning about unused variables in Catch tests.  This turned out to be because catch.hpp is suppressing -Wunused-variable in all files in which it is included.

I attempted to fix the issue by moving the -Wunused-variable pragma down below "pragma diagnostic push", but this caused a warning to appear whenever a test SECTION was used.

I am wondering if the -Wunused-variable issue should be fixed by leaving the warning enabled and instead suppressing individual unused variables using **attribute**((unused)).

Eric

**Comment by philsquared** [comment]
Apologies - I think that commit referenced this issue incorrectly.
BTW - as for the actual issue you raised - I am looking into a solution.

**Comment by horenmar** [comment]
We definitely do not silence `-Wunused-variable` outside of Catch anymore, recently we had to make some changes to prevent user code from triggering these actually.

If there are still some supressions that leak, please open a new issue.
