### ISSUE TITLE
Treatment of LHS expressions

### ISSUE THREAD

**Issue by ezander** [philsquared/Catch#367]
Hi Phil!

first of all: great work! It's really fun writing unit tests with Catch. I have one issue, though. 
When I try to compile code like the following MWE

```
#include "catch.hpp"
class Foo {
  friend Foo operator+(Foo f1, Foo f2) { return f1; }
  friend bool operator==(Foo f1, Foo f2) { return true; }
};

TEST_CASE( "Testing Foo", "[foo]" ) {
  Foo f, g, h;
  REQUIRE( h==f+g ); // compiles
  REQUIRE( (f+g)==h ); // also 
  REQUIRE( f+g==h ); // doesn't compile
}
```

I get an error message from the compiler in the third REQUIRE mentioning something about Expression_Too_Complex_Please_Rewrite_As_Binary_Comparison. This is slightly confusing, because the expressions in the first and second REQUIRE are just as complex. After digging into the catch include files I found the following in "catch_expression_lhs.hpp":

```
// Only simple binary expressions are allowed on the LHS.
// If more complex compositions are required then place the sub expression in parentheses
template<typename RhsT> STATIC_ASSERT_Expression_Too_Complex_Please_Rewrite_As_Binary_Comparison& operator + ( RhsT const& );
```

Reading this the error suddenly makes a lot more sense. Maybe the error could be renamed to something that is in more accord with the comment preceding it? Something like "STATIC_ASSERT_LHS_expression_too_complex_Please_put_in_parenthesis_or_move_to_RHS"?

**Comment by philsquared** [comment]
Great suggestion - makes a lot of sense - thanks.
I'll try and get around to doing this soon - although I'm in the middle of another big project for a while so it may not be straight away.

**Comment by Trass3r** [comment]
Also ran into this :+1:

**Comment by tclamb** [comment]
As of 8cc1108f2b8aa215c94f1d6d3b93121d28ffd08a, this is no longer an issue. `REQUIRE(f + g == h);` is now a valid test.

**Comment by horenmar** [comment]
This kind of complex expression is now supported (including things like `1 + 2 / 2 + 3 / 2 == 5 / 2 + 1`), so I am going to close this.
