### ISSUE TITLE
opening /* missing from catch.hpp single inculde (development)

### ISSUE THREAD

**Issue by ryanhaining** [philsquared/Catch#370]
I don't know if this was human-error or something wrong in the auto generation, but a single line `/*` is missing from the single include in the development branch around a comment

https://github.com/philsquared/Catch/blob/develop/single_include/catch.hpp#L1231

**Comment by philsquared** [comment]
It's a generation issue (in the script that splices the headers together). I'll look into it properly at some stage but for now I've just changed the comment type to workaround the issue. The latest commit should be working again.
Sorry I didn't fix this sooner - I'm just going back over issues after a period away from the project. Someone else had reported this issue more recently too.
