### ISSUE TITLE
Successful tests don't return expected messages

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#373]
I'm currently implementing BDD with Catch and when I run my tests I expect to see messages like the ones at the bottom of [this](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md) page but instead I just get this:

```
$ ./ShogunTests 
===============================================================================
All tests passed (4 assertions in 2 test cases)
```

**Comment by jbrwilkinson** [comment]
Did you try running with --success ?

**Comment by ruipacheco** [comment]
Perfect.
