### ISSUE TITLE
Assertion m_sectionStack.empty() failed in develop branch

### ISSUE THREAD

**Issue by obfuscated** [philsquared/Catch#377]
I'm testing the signal handling in the develop branch and I'm seeing this assertion, when there is a segmentation fault:

```
a.out is a Catch v1.1 b13 (develop) host application.
Run with -? for options

myCrash
  test1
mycatch.cpp:7

mycatch.cpp:8: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

a.out: /some_path/catch/include/internal/../reporters/catch_reporter_bases.hpp:47: virtual void Catch::StreamingReporterBase::testCaseEnded(const Catch::TestCaseStats&): Assertion `m_sectionStack.empty()' failed.
```

Here is the code sample that produces the assert:

``` c++
#define CATCH_CONFIG_RUNNER
#include <catch.hpp>

const char* myFunc() { return NULL; }

TEST_CASE("myCrash") {
    SECTION("test1") {
        REQUIRE(myFunc()==std::string("test"));
    }
}

int main(int argc, char* argv[]) {
    return Catch::Session().run(argc, argv);
}
```

Tested on CentOS 6.x, GCC 4.4.x

**Comment by philsquared** [comment]
That's a little bit nasty. The assertion makes logical sense. However in the event of a segfault we get thrown onto a path where the former stack has been abandoned - and section tracking is performed by a stack-based RAII object!
There's some hacky code that kicks in to try and get things into a consistent enough state to report the error before terminating - but that assertion was kicking in at the end of it.
I tried adding more compensatory code in but it was making it even muddier so I've opted to just remove that assertion now. It's not a big deal anyway.

**Comment by philsquared** [comment]
I'm presuming no-one has seen this issue resurface and I can close the ticket?

**Comment by obfuscated** [comment]
Yep, seems to work correctly now.

**Comment by philsquared** [comment]
Thanks for confirming
