### ISSUE TITLE
REQUIRE and templates with multiple parameters

### ISSUE THREAD

**Issue by hynner** [philsquared/Catch#379]
REQUIRE macro doesn't work when template with multiple arguments is used inside of it.

For example:
```
REQUIRE(array<int,5>().size() == 5);
```
Gives me the following error on GCC 4.9.1:
```
error: macro "REQUIRE" passed 2 arguments, but takes just 1
    REQUIRE(array<int,5>().size() == 5);
In function ‘void ____C_A_T_C_H____T_E_S_T____10()’:
error: ‘REQUIRE’ was not declared in this scope
    REQUIRE(array<int,5>().size() == 5);
```

It works fine when only one parameter is used, like this:
```
REQUIRE(vector<int>().size() == 0);
```
It also works when the I explicitly cast the result to bool, like this:
```
REQUIRE(bool(array<int,5>().size() == 5));
```

**Comment by kirbyfan64** [comment]
I encountered this same issue. You [have to use parenthesis](https://github.com/philsquared/Catch/issues/340#issuecomment-58617039):

```c++
REQUIRE((array<int,5>().size()) == 5);
```

This is just because REQUIRE is defined to take one argument. The C preprocessor is blind to template arguments, so it treats your call as:

```c++
REQUIRE((array<int),(5>().size()) == 5);
```

**Comment by hynner** [comment]
Ok thanks, I didn't know that. Closing the issue.
