### ISSUE TITLE
catch.hpp(3377) generates warning C4242: '=' : conversion from 'int' to 'char', possible loss of data

### ISSUE THREAD

**Issue by socantre** [philsquared/Catch#389]
```
std::transform( sourceLC.begin(), sourceLC.end(), sourceLC.begin(), ::tolower );
```

**Comment by kirbyfan64** [comment]
IMO, I'd just use a pragma to get around this, because it's perfectly valid.

**Comment by socantre** [comment]
yeah, `#pragma warning(supress:4242)` on the line immediately before the warning would make it go away.

**Comment by horenmar** [comment]
This has been fixed since.
