### ISSUE TITLE
msvc /analyze warning "C6001: Using uninitialized memory" in user test cases

### ISSUE THREAD

**Issue by socantre** [philsquared/Catch#391]
I'm getting a warning from msvc /analyze about using uninitialized memory in a testcase simplified from my real project:

```
TEST_CASE("test1") {
  int *x = nullptr;
  REQUIRE(x==nullptr);
  SECTION("section") {
  }
}
```

I'm not certain what exactly the warning is claiming is uninitialized, but it seems to be one of the internal variables created by the catch macros. It may also be a false positive.

I've produced a self contained cmake project that reproduces the warning:

https://github.com/socantre/catch-repro

This example suppresses warnings in the catch.hpp header itself, but this warning is positioned in user code rather than in the header. Ideally the catch.hpp header can do something to prevent this warning without shutting it off in user code completely, but that may not be possible if this is just a false positive.

**Comment by kirbyfan64** [comment]
This *looks* like it should be correct. Looking at the preprocessed file, the variable is never used uninitialized. In fact, it's never used at all.

**Comment by horenmar** [comment]
I tested this against current master and didn't get the warning, so I am going to mark this as resolved, unless someone can repro it.
