### ISSUE TITLE
Error with REQUIRE(ptr == nullptr)

### ISSUE THREAD

**Issue by mjscosta** [philsquared/Catch#402]
ubuntu trusty
ii  catch                                  1.0+m10git1e2f1d16-1                  amd64        C++ Automated Test Cases in Headers

	REQUIRE(opt1 != nullptr);
Is producing the following error:
/usr/include/catch.hpp:683:49: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘std::nullptr_t’)
         enum { value = sizeof( testStreamable(s << t) ) == sizeof( TrueType ) };

**Comment by jbrwilkinson** [comment]
Please also try {{REQUIRE_FALSE(opt1 == nullptr);}}

**Comment by mjscosta** [comment]
Hi, downloaded the latest catch.hpp, and installed it in the development environment, and its fine!!

The ubuntu package is a bit outdated ...

Thanks for the suggestion!

Regards,
Mario

**Comment by PureAbstract** [comment]
@mjscosta Can you close this issue now? Thx
