### ISSUE TITLE
String conversions does not work

### ISSUE THREAD

**Issue by paolobolzoni** [philsquared/Catch#405]
Here is a self contained example:

```
struct S { int a; };
bool operator==(S const& lhs, S const& rhs) {
    return lhs.a == rhs.a; }

#include <string>

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

namespace Catch {
std::string toString( S const& value ) {
    return std::to_string(value.a) + " inside S"; } }

TEST_CASE( "new type", "[type]" ) {
    S t1;
    t1.a = 1;

    S t2;
    t2.a = 2;

    REQUIRE(t1 == t2); }
```

The output contains:
```
nt.cpp:25: FAILED:
  REQUIRE( t1 == t2 )
with expansion:
  {?} == {?}
```

It does not use the human friendly representation, bug or I am missing something?

**Comment by PureAbstract** [comment]
There are (at least) two workarounds for this:

Option 1: move your declaration of `Catch::toString( S const& )` *before* including catch.hpp.
Option 2: provide a specialisation of `Catch::StringMaker<S>` *after* including catch.hpp

I have a (mild) personal preference for the latter, but YMMV.

**Comment by paolobolzoni** [comment]
Thanks, to specialize `Catch::StringMaker` works fine and I like it more than the alternative as I can easily continue to compile catch separately.
It is strange it is not documented. However, to whomever will read this page, this is the code working:

```
struct S { int a; };
bool operator==(S const& lhs, S const& rhs) {
    return lhs.a == rhs.a; }

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <string>

namespace Catch {
template<> struct StringMaker<S> {
    static std::string convert(S const& s) {
        return std::to_string(s.a) + " (inside an S)"; } }; }

TEST_CASE( "new type", "[type]" ) {
    S t1;
    t1.a = 1;

    S t2;
    t2.a = 2;

    REQUIRE(t1 == t2); }
```

**Comment by philsquared** [comment]
Odd. I thought I had documented it a while back when I added toString.md but it wasn't there.
So I've added it now: https://github.com/philsquared/Catch/blob/master/docs/tostring.md

Thanks for bringing it up.
