### ISSUE TITLE
Inconsistent use of decimal vs hex in comparison failure messages

### ISSUE THREAD

**Issue by vadz** [philsquared/Catch#409]
`toString()` currently prints out the value in hex if it's greater than 8000 which is relatively strange on its own (why 8000?), but especially so when comparing two values, here is a message I'm getting:

```
soci/tests/odbc/test-odbc-mssql.cpp:51: FAILED:
  CHECK( str2.length() == str.length() )
with expansion:
  8000 == 0x26a2
```

It is correct, of course, (`0x26a2 == 9890 != 8000`), but does look weird. It would be nice to impose the same base for all numbers appearing in the same message.

**Comment by DarrenCook** [comment]
+1  This is driving me crazy. E.g. Is 0x1cc7c greater or less than 117891? (If you know without using a calculator, you are too clever to need a unit testing library ;-)

Strangely, I cannot find the 8000 magic number (nor 8001) in the catch.hpp file. I wonder where it is coming from!

**Comment by martinmoene** [comment]
It's `8192` naturally ;)

CATCH v1.1 build 1 (master branch), lines 7274, 7283:
```
std::string toString( int value ) {
    std::ostringstream oss;
    if( value > 8192 )
        oss << "0x" << std::hex << value;
    else
        oss << value;
    return oss.str();
}

std::string toString( unsigned long value ) {
    std::ostringstream oss;
    if( value > 8192 )
        oss << "0x" << std::hex << value;
    else
        oss << value;
    return oss.str();
}
```

**Comment by philsquared** [comment]
I don't remember why I chose 8192 specifically but the general idea was that for "small" numbers it's generally easier to reason about them in decimal whereas very large numbers hex is often more convenient. There are substantial excepts either way, of course - but the issue here is the inconsistency!
I'm not sure why you're getting one side printed one way and the other side the other way (as they should both be the same type). I'll look into it.

**Comment by vadz** [comment]
@philsquared the explanation seems pretty clear: numbers are printed in different bases because they fall on different sides of 8192 (they were 8000 and 9890). And yes, the issue is inconsistency. I didn't see any really simple way to force all numbers inside the same expression to use the same base, so personally I'd just always print them in decimal to fix this and perhaps add some way to explicitly request hex in the future (as it can also be useful for small numbers, e.g. bitmasks).

**Comment by The-Compiler** [comment]
Why not just print both? I think this is still clear enough and then the user can decide what to look at:

```
...
with expansion:
  8000 (0x1f40) == 9890 (0x26a2)
```

**Comment by vadz** [comment]
This is an interesting idea but I think it's going to result in too much noise when comparing small numbers, e.g. imagine seeing `1 (0x1) == 2 (0x2)`. So I'd rather only do it for "big" numbers, but this runs into the same problem as the original approach: if we keep the threshold at 8192, we could end up with `8000 == 9890 (0x26a2)`, i.e. without hex representation of the former number...

**Comment by The-Compiler** [comment]
Maybe just set the limit to >= 10? I think `10 (0xA) == 20 (0x14)` would be okay, and the inconsistency with `10 (0xA) == 2` doesn't matter that much, as 2 is the same in base-10 and base-16 anyways.

**Comment by philsquared** [comment]
Ahh, I missed the point about the values being different. That makes sense.

Interesting idea to print both. That's certainly quite doable. I do prefer zero-config options where possible.
I'm not 100% sure, yet. As @vadz says it might result in a little too much noise.
But I don't see any harm in trying it out for a while. The current way is clearly not working out.

**Comment by kirbyfan64** [comment]
Why not use a mix? If the number is greater than 8000 (or some other constant), then print the decimal version *and* the hex version. That way, you don't get too much visual noise for small numbers.

**Comment by vadz** [comment]
See my last comment before this one: if you use a mix, you're back to inconsistent output, i.e. the original problem.

**Comment by philsquared** [comment]
ah but if you *always* print the decimal value, but only print the hex, parenthetically, above a threshold (I'm leaning towards 255) then, while there is still scope for inconsistency you will still visually see the decimal values on both sides.
The worst part of the original problem is solved, at least.

**Comment by kirbyfan64** [comment]
What if both sides are printing in decimal and hex if one side is greater than the constant? It fixes the consistency issue.

**Comment by philsquared** [comment]
that would be nice - but not really feasible (the ints are converted to strings independently - the string conversation function has no knowledge of the context in which it is being evaluated). Changing that would complicate things considerably

**Comment by philsquared** [comment]
I've committed this (prints dec *and* hex if > 255) now as part of build 3. We'll see how it sits for a while.
Let me know how you get on with it (and thanks for all the suggestions).

**Comment by horenmar** [comment]
The current output is significantly saner, but I think some discussion about the exact details can be had in #770 .
