### ISSUE TITLE
clang 3.4 error

### ISSUE THREAD

**Issue by VadimGit** [philsquared/Catch#414]
After updating to 1.1 clang 3.4 doesn't  compile test_runner:

https://travis-ci.org/VadimGit/CatchCmake

in the same time gcc works fine.

**Comment by kirbyfan64** [comment]
Try including `type_traits` before including `catch.hpp`.

**Comment by PureAbstract** [comment]
`catch.hpp` should already be including `type_traits`.

Is that travis script installing the correct version of `libc++` for the clang build? (I forget the exact details, but I recall a while back that travis was using and old version of `libstdc++` instead)

**Comment by VadimGit** [comment]
Sorry my bad. Just now tried on debian testing with clang 3.5 and everything works fine. Something wrong with travis script.

**Comment by philsquared** [comment]
So is there a Catch issue here or not?

**Comment by PureAbstract** [comment]
@philsquared - No; it's actually a (long-standing) problem with travis

**Comment by VadimGit** [comment]
No.  It's a travis problem. Issue should be closed.
