### ISSUE TITLE
Add support for breaking into gdb

### ISSUE THREAD

**Issue by lorenzhs** [philsquared/Catch#418]
Breaking into gdb is easy (just raise SIGTRAP), but I'm not sure how best to detect whether gdb is running.

I modified Catch in my fork to break into gdb without checking: https://github.com/lorenzhs/Catch/commit/43d8eb1cab5703778d31a8ebaf8814e6e6153c04 -- that's good enough for me (why bother with running the tests with `--break` unless you want it to break?), but since you check for debugger presence, it probably isn't for you.

**Comment by The-Compiler** [comment]
There are some solutions to detect gdb [here](http://stackoverflow.com/questions/3596781/detect-if-gdb-is-running) but most of them seem rather complicated and/or costly.

FWIW, I'd prefer breaking unconditionally to no breaking at all. If an user runs with `--break` with no gdb attached, just blame them ;)

**Comment by lorenzhs** [comment]
http://stackoverflow.com/a/8135517 seems quite okay? It looks reliable (setting up a SIGTRAP handler if the debugger hasn't already done so) and then raising SIGTRAP. In case you want to repeatedly drop into the debugger, it seems like it should look like this though:

```c++
static int _debugger_present = -1;
static void _sigtrap_handler(int signum)
{
    _debugger_present = 0;
    signal(SIGTRAP, SIG_DFL);
}

void debug_break(void)
{
    if (-1 == _debugger_present) {
        _debugger_present = 1;
        signal(SIGTRAP, _sigtrap_handler);
        raise(SIGTRAP);
    } else if (1 == _debugger_present) {
        raise(SIGTRAP)
    }
}
```
(or am I not understanding something?)

**Comment by kirbyfan64** [comment]
IMO, the easiest/cleanest/most portable thing would be a `--raise-sigtrap` command-line argument...

**Comment by lorenzhs** [comment]
but that is SIGTRAP's explicit purpose? I don't see why we would need another argument, that would only be confusing.

In my opinion, `--break` should check for the debuggers it knows (like visual studio), and otherwise fall back to SIGTRAP for all other debuggers. As I see it, the purpose of the debugger check is not to prevent users from running it with `--break` and then wondering why it crashes. Instead, it seems to be there to ensure that it's running *in a debugger it knows how to break into*. SIGTRAP would be a good fallback mechanism.

**Comment by davidshepherd7** [comment]
Is anyone working on implementing and/or merging this? 

FWIW the implementation in lorenzhs' fork looks good to me.

**Comment by horenmar** [comment]
This should be implemented in commits b634e592dac83edddf724c2e243c674132ddfa8c, 25d017763b73e09d3e9adf7f4db9ce71992f0471, e1c4a4bd9b4507c86643ac825deb61da047f53e1

**Comment by hiiwave** [comment]
Hello, I assumed it had been implemented but I still encounter the same issue even with the latest release. 

Follow the same approach as in #586, the test reproducing this is as follows:
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("exception") { throw "nobody expects the Spanish inquisition"; }
```

By compiling and running it under gdb:
```
(gdb) r
Starting program: a.out -b

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v2.0.0-develop.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
exception
-------------------------------------------------------------------------------
tst.cpp:4
...............................................................................

tst.cpp:4: FAILED:
due to unexpected exception with message:
  nobody expects the Spanish inquisition

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

Does anyone have any idea why I cannot break into gdb here? Thanks a lot.

**Comment by hiiwave** [comment]
I created a new issue #1030 for this.
