### ISSUE TITLE
Failure building using GCC 5 on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by kartikkumar** [philsquared/Catch#424]
Hi all,

Recently, my Homebrew updated the GCC suite on my system to 5.1.0 and building with catch now triggers the following errors:

```
/usr/local/include/Catch/catch.hpp:813:17: error: 'nullptr_t' in namespace 'std' does not name a type
     inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
                 ^
/usr/local/include/Catch/catch.hpp:934:58: error: 'template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare' conflicts with a previous declaration
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                          ^
/usr/local/include/Catch/catch.hpp:928:44: note: previous declaration 'namespace Catch::Internal { }::compare'
     template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                            ^
/usr/local/include/Catch/catch.hpp:934:53: error: 'nullptr_t' is not a member of 'std'
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                     ^
/usr/local/include/Catch/catch.hpp:934:70: error: expected primary-expression before '*' token
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                      ^
/usr/local/include/Catch/catch.hpp:934:72: error: 'rhs' was not declared in this scope
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                        ^
/usr/local/include/Catch/catch.hpp:934:76: error: expression list treated as compound expression in initializer [-fpermissive]
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                            ^
/usr/local/include/Catch/catch.hpp:934:78: error: expected ';' before '{' token
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                              ^
/usr/local/include/Catch/catch.hpp:937:66: error: 'std::nullptr_t' has not been declared
     template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                                                  ^
/usr/local/include/Catch/catch.hpp:937:44: error: redefinition of 'template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)'
     template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                            ^
/usr/local/include/Catch/catch.hpp:928:44: note: 'template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)' previously declared here
     template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                            ^
In file included from test/testScarab.cpp:12:0:
/usr/local/include/Catch/catch.hpp:1184:38: error: 'std::__cxx11::string Catch::toString' redeclared as different kind of symbol
 std::string toString( std::nullptr_t );
                                      ^
/usr/local/include/Catch/catch.hpp:1181:13: note: previous declaration 'std::__cxx11::string Catch::toString(unsigned char)'
 std::string toString( unsigned char value );
             ^
/usr/local/include/Catch/catch.hpp:1184:23: error: 'nullptr_t' is not a member of 'std'
 std::string toString( std::nullptr_t );
                       ^
In file included from test/testScarab.cpp:12:0:
/usr/local/include/Catch/catch.hpp:6978:38: error: 'std::__cxx11::string Catch::toString' redeclared as different kind of symbol
 std::string toString( std::nullptr_t ) {
                                      ^
/usr/local/include/Catch/catch.hpp:6973:13: note: previous declaration 'std::__cxx11::string Catch::toString(unsigned char)'
 std::string toString( unsigned char value ) {
             ^
/usr/local/include/Catch/catch.hpp:6978:23: error: 'nullptr_t' is not a member of 'std'
 std::string toString( std::nullptr_t ) {

```

I'm building a C++ project using pre-C++-11 code. I'm assuming this has something to do with the fact that in GCC 5 C++11 has become the standard, but don't know if there is a simple fix for this.

Any help would be greatly appreciated.

**Comment by PureAbstract** [comment]
Are you using the correct version of libstdc++ for your compiler?

**Comment by kartikkumar** [comment]
I'm not sure how I can check on Mac OS, and more specifically when using GCC installed with Homebrew. When I run `gcc -v` I get the following:

```
$ /usr/local/bin/gcc-5 -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.1.0/libexec/gcc/x86_64-apple-darwin14.3.0/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14.3.0
Configured with: ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/usr/local/Cellar/gcc/5.1.0 --libdir=/usr/local/Cellar/gcc/5.1.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.1.0 --without-multilib' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --disable-multilib
Thread model: posix
gcc version 5.1.0 (Homebrew gcc 5.1.0 --without-multilib) 
```

Don't know if that helps provide any insight. If not, how would I go about checking what version of libstdc++ I'm linking against?

**Comment by kirbyfan64** [comment]
http://stackoverflow.com/questions/10354636/how-do-you-find-what-version-of-libstdc-library-is-installed-on-your-linux-mac

**Comment by kartikkumar** [comment]
Yea, I saw that SO thread, but the first couple of answers don't seem to work on my system. I tracked down the following files in `/usr/llib/`

```
libstdc++.6.0.9.dylib  
libstdc++.6.dylib      
libstdc++.dylib
```

So I'm guessing it's 6.0.9? Don't know if that means anything. Also, not sure if that's what the Homebrew GCC is linked against. There's nothing in `/usr/local/lib` so I'm assuming that those are the libraries.

**Comment by PureAbstract** [comment]
My concern is about the headers, rather than the binaries.
Can you compile the following 2-liner successfully:

```
#include <cstddef>
const std::nullptr_t p;
```

I ask, because the first error you report is:
`/usr/local/include/Catch/catch.hpp:813:17: error: 'nullptr_t' in namespace 'std' does not name a type`
Which would imply that `cstddef` is either not being included, or does not define `std::nullptr_t` as specified by the C++ standard.

**Comment by kartikkumar** [comment]
So it doesn't seem to compile but when I add the following to my `CMakeLists.txt` it works: `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`. 

So I'm wondering if since in GCC 5 I think the default is now C++11, somewhere libstdc++ is is still the old version? Perhaps this is a Homebrew configuration issue in that case, but I just want to make sure that it's not an issue with how CATCH is handling compiler versions.

**Comment by PureAbstract** [comment]
Given that you get the problem without including Catch, it's clearly not an Catch issue - it's a issue with your compiler/library setup.

**Comment by itrion** [comment]
In clang++ -stdlib=libstdc++ is the old version of the library. To compile
c++11/14 code you have to use -stdlib =libc++ maybe in gcc is the same

**Comment by PureAbstract** [comment]
> In clang++ -stdlib=libstdc++ is the old version of the library.

Not quite; it's not really about "old or new", it's about "GNU or LLVM".
`-stdlib=libstdc++` means "use libstdc++", which is the GNU implementation of the C++ standard library (http://gcc.gnu.org/libstdc++/).
`-std=libc++` means "use libc++", which is the LLVM implementation of the C++ standard library (http://libcxx.llvm.org/)

If you've installed a newer version of GNU's libstdc++, then you'll get that when you use `-stdlib=libstdc++`. If the installed version of libstdc++ is old, then that's what you'll get.

> To compile c++11/14 code you have to use -stdlib =libc++ maybe in gcc is the same

I've never used "-stdlib=libc++" to compile C++11/14 code with gcc on Linux; I just ensure that I have an appropriate version of libstdc++ installed.


Either way around, this is *not* a Catch issue, so any further discussion should probably take place in more relevant forums.

**Comment by kartikkumar** [comment]
Thanks for looking into it. I've just downgraded to GCC 4.9 for the moment. Hopefully someone will address the issue for Homebrew.

**Comment by philsquared** [comment]
Closing this since we established it was not a Catch issue
