### ISSUE TITLE
SelfTest fails

### ISSUE THREAD

**Issue by Sandman83** [philsquared/Catch#425]
Being a newcomer to this test suit I tried things around. Found, that one test of the SelfTest executable doesn't pass. 
Concerns: ToStringTuple.cpp in catch/projects/SelfTest, line 42. 
The error message is 

    CHECK( "{ { 42 }, { }, 1.2f }" == Catch::toString(value) )
    with expansion:
      "{ { 42 }, { }, 1.2f }"
      ==
      "{ { 42 }, { }, 0.0f }"

However, the last value "0.0f" changes unpredictable if I ran SelfTest more then once. For example I got values "-6468056.0f" and "-289567382291087360.0f"

**Comment by PureAbstract** [comment]
Which compiler/OS/etc are you using? (Unless I'm very much mistaken, the symptoms you describe *look* like a broken compiler)

**Comment by Sandman83** [comment]
I'm using G++ 5 on MacOs. 

    CMake says -- The CXX compiler identification is GNU 5.1.0

and

    g++-5 -v says

    g++-5 -v
    Using built-in specs.
    COLLECT_GCC=g++-5
    COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc5/5.1.0/libexec/gcc/x86_64-apple-darwin14.3.0/5.1.0/lto-wrapper
    Target: x86_64-apple-darwin14.3.0
    Configured with: ../configure --build=x86_64-apple-darwin14.3.0 --prefix=/usr/local/Cellar/gcc5/5.1.0 --libdir=/usr/local/Cellar/gcc5/5.1.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++ --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl014 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc5 5.1.0' --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
    Thread model: posix
    gcc version 5.1.0 (Homebrew gcc5 5.1.0) 

Yes, all other tests in ToStringTuple pass.

**Comment by PureAbstract** [comment]
Can you run it under a debugger, put a breakpoint at ToStringTuple.cpp line 42 and take a look at what the "value" tuple looks like?

**Comment by Sandman83** [comment]
compiled with cmake -DCMAKE_BUILD_TYPE=Debug
GDB says

... SelfTest/ToStringTuple.cpp:42
42	    CHECK( "{ { 42 }, { }, 1.2f }" == Catch::toString(value) );
(gdb) print value

    $1 = {<_Tuple_impl<0ul, std::tuple<int>, std::tuple<>, float>> = {<_Tuple_impl<1ul, std::tuple<>, float>> = {<_Tuple_impl<2ul, float>> = {<_Head_base<2ul, float, false>> = {
          _M_head_impl = 1.07801106e-38}, <No data fields>}, <_Head_base<1ul, std::tuple<>, true>> = {<tuple<>> = {<No data fields>}, <No data fields>}, <No data fields>}, <_Head_base<0ul, std::tuple<int>, false>> = {
      _M_head_impl = {<_Tuple_impl<0ul, int>> = {<_Head_base<0ul, int, false>> = {
            _M_head_impl = 42}, <No data fields>}, <No data fields>}}, <No data fields>}, <No data fields>}

**Comment by PureAbstract** [comment]
The problem appears to be here:
```_M_head_impl = 1.07801106e-38```

For whatever reason, your compiler appears not to be initialising the tuple correctly.

Line 41 reads:
```type value { std::tuple<int>{42}, {}, 1.2f };```

Which should initialise the float member to 1.2 - not 1.07...e-38.

It's true that a `tuple` containing an empty `tuple` is an unlikely edge-case, but that's why it's a test here...

I've just tried a simple example on godbolt (https://goo.gl/pZ8MV1) - which does the right thing on 4.8, 4.9 but fails on 5.1 - I think this is a compiler regression.

**Comment by Sandman83** [comment]
Oh, wow... So, you found a compiler bug... Do you report this to... to whom, actually? )) 
Apart from this, I think you (or I?) can close the ticket now. As the case is an edge-case, I think I can live with this, knowing which case should not occur. 
Thanks for your time!

**Comment by kirbyfan64** [comment]
I'd say to report it to GCC.
