### ISSUE TITLE
Floating Point Macros

### ISSUE THREAD

**Issue by rhl-** [philsquared/Catch#426]
Hi,

This is a feature request for these macros: https://code.google.com/p/googletest/wiki/AdvancedGuide#Floating-Point_Macros

if they do not already exist and I am not aware of them :)

**Comment by The-Compiler** [comment]
There's a section on [floating point comparisons](https://github.com/philsquared/Catch/blob/master/docs/assertions.md#floating-point-comparisons) in the documentation.

**Comment by philsquared** [comment]
Thanks @The-Compiler.
@rhl- - does that answer your question?

**Comment by rhl-** [comment]
Yes
