### ISSUE TITLE
Using type_traits inside of a REQUIRE statement

### ISSUE THREAD

**Issue by luxe** [philsquared/Catch#431]
Shouldn't it be possible to use a type trait inside of a REQUIRE statement?    
       
        //works
        bool constructible = std::is_constructible<Vertex, std::string, int>::value;
    	REQUIRE( constructible == true );

---

        //error:
    	REQUIRE( std::is_constructible<Vertex, std::string, int>::value == true );

---

      error: macro "REQUIRE" passed 3 arguments, but takes just 1
      REQUIRE( std::is_constructible<Vertex, std::string, int>::value == true );
                                                                              ^
       In function ‘void ____C_A_T_C_H____T_E_S_T____6()’:
       error: ‘REQUIRE’ was not declared in this scope
           REQUIRE( std::is_constructible<Vertex, std::string, int>::value == true );
            ^

**Comment by martinmoene** [comment]
As REQUIRE() is a macro, non-argument-separating commas have to be 'hidden'. You can do this by placing the part with the non-argument-separating commas inside parenthesis, e.g.:
```
REQUIRE( ( std::is_constructible<Vertex, std::string, int>::value ) == true );
```
You'll give in on expressiveness of the error message, so make sure the message is clear by the name of the test, or as in your "works" fragment from the variable name (`vertex_is_constructible `?).

**Comment by kirbyfan64** [comment]
```c++
REQUIRE( (std::is_constructible<Vertex, std::string, int>::value) == true );
```

**Comment by philsquared** [comment]
Putting the sub-expression containing commas in parentheses is correct, as @martinmoene and @kirbyfan64 propose.
However I disagree that it impacts the "expressive of the error message" in this case. I think you're thinking of when the entire expression (including the `== true`) goes in parentheses, Martin?

Either way does this address your concern, @luxe?

**Comment by martinmoene** [comment]
@philsquared mmm perhaps I was not thinking...  and now also to me it seems the error message would be just fine.

**Comment by luxe** [comment]
If the left or right side of the expression contains commas, I need to wrap them in parentheses.  Or I can wrap the entire expression in parentheses.  This is because macros parse and split by comma.  That makes sense.  Thanks.
