### ISSUE TITLE
Use C++11 override keyword

### ISSUE THREAD

**Issue by prapin** [philsquared/Catch#441]
C++11 introduced the keyword-like `override` and `final` terms for `virtual` functions to specify when a function is overridden.
CATCH has quite a lot of `virtual` functions and can benefit to use this new feature.

Pros:
- Safety. A method declared `override` with a different signature than a base class `virtual` method will not compile. This is a good protection against typos and when changing the method signature during refactoring.
- Documentation. It is a good for the programmer and the reviewers to quickly distinguish between first declared `virtual` functions and overriden ones.

Cons:
- Only for C++11. But for older C++98 compilers, `#define override` to nothing can be used to compile anyway.

See my commit:
https://github.com/prapin/Catch/commit/94a5b621c806be93a88a418ec1dfe7e6c9cc5221

**Comment by rollbear** [comment]
override and final aren't keywords in C++11/14, they're context sensitive. You're allowed to have variables, parameters, types, functions named "override", so hiding them with the preprocessor is not likely to work.

It would, of course, be possible to add a CATCH_OVERRIDE macro, that expands to nothing in C++98/03 and to override in C++11/14.

Not that I think there'd be much gain. As a Catch user, you don't see the implementation of Catch so its internals are of no concern. It could help developers of Catch a bit, though.

**Comment by philsquared** [comment]
I've been using the `<PREFIX>_OVERRIDE` approach in my day-job code-base for a couple of years (slightly different: it uses the pre-C++11 VC++ extension to do that same thing - but also suppresses the warning about it at the same time).
I might consider this, although as @rollbear says its not a huge gain - but it does risk breaking on compilers I don't test on.

**Comment by philsquared** [comment]
FYI I've started doing this now. I've not rolled it out to all virtual overrides, but will increase coverage over time (and I've realised there's a lot more virtual than I'd thought!)

**Comment by horenmar** [comment]
I tried compiling Catch under g++ with `-Wsuggest-override`, but got no warnings, so I am going to assume that overrides are currently all present and close this.

However, there is also a good point in that the [contribution documentation](/philsquared/Catch/blob/master/docs/contributing.md) could use some notes about C++98 compatibility and conditional compilation for various compilers for PRs.
