### ISSUE TITLE
Random generator should be seeded on each unit test

### ISSUE THREAD

**Issue by prapin** [philsquared/Catch#442]
CATCH has a command line option `--rng-seed` to initialize pseudo-random generator before running unit tests, either with a fixed value or based on time.
This is good. I personally wrote quite a lot of unit tests that uses pseudo-random generator to test unsuspected corner case numerical values.

But the generator is initialized in `Session::run`, only once for all tests. It shall be initialized before *each* unit test (for example in `RunContext::runCurrentTest`).
Otherwise, the unit tests are not independent between each others. The random generator seed value at the start of a unit test depends on the number, the order and the execution path of all unit tests before it that have used the generator.

**Comment by philsquared** [comment]
Forgot to reference this issue in the commit - but I've now done this. I agree that it's exactly how it should be done.

**Comment by philsquared** [comment]
that's in the `v1.2.1-develop.2` commit.

**Comment by philsquared** [comment]
I'm going to close this issue, as I believe it is fully addressed.
Feel free to reopen if you think there is more to it.
