### ISSUE TITLE
Compiling example of catch

### ISSUE THREAD

**Issue by fekir** [philsquared/Catch#444]
Hello, 
I'm a new user of catch. I've tried to compile to example provided at this site, and I've got a bunch of compilation warning generated by gcc (version 4.8.2) using the flags: 
-Wzero-as-null-pointer-constant
-Wswitch-default
-Wctor-dtor-privacy
-Wshadow
-Wuseless-cast

I think it would be great if all the warnings could be resolved. I also think that for most of them it shouldn't be to difficult without even using conditional compilation.

For the "zero-as-null-pointer-constant", since you are aiming to provide full support also for older compilers who do not have nullptr, you could define a global constant that (through ifdefs) is conditionally assigned to nullptr or NULL.

Please let me know if you need more information!

**Comment by philsquared** [comment]
Thanks @fekir. If you could post the warnings you're seeing that would be a help.

**Comment by fekir** [comment]
I can't see how to atacch a file, so I'm posting the content, I'm sorry but it is a bit long...:


Scanning dependencies of target proj.bin
[ 25%] Building CXX object CMakeFiles/proj.bin.dir/main.cpp.o
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In static member function ‘static void (Catch::SafeBool::* Catch::SafeBool::makeSafe(bool))()const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:208:51: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             return value ? &SafeBool::trueValue : 0;
                                                   ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: At global scope:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:497:7: warning: ‘class Catch::MethodTestCase<C>’ only defines a private destructor and has no friends [-Wctor-dtor-privacy]
 class MethodTestCase : public SharedImpl<ITestCase> {
       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘virtual bool Catch::TestSpec::NamePattern::matches(const Catch::TestCaseInfo&) const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2865:23: warning: switch missing default case [-Wswitch-default]
                 switch( m_wildcard ) {
                       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘void Catch::Config::useStream(const string&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3231:20: warning: declaration of ‘stream’ shadows a member of 'this' [-Wshadow]
             Stream stream = createStream( streamName );
                    ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘Catch::Clara::CommandLine<ConfigT>::ArgBuilder& Catch::Clara::CommandLine<ConfigT>::ArgBuilder::detail(const string&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3849:61: warning: declaration of ‘detail’ shadows a member of 'this' [-Wshadow]
             ArgBuilder& detail( std::string const& detail ) {
                                                             ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘void Catch::Clara::CommandLine<ConfigT>::optUsage(std::ostream&, std::size_t, std::size_t) const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3933:37: warning: declaration of ‘usage’ shadows a member of 'this' [-Wshadow]
                 Detail::Text usage( it->commands(), Detail::TextAttributes()
                                     ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In function ‘void Catch::setRngSeed(Catch::ConfigData&, const string&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4165:68: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             config.rngSeed = static_cast<unsigned int>( std::time(0) );
                                                                    ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In constructor ‘Catch::SectionTracking::TestCaseTracker::TestCaseTracker(const string&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5009:47: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             m_completedASectionThisRun( false )
                                               ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In constructor ‘Catch::RunContext::RunContext(const Catch::Ptr<const Catch::IConfig>&, const Catch::Ptr<Catch::IStreamingReporter>&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5183:9: warning: declaration of ‘config’ shadows a member of 'this' [-Wshadow]
         :   m_runInfo( config->name() ),
         ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5190:49: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             m_prevConfig( m_context.getConfig() )
                                                 ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In destructor ‘virtual Catch::RunContext::~RunContext()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5201:39: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             m_context.setConfig( NULL );
                                       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘Catch::Totals Catch::RunContext::runTest(const Catch::TestCase&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5242:30: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             m_activeTestCase = NULL;
                              ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In static member function ‘static void Catch::TestRegistry::sortTests(const Catch::IConfig&, std::vector<Catch::TestCase>&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5789:19: warning: switch missing default case [-Wswitch-default]
             switch( config.runOrder() ) {
                   ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: At global scope:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5812:11: warning: ‘class Catch::FreeFunctionTestCase’ only defines a private destructor and has no friends [-Wctor-dtor-privacy]
     class FreeFunctionTestCase : public SharedImpl<ITestCase> {
           ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In function ‘void Catch::cleanUp()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6023:29: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         getTheRegistryHub() = NULL;
                             ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In constructor ‘Catch::Stream::Stream()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6124:41: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
     : streamBuf( NULL ), isOwned( false )
                                         ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘void Catch::Stream::release()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6134:23: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             streamBuf = NULL;
                       ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In constructor ‘Catch::Context::Context()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6153:79: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Context() : m_config( NULL ), m_runner( NULL ), m_resultCapture( NULL ) {}
                                                                               ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6153:79: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6153:79: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In function ‘void Catch::cleanUpContext()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6241:24: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         currentContext = NULL;
                        ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘virtual void Catch::{anonymous}::PosixColourImpl::use(Catch::Colour::Code)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6350:19: warning: switch missing default case [-Wswitch-default]
             switch( _colourCode ) {
                   ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In function ‘uint64_t Catch::{anonymous}::getCurrentTicks()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6946:33: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             gettimeofday(&t,NULL);
                                 ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘unsigned int Catch::Timer::getElapsedMilliseconds() const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:6959:71: warning: useless cast to type ‘unsigned int’ [-Wuseless-cast]
         return static_cast<unsigned int>(getElapsedMicroseconds()/1000);
                                                                       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In copy constructor ‘Catch::XmlWriter::ScopedElement::ScopedElement(const Catch::XmlWriter::ScopedElement&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7860:32: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
                 other.m_writer = NULL;
                                ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘void Catch::XmlWriter::writeEncodedText(const string&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8030:23: warning: switch missing default case [-Wswitch-default]
                 switch( mtext[pos] ) {
                       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘virtual bool Catch::XmlReporter::assertionEnded(const Catch::AssertionStats&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8150:19: warning: enumeration value ‘Unknown’ not handled in switch [-Wswitch-enum]
             switch( assertionResult.getResultType() ) {
                   ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8150:19: warning: enumeration value ‘Ok’ not handled in switch [-Wswitch-enum]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8150:19: warning: enumeration value ‘FailureBit’ not handled in switch [-Wswitch-enum]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8150:19: warning: enumeration value ‘ExpressionFailed’ not handled in switch [-Wswitch-enum]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8150:19: warning: enumeration value ‘Exception’ not handled in switch [-Wswitch-enum]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8150:19: warning: enumeration value ‘DidntThrowException’ not handled in switch [-Wswitch-enum]
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘void Catch::JunitReporter::writeAssertion(const Catch::AssertionStats&)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8394:23: warning: switch missing default case [-Wswitch-default]
                 switch( result.getResultType() ) {
                       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In constructor ‘Catch::ConsoleReporter::AssertionPrinter::AssertionPrinter(std::ostream&, const Catch::AssertionStats&, bool)’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8560:23: warning: switch missing default case [-Wswitch-default]
                 switch( result.getResultType() ) {
                       ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In member function ‘void Catch::CompactReporter::AssertionPrinter::print()’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:8967:23: warning: switch missing default case [-Wswitch-default]
                 switch( result.getResultType() ) {
                       ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option() [with T = long unsigned int]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4918:29:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2453:40: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Option() : nullableValue( NULL ) {}
                                        ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option(const Catch::Option<T>&) [with T = long unsigned int]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4927:16:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2458:33: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         : nullableValue( _other ? new( storage ) T( *_other ) : NULL )
                                 ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option() [with T = Catch::SectionTracking::TestCaseTracker]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5190:49:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2453:40: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Option() : nullableValue( NULL ) {}
                                        ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Option<T>::reset() [with T = Catch::SectionTracking::TestCaseTracker]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5243:37:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2482:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             nullableValue = NULL;
                           ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Ptr<T>::Ptr() [with T = Catch::IStreamingReporter]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5516:30:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:358:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Ptr() : m_p( NULL ){}
                           ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Ptr<T>::Ptr() [with T = Catch::Config]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5604:42:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:358:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Ptr<T>::reset() [with T = Catch::Config]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5634:32:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:374:17: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             m_p = NULL;
                 ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option(const Catch::Option<T>&) [with T = Catch::TagAlias]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7506:24:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2458:33: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         : nullableValue( _other ? new( storage ) T( *_other ) : NULL )
                                 ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option() [with T = Catch::TagAlias]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7508:37:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2453:40: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Option() : nullableValue( NULL ) {}
                                        ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Ptr<T>::Ptr() [with T = Catch::CumulativeReporterBase::SectionNode]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7676:38:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:358:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Ptr() : m_p( NULL ){}
                           ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Ptr<T>::reset() [with T = Catch::CumulativeReporterBase::SectionNode]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7729:33:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:374:17: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             m_p = NULL;
                 ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Clara::Detail::BoundArgFunction<ConfigT>& Catch::Clara::Detail::BoundArgFunction<ConfigT>::operator=(const Catch::Clara::Detail::BoundArgFunction<ConfigT>&) [with ConfigT = Catch::ConfigData]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3919:32:   required from ‘void Catch::Clara::CommandLine<ConfigT>::bindProcessName(M C::*) [with C = Catch::ConfigData; M = std::basic_string<char>; ConfigT = Catch::ConfigData]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4202:55:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3534:75: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
                 IArgFunction<ConfigT>* newFunctionObj = other.functionObj ? other.functionObj->clone() : NULL;
                                                                           ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Clara::Detail::BoundArgFunction<ConfigT>::BoundArgFunction(const Catch::Clara::Detail::BoundArgFunction<ConfigT>&) [with ConfigT = Catch::ConfigData]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3881:76:   required from ‘Catch::Clara::CommandLine<ConfigT>::CommandLine(const Catch::Clara::CommandLine<ConfigT>&) [with ConfigT = Catch::ConfigData]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4297:16:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3532:96: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             BoundArgFunction( BoundArgFunction const& other ) : functionObj( other.functionObj ? other.functionObj->clone() : NULL ) {}
                                                                                                ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Option<T>::reset() [with T = long unsigned int]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2462:19:   required from ‘Catch::Option<T>::~Option() [with T = long unsigned int]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4918:29:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2482:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             nullableValue = NULL;
                           ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Clara::CommandLine<ConfigT>::optUsage(std::ostream&, std::size_t, std::size_t) const [with ConfigT = Catch::ConfigData; std::ostream = std::basic_ostream<char>; std::size_t = long unsigned int]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3987:33:   required from ‘void Catch::Clara::CommandLine<ConfigT>::usage(std::ostream&, const string&) const [with ConfigT = Catch::ConfigData; std::ostream = std::basic_ostream<char>; std::string = std::basic_string<char>]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:5624:53:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3935:78: warning: declaration of ‘usage’ shadows a member of 'this' [-Wshadow]
                                                         .setIndent( indent ) );
                                                                              ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Option<T>::reset() [with T = Catch::TagAlias]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2462:19:   required from ‘Catch::Option<T>::~Option() [with T = Catch::TagAlias]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7506:24:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2482:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             nullableValue = NULL;
                           ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option() [with T = Catch::TestRunInfo]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4557:34:   required from ‘Catch::LazyStat<T>::LazyStat() [with T = Catch::TestRunInfo]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7578:38:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2453:40: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Option() : nullableValue( NULL ) {}
                                        ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Option<T>::reset() [with T = Catch::TestRunInfo]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2462:19:   required from ‘Catch::Option<T>::~Option() [with T = Catch::TestRunInfo]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4556:12:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2482:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             nullableValue = NULL;
                           ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option() [with T = Catch::GroupInfo]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4557:34:   required from ‘Catch::LazyStat<T>::LazyStat() [with T = Catch::GroupInfo]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7578:38:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2453:40: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Option() : nullableValue( NULL ) {}
                                        ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Option<T>::reset() [with T = Catch::GroupInfo]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2462:19:   required from ‘Catch::Option<T>::~Option() [with T = Catch::GroupInfo]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4556:12:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2482:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             nullableValue = NULL;
                           ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Option<T>::Option() [with T = Catch::TestCaseInfo]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4557:34:   required from ‘Catch::LazyStat<T>::LazyStat() [with T = Catch::TestCaseInfo]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:7578:38:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2453:40: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
         Option() : nullableValue( NULL ) {}
                                        ^
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘void Catch::Option<T>::reset() [with T = Catch::TestCaseInfo]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2462:19:   required from ‘Catch::Option<T>::~Option() [with T = Catch::TestCaseInfo]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4556:12:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:2482:27: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             nullableValue = NULL;
                           ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/main.cpp:2:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In instantiation of ‘Catch::Clara::Detail::BoundArgFunction<ConfigT>::BoundArgFunction() [with ConfigT = Catch::ConfigData]’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3694:31:   required from ‘Catch::Clara::CommonArgProperties<ConfigT>::CommonArgProperties() [with ConfigT = Catch::ConfigData]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3734:19:   required from ‘Catch::Clara::CommandLine<ConfigT>::Arg::Arg() [with ConfigT = Catch::ConfigData]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3893:13:   required from ‘Catch::Clara::CommandLine<ConfigT>::OptBuilder Catch::Clara::CommandLine<ConfigT>::operator[](const string&) [with ConfigT = Catch::ConfigData; std::string = std::basic_string<char>]’
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:4204:17:   required from here
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:3530:52: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             BoundArgFunction() : functionObj( NULL ) {}
                                                    ^
[ 50%] Building CXX object CMakeFiles/proj.bin.dir/test1.cpp.o
In file included from /home/fekir/Workspace/CPP/Cmake/catch/test1.cpp:1:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In static member function ‘static void (Catch::SafeBool::* Catch::SafeBool::makeSafe(bool))()const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:208:51: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             return value ? &SafeBool::trueValue : 0;
                                                   ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/test1.cpp:1:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: At global scope:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:497:7: warning: ‘class Catch::MethodTestCase<C>’ only defines a private destructor and has no friends [-Wctor-dtor-privacy]
 class MethodTestCase : public SharedImpl<ITestCase> {
       ^
[ 75%] Building CXX object CMakeFiles/proj.bin.dir/test2.cpp.o
In file included from /home/fekir/Workspace/CPP/Cmake/catch/test2.cpp:1:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In static member function ‘static void (Catch::SafeBool::* Catch::SafeBool::makeSafe(bool))()const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:208:51: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             return value ? &SafeBool::trueValue : 0;
                                                   ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/test2.cpp:1:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: At global scope:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:497:7: warning: ‘class Catch::MethodTestCase<C>’ only defines a private destructor and has no friends [-Wctor-dtor-privacy]
 class MethodTestCase : public SharedImpl<ITestCase> {
       ^
[100%] Building CXX object CMakeFiles/proj.bin.dir/test3.cpp.o
In file included from /home/fekir/Workspace/CPP/Cmake/catch/test3.cpp:1:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: In static member function ‘static void (Catch::SafeBool::* Catch::SafeBool::makeSafe(bool))()const’:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:208:51: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
             return value ? &SafeBool::trueValue : 0;
                                                   ^
In file included from /home/fekir/Workspace/CPP/Cmake/catch/test3.cpp:1:0:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp: At global scope:
/home/fekir/Workspace/CPP/Cmake/catch/catch.hpp:497:7: warning: ‘class Catch::MethodTestCase<C>’ only defines a private destructor and has no friends [-Wctor-dtor-privacy]
 class MethodTestCase : public SharedImpl<ITestCase> {
       ^
Linking CXX executable proj.bin
[100%] Built target proj.bin

**Comment by philsquared** [comment]
Thanks for that.
I've addressed some of them (in an, as yet unpushed, commit) - mostly the null pointer constant and shadowing issues. Most of the others are tricker. The enum switches are the most frustrating: Use just the cases you need + a default case and it complains the cases are no exhaustive. Add exhaustive cases and it complains there's no default. Have exhaustive cases *and* a default and it complains about unreachable code :-s I think I'm going to have to resort to disabling warnings for these.

**Comment by DavidEGrayson** [comment]
Did you try making it so that `default:` is a label for the same statement as one of the other cases?

~~~~{.cpp}
switch(something)
{
case 1: break;
case 2: break;
default:
case3: break;
}
~~~~

--David

**Comment by PureAbstract** [comment]
@DavidEGrayson I hope you realise you're suggesting *intentionally* writing fragile code to silence a warning?

**Comment by DavidEGrayson** [comment]
No, it doesn't seem fragile to me.  You would basically put all the cases you don't care about next to the `default:` label.  The line breaks should make it be clear what is going on.

~~~~{.cpp}
switch(something)
{
case 1:
  do_something_1();
  break;

case 2:
  do_something_2();
  break;

default:
case 3:
case 4:
case 5:
  break;
}
~~~~

Does it still look fragile to you?  If so, why?

**Comment by fekir** [comment]
@DavidEGrayson: Why are you not leaving the default case to the end?

Isn't 
------------------------------------------------------------------------------------------------------------------------------------
switch(something)
{
case 1:
  do_something_1();
  break;

case 2:
  do_something_2();
  break;

case 3:
case 4:
case 5:
default:
  break;
}
------------------------------------------------------------------------------------------------------------------------------------

enough to fix all the warnings?

**Comment by DavidEGrayson** [comment]
Either ordering seems fine.

**Comment by horenmar** [comment]
Using example code from [tutorial](/philsquared/Catch/blob/master/docs/tutorial.md) and `g++ -Wzero-as-null-pointer-constant -Wswitch-default -Wctor-dtor-privacy -Wshadow -Wuseless-cast -Wall -Wextra test.cpp` I am not getting these warnings anymore.
