### ISSUE TITLE
Support for TeamCity CI

### ISSUE THREAD

**Issue by izzycoding** [philsquared/Catch#452]
I am looking at implementing support in Catch for our TeamCity build system using the team city-messages functionality. Their code can be downloaded from the jet brains site.

I was wondering if this might be a good addition to the framework for use in CI build systems?

**Comment by izzycoding** [comment]
please ignore this, just found that there is already a team city build messaging component

**Comment by philsquared** [comment]
Sorry - I need to make it clearer that it is there - and how to get to it.
Unlike the other included reporters, the TeamCity reporter is not included in the single header version of Catch. You'll need to get the file, separately, from `reporters/include/catch_reporter_teamcity.hpp` and include that along side `catch.hpp` where you do `#define CATCH_CONFIG_MAIN`.

**Comment by philsquared** [comment]
oh - and `catch_reporter_teamcity.hpp` must be `#include`d after `catch.hpp`!
