### ISSUE TITLE
Access seed in test

### ISSUE THREAD

**Issue by sdressler** [philsquared/Catch#453]
I was trying to get the seed inside the tests, because they are using random number generators themselves. Usually it is not `std::rand` but `std::minstd_rand` with some specific distribution. On the other hand, the classes under test also take a seed.

I have seen, that one can grab the current context with `getCurrentContext` and then access the configuration. But I am not able to compile it due to linkage errors, e.g.

```
const uint64_t seed = Catch::getCurrentContext().getConfig()->rngSeed();
```

will lead to `multiple definition of `Catch::signalDefs'`, mostly because I had to include `catch_runner.hpp` which I think is not intended.

Maybe there already is a correct way to capture the seed inside the test, otherwise it would be a nice feature :-)

**Comment by philsquared** [comment]
as of `v1.2.1-develop.2` you can now get the seed by calling `Catch::rngSeed()`.

**Comment by sdressler** [comment]
Awesome :-)
