### ISSUE TITLE
Dynamically create argument to WHEN statement

### ISSUE THREAD

**Issue by daixtrose** [philsquared/Catch#455]
I attempted to do the following

``` c++
std::string description = /* ... create string out of the current states */ 

WHEN( description )
{
    // ...
```

but this fails due to a parse error. I could fall back to boost::preprocessor, but I kind of refrain from those adventures as often as possible. Any idea how I can proceed?

**Comment by philsquared** [comment]
What is the "parse error"? 
This *should* work (I do similar from time to time). In fact I tried your example and it worked for me.

**Comment by philsquared** [comment]
Ah - I just spotted that you are using `WHEN`. I was thinking of `SECTION`.
`WHEN` forwards onto `SECTION`, but before doing so it prepends the string, `"    When: "`. It does it like this:

  SECTION( "    When: " desc, "" )

- which assumes `desc` will be a string literal! That explains your issue.
The solution is simple (wrap the `"    When: "` in a std::string and use `operator+`).
I'll add this into to the next build.

**Comment by philsquared** [comment]
This is in, now: v1.2.1-develop.9
