### ISSUE TITLE
How to define tear down code in the TEST_CASE() SECTION() syntax?

### ISSUE THREAD

**Issue by danijar** [philsquared/Catch#459]
I want to check for an error flag after each section in the test case. Where can I specify this?

**Comment by DavidEGrayson** [comment]
Can you put it inside the TEST_CASE after all the SECTIONs?

**Comment by philsquared** [comment]
I agree with @DavidEGrayson's suggestion, based on the information given.
Does this address your need, @danijar?

**Comment by danijar** [comment]
Hi, I'm sorry but I can't try it out right now. If code provided after the last SECTION is run after each section, yes. I'll see if it works as soon as I have the time.

**Comment by danijar** [comment]
@philsquared  I just tested adding tear-down code inside the TEST_CASE after all SECTIONs. The code was ignored completely. Even throwing an exception there had no effect.

**Comment by DavidEGrayson** [comment]
It sounds like that code wasn't running.  Do you have any failing REQUIRE lines in the sections above, or anything else that is throwing an exception?  It's possible I don't know how SECTION works.

**Comment by philsquared** [comment]
@danijar If you want code to run at the end of a scope, regardless of whether an exception was thrown, you can use something like a ScopeGuard.
