### ISSUE TITLE
Exceptions all reported as "Unknown exception"

### ISSUE THREAD

**Issue by criptych** [philsquared/Catch#463]
I have a project with a few tests that (deliberately) cause exceptions, e.g. `ArgumentError`, `InternalError`, `NotImplementedError`.  These all ultimately inherit from `std::exception` and implement method `what`, but when CATCH, er, catches them, it prints "`FAILED ... due to unexpected exception with message: Unknown exception`".  When I throw plain C-style strings, it displays the message; however, I'd prefer to use "standard" exceptions.  I'm still not sure if this is an issue with the library or just something I'm doing wrong, though.

Many thanks for developing this tool, btw.  Of all the test frameworks I've used (granted, not that many) it's by far the simplest to set up and use, might even get me to use TDD/BDD on a regular basis. :)

**Comment by DavidEGrayson** [comment]
I had trouble with this myself until I realized that the exception needs to *publicly* inherit from std::exception.  Is that how your exception classes are defined?

~~~~
class foo_error : public std::exception
{
};
~~~~

**Comment by criptych** [comment]
They weren't, but doing so fixed the issue.  Thanks for the help; I couldn't find anything in the docs and trying to unravel Catch's exception handling was hurting my head.

**Comment by hpg-mheck** [comment]
I know this isn't the ideal place to ask this, but I am seeing Astounding Failure Levels trying to get ANY search engine to actually search for the exact keywords required to look this up, so I am left with little choice but to ask this here, on this closed bug.

I absolutely CANNOT get this to work.  Catch2 *refuses* to show my exception class names OR the value of "what()", no matter what I do.  I have tried many, many experiments.

Can someone point me to a REAL, WORKING EXAMPLE of this, preferably with an intermediate base class?  Everything I can find has lots of hand-waving and you-know-what-I-mean instead of full, complete, working code.

In the absence of being able to find any, OR being able to make any work, I assert that this bug is STILL OPEN, because I cannot prove otherwise.

**Comment by horenmar** [comment]
@hpg-mheck Can you provide a [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by hpg-mheck** [comment]
Aha, I see the issue now.  Catch2 can not properly translate exceptions thrown as pointers to exception objects.  (Yes, I know all the reasons that's not the ideal way to handle them in most situations, but with legacy code, we get what we get.)  The test harness passes on "throw MyException" fine, just not on "throw new MyException" (not my design).  That's close enough for me, and one more reason I can cite to overhaul the code.  Sorry, and thanks!  Maybe this exchange will be useful to someone else, in any case.

**Comment by hpg-mheck** [comment]
Oh, and in case anyone is wondering: when thrown properly, yes, I was able to overload what() in an intermediate base class and get what I expected from the derived classes.  So, error was on my end.

**Comment by chrisdembia** [comment]
I am having this issue and it is not caused by private inheritance or throwing pointers. I do not have a MWE yet, but I'm just posting in case others are still having this issue.

(by the way, Catch is great :) )

**Comment by claremacrae** [comment]
Updating for anyone who comes here via search - if you are running your Catch2 exe in CLion, you have almost certainly hit this CLion issue:
https://youtrack.jetbrains.com/issue/CPP-11919

Apparently a fix may be coming in 2020, so check for updates...

**Comment by chrisdembia** [comment]
Yay! My issue is through CLion, too.

**Comment by claremacrae** [comment]
A workaround is to not use the CLion Catch2 adapter, and instead to tell CLion to run the test program as a CMake executable - but I think that you then cannot run individual tests...

It would at least tell you want the text was of the failing exception...

**Comment by gelldur** [comment]
@claremacrae you can run but you need to pass flags for executable which is annoying. Also other annoying thing is `-r xml` which Clion add always and we can't change that to e.g. console :/

**Comment by claremacrae** [comment]
Just to note that this is fixed in the CLion 2020.2 EAP and later....
