### ISSUE TITLE
Readme: Add how-to for supplying different allocator

### ISSUE THREAD

**Issue by mtlmeijer** [philsquared/Catch#468]
There is a friendly how-to for supplying your own main in the Readme.
Can we have one for supplying our own allocator as well?

**Comment by mtlmeijer** [comment]
A compile error I get:
{code}
1>  Note: including file: D:\dev\ThirdParty\Catch\include\catch.hpp
1>  Note: including file:  d:\dev\thirdparty\catch\include\internal/catch_suppress_warnings.h
1>  Note: including file:  d:\dev\thirdparty\catch\include\internal/catch_notimplemented_exception.h
1>  Note: including file:   d:\dev\thirdparty\catch\include\internal\catch_common.h
1>  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sstream
1>  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string
1>  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\iterator
1>  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\istream
1>  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ostream
1>  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ios
1>  Note: including file:          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocnum
1>  Note: including file:           C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\climits
1>  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\yvals.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xkeycheck.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\use_ansi.h
1>  Note: including file:           C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cmath
1>  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h
1>  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtgmath.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtr1common
1>  Note: including file:           C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cstdio
1>  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\swprintf.inl
1>  Note: including file:           C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cstdlib
1>  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:           C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\streambuf
1>  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xiosbase
1>  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale
1>  Note: including file:              C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cstring
1>  Note: including file:               C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\string.h
1>  Note: including file:                C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:              C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept
1>  Note: including file:               C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\exception
1>  Note: including file:                C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xstddef
1>  Note: including file:                 C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cstddef
1>  Note: including file:                 C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\initializer_list
1>  Note: including file:                C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\eh.h
1>  Note: including file:                 C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:               C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xstring
1>  Note: including file:                C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xmemory0
1>  Note: including file:                 C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\limits
1>  Note: including file:                  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ymath.h
1>  Note: including file:                  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cfloat
1>  Note: including file:                   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\float.h
1>  Note: including file:                    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:                    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtwrn.h
1>  Note: including file:                     C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:                  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\cwchar
1>  Note: including file:                   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\wchar.h
1>  Note: including file:                    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
1>  Note: including file:                    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\wtime.inl
1>  Note: including file:                 C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\new
1>c:\program files (x86)\microsoft visual studio 12.0\vc\include\new(59): error C2084: function 'void *operator new(unsigned int,void *)' already has a body
1>          d:\dev\thirdparty\kin\pigs\pos\new.h(8) : see previous definition of 'new'
{code}

**Comment by DavidEGrayson** [comment]
If you really want to define your own version of `new`, I suppose you will have to find some way to disable Visual Studio's version.  The compiler is telling you that it found two versions of `new` and doesn't know which one to use.

You could look in "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\new" and see if the definition of the operator (on line 59) is surrounded by any ifdefs, and consider whether you can use an appropriate macro definition in your compiler settings to disable it.

This doesn't really have anything to do with Catch, right?

**Comment by horenmar** [comment]
I don't think that making Catch allocator aware is anywhere on the roadmap.
