### ISSUE TITLE
Option '-n' not working

### ISSUE THREAD

**Issue by hhinke** [philsquared/Catch#469]
Documentation says that if option **-n** is omitted the name for the test run is the same of the executable. 

That's not working for **JUnit** reporter.
The name of the testsuite (attribute name of tag <testsuite> on generated JUnit XML), by default, is **"all tests"** and when **-n** option is used it remains **"all tests"**.

**Comment by jfemia** [comment]
I noticed this too - it's hard-coded.

I made the following quick change to work around the issue (which may not be the best way but it solved my problem).

```
@@ -5582,5 +5582,5 @@
             Totals totals;
 
-            context.testGroupStarting( "all tests", 1, 1 ); // deprecated?
+            context.testGroupStarting( context.config()->name(), 1, 1 ); // deprecated?
 
             TestSpec testSpec = m_config->testSpec();
@@ -5613,5 +5613,5 @@
                 m_reporter->skipTest( *it );
 
-            context.testGroupEnded( "all tests", totals, 1, 1 );
+            context.testGroupEnded( context.config()->name(), totals, 1, 1 );
             return totals;
         }
```

**Comment by hhinke** [comment]
I don't know what can be better than this solution, but worked well. Now the testsuite name is correctly set! thanks

**Comment by philsquared** [comment]
Not sure what I was thinking when I put that "all tests" in there - perhaps it was a placeholder.
In any event I see no reason why it should not be as you suggest, @jfemia, so I've changed it to that now (will push later - you'll see a commit notification here).
