### ISSUE TITLE
catch.hpp doesn't play well with VS 2015 and _HAS_AUTO_PTR_ETC=0

### ISSUE THREAD

**Issue by socantre** [philsquared/Catch#479]
VS 2015 allows projects to opt into an implementation of [ISO C++ proposal n4190](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4190.htm), which has been [accepted for C++17](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4497.pdf). This proposal removes a number of deprecated features including `auto_ptr` and `random_shuffle`. Projects opt in by setting a preprocessor define [`/D_HAS_AUTO_PTR_ETC=0`](http://blogs.msdn.com/b/vcblog/archive/2015/04/29/c-11-14-17-features-in-vs-2015-rc.aspx).

VS2015 still defines `__cplusplus` as `199711L`, so the [`unique_ptr` detection](https://github.com/philsquared/Catch/blob/3b18d9e962835100d7e12ac80d22882e408e40dc/single_include/catch.hpp#L3758) in catch.hpp still falls back to `auto_ptr` for visual studio.

catch.hpp also [uses `std::random_shuffle`](https://github.com/philsquared/Catch/blob/3b18d9e962835100d7e12ac80d22882e408e40dc/single_include/catch.hpp#L5788).

**Comment by philsquared** [comment]
Thanks for bringing this up.
The `auto_ptr` detection should be easy enough (should be able to use `unique_ptr` since at least VS2013).
`random_shuffle` shouldn't be a huge job either, but it will require the alternate code, with `std::shuffle`, to be written.
I'll try and get to looking at this when I get back from holiday (in a couple of weeks).

**Comment by nabijaczleweli** [comment]
Why are you trying to use Visual Studio *anyway*?

**Comment by bkentel** [comment]
This is still an issue in the following locations:
https://github.com/philsquared/Catch/blob/master/include/internal/catch_stream.h#L52
https://github.com/philsquared/Catch/blob/master/include/internal/catch_config.hpp#L154
https://github.com/philsquared/Catch/blob/master/include/internal/catch_test_case_registry_impl.hpp#L44

**Comment by BrettRyland** [comment]
I've also just been bit by the `__cplusplus` value of VS2015 being `199711L` while compiling the example in the tutorial and using the `/std:c++latest` compiler flag. Manually defining `#define CATCH_CPP14_OR_GREATER` before including `catch.hpp` fixed the problem though.

**Comment by horenmar** [comment]
@BrettRyland Can you verify if this is still the case for current master? I merged a commit that uses `std::shuffle` instead of `std::random_shuffle` this week, so it should be fixed.

**Comment by BrettRyland** [comment]
@horenmar Sorry for the late reply, I was on holiday. Indeed, the current master fixes the problem for me. Thanks!
