### ISSUE TITLE
Prevent naming conflicts with headers by nesting under a `catch` directory

### ISSUE THREAD

**Issue by michaelbprice** [philsquared/Catch#481]
Currently the directories `include` and `single_include` contain the headers directly.  In order to prevent collisions with other header names consuming sources, the headers should be nested under a `catch` directory.  This is essentially namespaces for headers and is a common practice.

In this proposed change, consumers would

```
#include "catch/catch.hpp"
```

instead of

```
#include "catch.hpp"
```

**Comment by horenmar** [comment]
Catch's CMake setup installs the header under `catch/catch.hpp`, but the repository topology will remain as-is.
