### ISSUE TITLE
[Help] test asynchronous code

### ISSUE THREAD

**Issue by Darelbi** [philsquared/Catch#483]
Can someone give some hint on how to test asynchronous code with Catch, what I want is running some thread, and at some point test a condition, of course I don't want to introduce "extra synchronization" inside the test because that may make impossible detecting a bug.

The perfect place to test something should be inside the thread, but as far as I know, I cannot put a "REQUIRE" clause inside the scope of threaded function.. or yes?

Thanks

**Comment by horenmar** [comment]
You are correct that Catch does not support multiple threads running through test macros (REQUIRE, SECTION, etc). You would have to save the test result into a bool and REQUIRE on it from main thread, after you join other threads, but that loses you expression decomposition

**Comment by htfy96** [comment]
It would be better to mention this in documentation 
😞 spent whole night on a weird crash
