### ISSUE TITLE
Catch doesn't compile

### ISSUE THREAD

**Issue by czipperz** [philsquared/Catch#487]
I can't get Catch to compile. Here's my `main` file:

     //main.cc
    #define CATCH_CONFIG_MAIN
    #include "catch.hpp"

Then I compile like this:

    g++ -c main.cc

Here are the errors I get:

    In file included from main.cc:2:0:
    catch.hpp:875:17: error: 'nullptr_t' in namespace 'std' does not name a type
         inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
                     ^
    catch.hpp:996:58: error: 'template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare' conflicts with a previous declaration
         template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                              ^
    catch.hpp:990:44: note: previous declaration 'namespace Catch::Internal { }::compare'
         template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                                ^
    catch.hpp:996:53: error: 'nullptr_t' is not a member of 'std'
         template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                         ^
    catch.hpp:996:70: error: expected primary-expression before '*' token
         template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                          ^
    catch.hpp:996:72: error: 'rhs' was not declared in this scope
         template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                            ^
    catch.hpp:996:76: error: expression list treated as compound expression in initializer [-fpermissive]
         template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                                ^
    catch.hpp:996:78: error: expected ';' before '{' token
         template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                                  ^
    catch.hpp:999:66: error: 'std::nullptr_t' has not been declared
         template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                                                      ^
    catch.hpp:999:44: error: redefinition of 'template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)'
         template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                                ^
    catch.hpp:990:44: note: 'template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)' previously declared here
         template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                                ^
    In file included from main.cc:2:0:
    catch.hpp:1099:38: error: 'std::string Catch::toString' redeclared as different kind of symbol
     std::string toString( std::nullptr_t );
                                          ^
    catch.hpp:1096:13: note: previous declaration 'std::string Catch::toString(unsigned char)'
     std::string toString( unsigned char value );
                 ^
    catch.hpp:1099:23: error: 'nullptr_t' is not a member of 'std'
     std::string toString( std::nullptr_t );
                           ^
    In file included from main.cc:2:0:
    catch.hpp:7351:38: error: 'std::string Catch::toString' redeclared as different kind of symbol
     std::string toString( std::nullptr_t ) {
                                          ^
    In file included from main.cc:2:0:
    catch.hpp:1222:13: note: previous declaration 'template<class T, class Allocator> std::string Catch::toString(const std::vector<_Tp, _Alloc>&)'
     std::string toString( std::vector<T,Allocator> const& v ) {
                 ^
    In file included from main.cc:2:0:
    catch.hpp:7351:23: error: 'nullptr_t' is not a member of 'std'
     std::string toString( std::nullptr_t ) {
                           ^

What am I supposed to do?

I am using g++ 5.2.0 and the most recent release of Catch.
Arch linux, kernel version 4.0.7.2. 64 bit.

**Comment by PureAbstract** [comment]
Try adding `-std=c++11` to your gcc command line.
(This looks like #424 again)

**Comment by czipperz** [comment]
That still doesn't work.

**Comment by kirbyfan64** [comment]
@czipperz Would you happen to be using GCC 4.6 or lower?

**Comment by czipperz** [comment]
@kirbyfan64 it was already in my issue... 5.2.0

**Comment by PureAbstract** [comment]
@czipperz Try compiling this:
```
#include <cstddef>
const std::nullptr_t p;
```

**Comment by DavidEGrayson** [comment]
I thought we fixed this already when we discussed it here: https://github.com/philsquared/Catch/pull/471

Why was adding `--std=gnu++11` not enough to fix @czipperz's problem?

**Comment by philsquared** [comment]
There are two things here.
In @czipperz's case I suspect getting `nullptr` to be defined is what is wanted. As @PureAbstract says that's not really a Catch issue, but that doesn't mean we can't help. I'm interested in whether the Catchless example @PureAbstract suggested repros the issue or not - since --std=c++11 should have worked.

Aside from that Catch should work fine without `nullptr`. The latest code on the develop branch has tweaked C++11 detection for GCC, as mentioned in #471, which seems like it should be solving the issue from the other angle (thanks for bringing that up @DavidEGrayson). So I'm also curious why that is not in effect. I presume that when @czipperz says, "the latest release of Catch" he is referring to the latest on Master. If so could you please also try the latest on Develop and report back?

**Comment by czipperz** [comment]
@PureAbstract You can't have a const value without a value (clang and gcc both give same error for this)

**Comment by czipperz** [comment]
@philsquared compiling the develop version on both clang and gcc gives a bunch of errors.

**Comment by PureAbstract** [comment]
Do either of them carp about nullptr_t not being declared? (Which was your original problem)

**Comment by czipperz** [comment]
No, turns out the develop version didn't work because I didn't recompile the main test file (that has no tests).  Thanks for the help everyone!

**Comment by kevinushey** [comment]
For what it's worth, I think this is an issue that could be handled in Catch -- effectively, the availability of `std::nullptr_t` is being mis-detected when the C++ standard is not specified. Issue here: https://github.com/philsquared/Catch/issues/487
