### ISSUE TITLE
add a non fatal alternative to the FAIL logging macro

### ISSUE THREAD

**Issue by blastrock** [philsquared/Catch#491]
Hi,

I saw the macro FAIL in the logging macros which aborts the tests and marks it as failed. It would be nice to have a more gentle alternative that would mark the test as failed without aborting it (as CHECK(something_false) does).

My use case is that I want to mark the test as failed in a class destructor, but as FAIL throws an exception in there, it makes everything crumble and ultimately makes the program std::terminate because there are two exceptions to handle.

**Comment by Eloff** [comment]
Just use WARN?

**Comment by blastrock** [comment]
WARN does not mark the test as failed...

**Comment by rollbear** [comment]
You may want to view https://github.com/rollbear/Catch/tree/develop

I presume (and accept by default that) there are good reasons Phil hasn't accepted the PR, but I do believe something along those lines would be good.

**Comment by blastrock** [comment]
Oh thanks, exactly what I want :)
I'll close this then and comment on #416
