### ISSUE TITLE
Unwanted Approx behaviour

### ISSUE THREAD

**Issue by takacsd** [philsquared/Catch#499]
I have some issues with the Approx class.
Namely, when I see something like:
```
  100.2 == Approx(100).epsilon(0.01)
```
I would expect a check like abs(100.2 - 100) < 0.01, so I expect failure.
But it will pass, because the actual expression is something totally different.

It is possible that this naive implementation is not stable numerically, which is fine (although I can't see why), but at least the expression should be properly documented in the reference documentation.

It would be also nice, if the output would be more meaningful, something like:
```
  passed: 100.2 == Approx(100).epsilon(0.01) for: 100.2 == Approx( 100.0 +- 1.01 )
```
 so the accepted interval would be clear.

**Comment by CNugteren** [comment]
You are confusing absolute and relative errors. Catch uses a relative error metric (the ```epsilon```), while you want an absolute error metric. I've added such a thing in #538.

**Comment by takacsd** [comment]
Either I'm confusing absolute and relative errors, or it wasn't properly documented...
But thanks anyway.

**Comment by julien-l** [comment]
I agree with the op, the documentation is not clear: I had to dig into the Catch code to realize that espilon was the relative error. The documentation does not specify it. (Sorry for the comment on a closed post, but since the documentation hasn't been updated, I posted anyway.)

**Comment by onqtam** [comment]
+1
