### ISSUE TITLE
Junit XML reporter

### ISSUE THREAD

**Issue by philsquared** [philsquared/Catch#5]
It should be possible to obtain xml reports that follow the schema for JUnit - for consumption by third party tools

**Comment by Trass3r** [comment]
Is there anything left for this one?

**Comment by SebDyn** [comment]
> Is there anything left for this one?

I just tried recent Catch 1.1 build 1 and frankly I need to reply with: No. It is - again - not really working.

Here is the reason:

- Old CATCH (working):

        <testsuite errors="0" failures="0" tests="107" hostname="0" time="0.140043" timestamp="0">

- Current Catch (not working):

        <testsuite name="all tests" errors="0" failures="0" tests="1074" hostname="0" time="19.5793" timestamp="0">

I use Jenkins 1.596.2 (stable) with JUnit reporter. The interesting thing is: Jenkins does not return with an error. It just does not display the test results when using the current CATCH output.

**Comment by SebDyn** [comment]
Ok, it seems that Jenkins has a bug somewhere. The "name" keyword ist a mandatory field in JUnit 6 standard. We continue investigating this issue.

**Comment by alt-** [comment]
The fields with "tbd" really need to go or be fixed.

Jenkins' Junit plugin performs duplication checks on inputs by "strict" comparing (null doesn't match) the name, id and timestamp fields (https://github.com/jenkinsci/junit-plugin/blob/master/src/main/java/hudson/tasks/junit/TestResult.java#L240). 

If the timestamp field would be missing, it would work correctly, but the dummy value "tbd" matches the check and Jenkins throws away all other test results.

**Comment by horenmar** [comment]
Timestamp should now be filled with proper UTC-based time, at the time of writing the results, and most other issues raised in this thread be addressed as well.

If there are some issues remaining, please open a new issue for them.
