### ISSUE TITLE
-l shows 2 tests but when ran I get No Tests Ran

### ISSUE THREAD

**Issue by NickPadilla** [philsquared/Catch#503]
Hello, 

Love this project!  Looking forward to integration with XCode debugger!  

We set it up first on our development platform - Mac OSX, which works just fine.  Now that we are trying to integrate with our build platform - Ubuntu 32/64 bit - it doesn't work when taking control over main().  All our other tests work just as expected however. 

So the setup is that we have a Poco Project application that hijacks the main() and does a bunch of setup for us - the application we are testing uses this framework heavily and also has a runtime configuration that is needed for some of the tests.  So I have a TestBase.h that provides the wiring, this works perfectly on OSX but not so on Ubuntu 32/64.  I am getting this when I run with `-s` only

```
=============================================================================
 No tests ran
```

However when running the guy with the `--list-tests` option, I get this.

```
All available test cases:
  Testing namespace::Service::updateConfig 
     [updateConfig]
  Testing namespace::Service::updateText 
     [updateText]
2 test cases
```

Any idea as to why Catch can find the tests cases with the `-l` flag, but when attempting to run them it doesn't?  If you need any more information please let me know.

**Comment by philsquared** [comment]
Thanks for reporting your issue here, Nick.
The only difference between actually running the tests and just listing them with `-l` should be that "hidden" tests are still shown when you list them (but in grey, if you're using a colourised output).
In your example it doesn't *look* like any of your tests are hidden - although it's not clear if that output is from your actual code or just a representative example?
It also wouldn't explain the platform differences. I've not heard of anything similar on Ubuntu before.

Do you see the same behaviour on Ubuntu with a simple test case that doesn't use Poco?

**Comment by NickPadilla** [comment]
Hey @philsquared - Thanks for the quick response!  All the simple tests run on Ubuntu no problems, and on OSX the tests that include the TestBase.h (Poco Wiring) work just fine.  I do not believe that any of our tests are written as hidden tests.  

That is the output from the actual code, just updated the data in the name portion.  

I agree that there shouldn't be any difference in functionality between a run on OSX or Ubuntu.  I just don't have time this week to run over the catch code and see what is happening, so figured I'd just post this here to see if anyone else might have some input.  

I am not doing anything complex, just passing in the command line args like the docs show, `returnCode = session.applyCommandLine(argc, argv);`  and then if the return code is valid we do `exit = session.run();`.  Doesn't seem to be anything out of place from what i can tell, and the fact that it does indeed work on OSX we can assume the setup is good.  

Just an FYI, we will be compiling and running the tests for `arm-linux-gnueabihf-` and `arm_v5t_le-` toolchains as well.  As soon as we have all our ducks in and row, and working ;), we plan on putting together a nice tutorial on how to wire the different pieces together.

**Comment by horenmar** [comment]
@NickPadilla  This issue is kinda old, but still: has anything come of it afterwards?

If not, I am going to close this soon because looking for year and a half old, platform dependent, issue with no repro is probably not worth the time given how much has Catch changed in the meantime.
