### ISSUE TITLE
Catch relies on DEBUG macro, though it's not documented.

### ISSUE THREAD

**Issue by cubuspl42** [philsquared/Catch#508]
Maybe it's a standard convention, but I had a really hard time diving into Catch sources to find out that "--break" didn't work for me, because I didn't have DEBUG macro defined. This should be mentioned somewhere.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
This problem is worse than you describe for me. I have to #define DEBUG to get the test-case code to compile at all.

**Comment by philsquared** [comment]
This is no longer the case, as of 70d3c937c31bfa28fbba940d505b6de006ea8529
