### ISSUE TITLE
Get name of current test case

### ISSUE THREAD

**Issue by mlogan** [philsquared/Catch#510]
Is there are macro or function call that evaluates to the name of the current test case? I've looked through catch.hpp and searched the github repo and haven't found anything. Thanks!

**Comment by philsquared** [comment]
The short answer is "yes".
The slightly longer answer is, "yes - but it's not technically public - so is liable to change - in fact I'm doing some refactoring in exactly that area at the moment!

However, if you're prepared to live with that (if I do change it there will still be another way to do it) then you can use this for now:

  Catch::getResultCapture().getCurrentTestName();

Out of interest why do you need this?

**Comment by mlogan** [comment]
I want to produce some test artifacts, and its much cleaner and easier if I can log them to a file based on the name of the test.

**Comment by mlogan** [comment]
Thanks for the info, sounds just like what I need.

**Comment by jgm-radez** [comment]
Is there an equivalent for section name, perhaps including the section leaf parent names?  Like the context-as-a-string?  Trying to name some performance artifacts collected during the tests... i.e. performance artifact A came from test case/section[/section] B

**Comment by jgm-radez** [comment]
Does this work?

        virtual std::vector<std::string> getCurrentSectionNames() const {
                std::vector<std::string> retval;
                for(std::vector<ITracker*>::const_iterator iter=m_activeSections.begin(); iter!=m_activeSections.end(); ++iter)
                        retval.push_back((*iter)->nameAndLocation().name);
                return retval;
        }

**Comment by isidore** [comment]
Would also like a version for section names. 
Ideally 

    Catch::getResultCapture().getCurrentSectionName()

**Comment by jkransom** [comment]
`Catch::getResultCapture().getCurrentTestName()` is now marked as deprecated. Is there a replacement? (Hopefully one which also gives us the section names?)
