### ISSUE TITLE
Incomprehensible text in tutorial.md

### ISSUE THREAD

**Issue by LudwikJaniuk** [philsquared/Catch#517]
Line 99, "In particular, the way your code must be split up and the blunt granularity of cause problems."

This sentence is unreadable. Maybe the intended meaning was: "In particular, the way your code must be split up and the blunt granularity of **it will** cause problems."?

**Comment by philsquared** [comment]
Well spotted. Thanks!
I've corrected it to what I think was my original intention (close to your guess) - on Develop for now - will merge over to master later.

**Comment by LudwikJaniuk** [comment]
Gr8. Also, Catch rocks!
