### ISSUE TITLE
Catch, nullptr and gcc 5.0: availability of std::nullptr_t misdetected w/C++98

### ISSUE THREAD

**Issue by kevinushey** [philsquared/Catch#526]
Note: this is similar to https://github.com/philsquared/Catch/issues/487, but I think something could be done in Catch to help alleviate this.

It looks like `gcc` does not define `std::nullptr_t` when the C++ standard (through `-std`) is not specified. A simple workaround is to ensure that you compile with `std=c++11` or above, but some of us unfortunately live in a world where we must adhere to the C++98 standard.

I think the lines [here](https://github.com/philsquared/Catch/blob/d758428fe297655e558a86cc6a013fcb1bcc8c7d/include/internal/catch_compiler_capabilities.h#L69-L71) need to be amended to only operate with GCC with major version 4. With gcc 5 and above, one must explicitly opt into the C++11 standard if they want `std::nullptr_t`; that would then be detected [here](https://github.com/philsquared/Catch/blob/d758428fe297655e558a86cc6a013fcb1bcc8c7d/include/internal/catch_compiler_capabilities.h#L109-L111).

(and PS: thanks to everyone who has contributed to Catch; it's an amazing tool!)

**Comment by kevinushey** [comment]
It looks like this is handled in the PR here: https://github.com/philsquared/Catch/pull/471.

**Comment by philsquared** [comment]
So are you saying that the result of PR #471 fixes the issue for you (I just noticed that one should have been closed but was still open)?

**Comment by kevinushey** [comment]
That's right, although the fix is currently only part of the `develop` branch and not the `master` branch, IIUC? https://github.com/philsquared/Catch/commit/f3308ed7c48c7989464817d5b1f07c66122c1d85
