### ISSUE TITLE
"unreferenced local variable" warning in MSVC12

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#532]
Visual Studio 2013 is giving me the following warning:

> warning C4101: 'valid' : unreferenced local variable

Code:

```
TEST_CASE("Checking IsAlpha", MAIN_TAG)
{
   CFieldValidator valid; // WARNING IS HERE
  
   SECTION("Non-alpha characters, expect false")
   {
      const int SIZE = 8;
      const char *str[SIZE];

      //Long invalid strings
      str[0] = "0123456789";
      str[1] = "!@#$%^&*()_+";
      str[2] = "MostlyGo0dString";
      
      //Short invalid strings
      str[3] = "1";
      str[4] = "&";

      //Edge char's invalid
      str[5] = "1istheloneliestnumber";
      str[6] = "Couldn'tthinkofanythingwitty^";

      //Null pointer
      str[7] = 0;
     
      for (int i = 0; i < SIZE; i++)
      {
         INFO("str[" << i << "]: " << (str[i] ? str[i] : "NULL"));   
         CHECK(!valid.IsAlpha(str[i]));
      }
   }
}
```

I'm using it in the FOR loop near the bottom of the `SECTION`. Why is this warning happening? I'm using the following version of Catch (single include):

https://github.com/philsquared/Catch/commit/ece529ae7cd5fe15d698986aabdd5faf23e333f8

**Comment by elken** [comment]
[Here](https://msdn.microsoft.com/en-us/library/c733d5h9.aspx) is the MSDOC on that error code. `valid` is never assigned anything.

**Comment by rcdailey** [comment]
I didn't realize `IsAlpha()` was a static function. Thank you for pointing it out.
