### ISSUE TITLE
error: undefined reference to 'vtable for Catch::NonCopyable'

### ISSUE THREAD

**Issue by awhlee** [philsquared/Catch#540]
Hi,

New to Catch.  Seems like a great project.  As my first test, I included catch.hpp in a simple class and created two functions succeedingCase() and failingCase() (much like the examples in SelfTests/ClassTests.cpp).  Realized that I needed a default constructor for my class and resolve that issue.  Now when I try to build, I get the following types of errors:

single_include/catch.hpp:241: error: undefined reference to 'vtable for Catch::NonCopyable'
/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
./../src/common/sample/todo_list_impl.cpp:40: error: undefined reference to 'Catch::SourceLineInfo::SourceLineInfo(char const*, unsigned int)'
./../src/common/sample/todo_list_impl.cpp:40: error: undefined reference to 'Catch::ResultBuilder::ResultBuilder(char const*, Catch::SourceLineInfo const&, char const*, Catch::ResultDisposition::Flags)'
./../src/common/sample/todo_list_impl.cpp:40: error: undefined reference to 'Catch::ResultBuilder::endExpression()'
./../src/common/sample/todo_list_impl.cpp:40: error: undefined reference to 'Catch::ResultBuilder::shouldDebugBreak() const'
./../src/common/sample/todo_list_impl.cpp:40: error: undefined reference to 'Catch::ResultBuilder::react()'
./../src/common/sample/todo_list_impl.cpp:40: error: undefined reference to 'Catch::ResultBuilder::useActiveException(Catch::ResultDisposition::Flags)'
./../src/common/sample/todo_list_impl.cpp:41: error: undefined reference to 'Catch::SourceLineInfo::SourceLineInfo(char const*, unsigned int)'
./../src/common/sample/todo_list_impl.cpp:41: error: undefined reference to 'Catch::ResultBuilder::ResultBuilder(char const*, Catch::SourceLineInfo const&, char const*, Catch::ResultDisposition::Flags)'
./../src/common/sample/todo_list_impl.cpp:41: error: undefined reference to 'Catch::ResultBuilder::endExpression()'
./../src/common/sample/todo_list_impl.cpp:41: error: undefined reference to 'Catch::ResultBuilder::shouldDebugBreak() const'
./../src/common/sample/todo_list_impl.cpp:41: error: undefined reference to 'Catch::ResultBuilder::react()'
./../src/common/sample/todo_list_impl.cpp:41: error: undefined reference to 'Catch::ResultBuilder::useActiveException(Catch::ResultDisposition::Flags)'

I'm building with the Android NDK and this is what my Application.mk looks like:
APP_OPTIM := debug
APP_ABI := armeabi
APP_STL := stlport_static 
APP_CPPFLAGS := -frtti -fexceptions -std=gnu++11 
APP_PLATFORM := android-19
APP_BUILD_SCRIPT := Android.mk
NDK_TOOLCHAIN_VERSION = 4.9
APP_STL := gnustl_static

My Android.mk doesnt' have anything magical in it.  It just sets the include folders and files that are to be compiled into the library.

Thanks in advance for any help.
--Tony

**Comment by awhlee** [comment]
Trying to build the same code outside of the NDK env with a dedicated gnu makefile.

**Comment by philsquared** [comment]
Have you used `#define CATCH_CONFIG_MAIN` somewhere?

**Comment by awhlee** [comment]
Yes...I screwed up.  I had catch.hpp included somewhere and CATCH_CONFIG_MAIN somewhere else and this was not getting defined before the header was being included.  Rookie mistake but thanks for the response :)

**Comment by grossd** [comment]
Hi, 

i have the same problem, after installing catch2 via git clone, on ubuntu 18.01, using clion C++

/however, i am not using $define CATCH_CONFIG_MAIN ...

and added tests to the main.cpp

and initially also tried to include catch.hpp in a seperate file with a test case ,and without main. 

in both cases i got errors such as above. 

any thoughts are much appreciated.

**Comment by grossd** [comment]
i now created a new project, a static library,  imported catch.hpp, configured main, and pasted the facorial example, catch, built successfully -- so thats great. 

however, when trying to run  i get an error:

10:12 PM	Error running 'Factorials are computed': Cannot run 'Factorials are computed' on '<default>'

not sure what this is -- perhaps something with the configuration ... 

any thoughts are much appreciated.

**Comment by horenmar** [comment]
Why do you not have `#define CATCH_CONFIG_MAIN` somewhere?

**Comment by grossd** [comment]
Hi Martin,

Thank you for your reply.

I just now figured it out.

Its basic stuff, but i am completely new to this all ...

To get it to work with CLion (on Ubuntu), i had to create a new console
project, then include catch, add the CATCH_CONFIG_MAIN, and comment out the
predefined main() function. Like this i think, the CMAKE file was
configured correctly as well.

Only, then could i compile and run the test.

Initially, i thought it would work when i create a library project.

Next step i'd like to create my functions in a library, and include them
into this main for testing.

thank you,

Daniel
