### ISSUE TITLE
Add & to REQUIRE_THROWS_AS type?

### ISSUE THREAD

**Issue by joto** [philsquared/Catch#542]
Exceptions should generally be caught by reference (`catch(some_type&)`). But if you give a simple type to `REQUIRE_THROWS_AS({...}, some_type);`, the macro will generate a catch by value (`catch(some_type)`). Not really a problem, but `clang-tidy` complains. Of course I can just use references myself, but it is not clear to the user that he always has to do this. Maybe we could change the `INTERNAL_CATCH_THROWS_AS` macro): 

```
-            catch( exceptionType ) { \
+            catch( std::add_lvalue_reference<exceptionType>::type ) { \
```

Unfortunately this solution only works in C++11.

**Comment by nabijaczleweli** [comment]
`add_*_reference<>` can be trivially implemented in usercode, so you could just have:
```c++
namespace catch {
#if cpluspluseleven
  template<class T>
  using add_lvalue_reference = std::add_lvalue_reference<T>;
#else
  template <typename T>
  struct add_lvalue_reference {
    typedef T & type;
  };
  template <typename T>
  struct add_lvalue_reference<T &> {
    typedef T & type;
  };
  template <typename T>
  struct add_lvalue_reference<T &&> {
    typedef T & type;
  };
#endif
}
```
