### ISSUE TITLE
Uninitialized member in TestRegistry

### ISSUE THREAD

**Issue by dawagner** [philsquared/Catch#545]
Hi,

I'm using ctest to run catch tests monitored by valgrind. As you can see in [this CI report](https://travis-ci.org/01org/parameter-framework/jobs/94879897), valgrind has found an uninitialized variable in TestRegistry. The CI uses the lastest (master) "single include".

It turns out that [`m_currentSortOrder`](https://github.com/philsquared/Catch/blob/master/include/internal/catch_test_case_registry_impl.hpp#L119) is indeed left uninitialized.

It seems that the `m_sortedFunctions.empty()` test above serves to detect the first time that method is called; `m_currentSortOrder` could be initialized there.

**Comment by mlin** [comment]
+1

**Comment by Morwenn** [comment]
I was about to report the exact same error. Glad to see that I'm not the only one getting it :)

**Comment by philsquared** [comment]
Good catch - thanks! All sorted (puns intended)

**Comment by dawagner** [comment]
You're welcome!
