### ISSUE TITLE
missed catch_runner.hpp in latest repository snapshot

### ISSUE THREAD

**Issue by amigo421** [philsquared/Catch#560]
after last pull , my project reports me about missed catch_runner.hpp in /include of catch lib

**Comment by philsquared** [comment]
Is this your own project, or one of the ones from the Catch repository?

**Comment by amigo421** [comment]
own project, which uses Catch lib, I didn't update Catch a few months, and did this a week ago, and got a error during project rebuild. I've temporary moved to single header version. It works for sure. I didn't investigate the issue inside Catch , I only see that there is a reference on this header inside other Catch files but git snapshot of Catch doesn't contain this file

**Comment by TrueWodzu** [comment]
I can confirm this problem. Just downloaded Catch for my first try and received error about missing catch_runner.hpp in catch_with_main.hpp

**Comment by philsquared** [comment]
Sorry about that. `catch_with_main.hpp` got a bit left behind. `catch_runner.hpp` was deleted back in August. I've fixed things up now.

**Comment by horenmar** [comment]
Either resolved or too old to matter.

**Comment by philsquared** [comment]
Resolved, yes
