### ISSUE TITLE
Catch doesn't work with gcc 5.2.0 under CygWin

### ISSUE THREAD

**Issue by mg262** [philsquared/Catch#564]
I've just updated my gcc version from 4.9.3 to 5.2.0 using Cygwin setup under Windows 7, and this seems to have broken Catch. Minimal working example: create a file "c.cpp" (copied from the tutorial, also copied below) with catch.hpp from Catch v. 1.3.1 in the same directory and run it through g++, I get an executable that outputs nothing when I run it.  (Passing the -h flag to it has no effect either.) 

I've checked that a 'hello world' program functions correctly under gcc 5.2.0 to rule out problems with my system.

---

#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

unsigned int Factorial( unsigned int number ) {
    return number <= 1 ? number : Factorial(number-1)*number;
}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
    REQUIRE( Factorial(1) == 1 );
    REQUIRE( Factorial(2) == 2 );
    REQUIRE( Factorial(3) == 6 );
    REQUIRE( Factorial(10) == 3628800 );
}

**Comment by nabijaczleweli** [comment]
Norepro:
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

d:\Pobieranie\asdf>cat c.cpp
#define CATCH_CONFIG_MAIN // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"

unsigned int Factorial( unsigned int number ) {
return number <= 1 ? number : Factorial(number-1)*number;
}

TEST_CASE( "Factorials are computed", "[factorial]" ) {
REQUIRE( Factorial(1) == 1 );
REQUIRE( Factorial(2) == 2 );
REQUIRE( Factorial(3) == 6 );
REQUIRE( Factorial(10) == 3628800 );
}
d:\Pobieranie\asdf>g++ -std=c++14 -Wall -Wextra -O3 -ICatch-1.3.1\include c.cpp

d:\Pobieranie\asdf>a
===============================================================================
All tests passed (4 assertions in 1 test case)


d:\Pobieranie\asdf>
```

**Comment by kirbyfan64** [comment]
@nabijaczleweli You're testing MinGW, not Cygwin...

**Comment by nabijaczleweli** [comment]
Cygwin should die in a fire

**Comment by philsquared** [comment]
@mg262 does it return an error code?

**Comment by mg262** [comment]
I haven't caught the error level from the command prompt in a very long time, so I am using a method grabbed from Google... 

`Mohan@QuietPC ~/core-sdk/dist/foo
$ g++ c.cpp

Mohan@QuietPC ~/core-sdk/dist/foo
$ cat run.bat
@echo off
a.exe
echo Exit Code is %errorlevel%
Mohan@QuietPC ~/core-sdk/dist/foo
$ ./run.bat
Exit Code is -1073741511`

**Comment by mg262** [comment]
Having looked into this more, I think the problem may be with the Cygwin installer -- it may not be updating the runtime libraries. [https://www.cygwin.com/ml/cygwin/2015-12/msg00143.html]  

Assuming that is the problem, sorry to waste your time.
