### ISSUE TITLE
use MPI in tests (aka MPI_Init in main)

### ISSUE THREAD

**Issue by nschloe** [philsquared/Catch#566]
The tests I'm considering to switch to Catch are required to run in serial as well as with multiple processes, i.e., all of
```
$ ./ioTest
$ mpiexec -n 2 ./ioTest
$ mpiexec -n 7 ./ioTest
```
need to pass. Naturally, I need to call
```c++
MPI_Init(&argc, &argv)
```
in the main file for this to work (and ideally `MPI_Finalize();`, too). I trust `#define CATCH_CONFIG_MAIN` doesn't take care of that.

Is it possible to handle this with Catch?

**Comment by nabijaczleweli** [comment]
Take a look at [supplying your own main()](https://github.com/philsquared/Catch/blob/master/docs/own-main.md) in the reference.

**Comment by nschloe** [comment]
Thanks, that did the trick. I'm now always linking
```c++
#define CATCH_CONFIG_RUNNER
#include <catch.hpp>

#include <Teuchos_GlobalMPISession.hpp>

int main(int argc, char* argv[])
{
  Teuchos::GlobalMPISession mpiSession(&argc, &argv, NULL);
  const int result = Catch::Session().run(argc, argv);
  return result;
}
```
with my tests.
