### ISSUE TITLE
Pending tests?

### ISSUE THREAD

**Issue by IngwiePhoenix** [philsquared/Catch#567]
Is there a way to have pending tests, as in, to "prototype" tests?

In Jasmine, I usually can do:

``` javascript
describe("...", function(){
  it("...");
})
```

and since the call to `it()` didnt get a function, its a pending test.

Is it possible to have that with Catch?

**Comment by nabijaczleweli** [comment]
```cpp
it("...", []() {})
```
I guess?

**Comment by philsquared** [comment]
Not precisely the same thing but if you write a test case (or section) that has no assertions you can get Catch to warn you about them....
Alternatively you could put a FAIL in there and add the [!shouldfail] tag. That way it will show up as a failing test without impacting the test failures count.

Do either of those possibilities fit the bill?

**Comment by IngwiePhoenix** [comment]
I think it'll work. Not exactly a pretty solution though ;)
