### ISSUE TITLE
Unresponsive http://builds.catch-lib.net

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#572]
http://builds.catch-lib.net is unresponsive. If it's no longer used, its mention must be fixed.

From  the [CATCH forum](https://groups.google.com/forum/?fromgroups=#!topic/catch-forum/KjK4PTIvs9Y):

> On Tue, Jan 19, 2016 at 8:24 AM, Becca Telrunya bbladorn@gmail.com wrote:
> 
> I'm trying to learn c++ Testing and found catch but when i follow the link in the tutorial on github (http://builds.catch-lib.net)  it times out without doing anything. "

**Comment by horenmar** [comment]
As of right now, the link is a redirect to github, closing this issue.
