### ISSUE TITLE
anonymous namespace issue

### ISSUE THREAD

**Issue by amigo421** [philsquared/Catch#576]
(not sure that is a problem of the lib). 
I was writing an own project with a lot of headers (with logic)  and added TEST_CASEs into each one. and was debugging/testing these ones individually. But after merging all headers into one project I faced with a number of similar issue which refer to TEST_CASE declaration in various modules in my project 
(just for sure, my code works as designed and removing a part of TEST_CASEs solve the problem ), I'm also confirming that all TEST_CASEs compiled and work correctly in case of including into the project without other headers (looks like a conflict). the errors looks like these ones:
```
c:\dev\workspace\algolist\src\algolist.hpp(143): error C2374: '`anonymous-namespace'::autoRegistrar143': redefinition; multiple initialization
c:\dev\workspace\algolist\src\mfactory.hpp(143): note: see declaration of '`anonymous-namespace'::autoRegistrar143'
c:\dev\workspace\algolist\src\algolist.hpp(143): error C2084: function 'void ____C_A_T_C_H____T_E_S_T____143(void)' already has a body
c:\dev\workspace\algolist\src\mfactory.hpp(143): note: see previous definition of '____C_A_T_C_H____T_E_S_T____143'
```

**Comment by miklelappo** [comment]
#define CATCH_INTERNAL_LINEINFO ::Catch::SourceLineInfo( __FILE__, static_cast<std::size_t>( __LINE__ ) )

**Comment by miklelappo** [comment]
The unique name don't have to use line number, otherwise when including other files you'll get this error

**Comment by horenmar** [comment]
We now use `__COUNTER__` if possible (the compiler supports it). Can you please check whether current single-include release still causes this error for you?

**Comment by amigo421** [comment]
hi mate,
is the problem still actual? 
from those times, I changed my style and now never write a tests in the same header.
so that is a no issue for me yet, but I can try to do this , just to assist with a testing

**Comment by horenmar** [comment]
@amigo421 It _should_ be fixed, but testing is always welcome.

**Comment by philsquared** [comment]
Any feedback would be welcome. However please note that it does depend on whether we detect compiler support for `__COUNTER__`.

**Comment by amigo421** [comment]
if you treat this as solved, I won't test this right now , just will report this in case Iwill have  faced with this again (i'm mostly using vc++ which supports __COUNTER__)

p.s. congrats-glad to see that you now work with jetbrains
