### ISSUE TITLE
What kind of "!" prefixed expressions cannot decompose?

### ISSUE THREAD

**Issue by luxe** [philsquared/Catch#577]
Can you elaborate on this?    

>     REQUIRE_FALSE( expression ) and
>     CHECK_FALSE( expression )
> 
> Evaluates the expression and records the logical NOT of the result. If an exception is thrown it is caught, reported, and counted as a failure. **(these forms exist as a workaround for the fact that ! prefixed expressions cannot be decomposed).**

> Example:

> REQUIRE_FALSE( thisReturnsFalse() );  

But all of the checks in this example pass:  
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

bool func(){
  return false;
}

TEST_CASE("test"){

    CHECK(!func());
    CHECK_FALSE(func());
    CHECK(!false);
    CHECK((((!false))));
}
```

Is this documentation still correct?
Can you provide some examples where "!" prefixed expressions cannot be decomposed?

**Comment by kirbyfan64** [comment]
Did you try `CHECK(!true)`?

**Comment by luxe** [comment]
`CHECK(!true);`  does not pass.  This seems to decompose correctly as well.

**Comment by martinmoene** [comment]
Expressions that involve other operators, e.g.: `REQUIRE( ! world < hello );`

```
#define CATCH_CONFIG_MAIN 
#include "catch.hpp"

TEST_CASE( "! expr", "[show]" )
{
    std::string hello("hello");
    std::string world("world");

    REQUIRE( ! true );
    REQUIRE(   hello < world );
    REQUIRE( ! world < hello );
}

// g++ -Wall -I../single_include -o not_expr.exe not_expr.cpp && not_expr.exe
```
Gives:
```
In file included from not_expr.cpp:2:0:
not_expr.cpp: In function 'void ____C_A_T_C_H____T_E_S_T____8()':
not_expr.cpp:15:14: error: no match for 'operator!' (operand type is 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}')
     REQUIRE( ! world < hello );
              ^
not_expr.cpp:15:14: note: candidate: operator!(bool) <built-in>
not_expr.cpp:15:14: note:   no known conversion for argument 1 from 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}' to 'bool'
not_expr.cpp:15:14: error: no match for 'operator!' (operand type is 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}')
     REQUIRE( ! world < hello );
              ^
not_expr.cpp:15:14: note: candidate: operator!(bool) <built-in>
not_expr.cpp:15:14: note:   no known conversion for argument 1 from 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}' to 'bool'
not_expr.cpp:15:22: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
     REQUIRE( ! world < hello );
                      ^
```

So, maybe:
**these forms exist as a workaround for the fact that `!` prefixed expressions cannot be decomposed *if they also involve other operators*.**

**Comment by martinmoene** [comment]
Notice: edited [previous comment](https://github.com/philsquared/Catch/issues/577#issuecomment-174268043).

**Comment by luxe** [comment]
That's not a valid expression one would expect to work in normal C++ either.  
Doing just:  
```
std::string hello ="hello";
std::string world = "world";
if(! hello < world){
}
```
gives a similar error since string does not support the logical negation operator.

**Comment by martinmoene** [comment]
Oops, you're right.

The reason is that writing the expression in parenthesis, like `REQUIRE( ! ( hello < world ) )` defeats expression decomposition.

**Comment by martinmoene** [comment]
Reworked example:
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE( "! expr", "[show]" )
{
    int a = 1;
    std::string hello("hello");
    std::string world("world");

    CHECK( ! true );  // Ok

    CHECK( ! --a );   // Ok

    CHECK(     hello < world );     // Ok
    CHECK( ! ( world < hello ) );   // No expression decomposition
}

// g++ -Wall -I../single_include -o not_expr.exe not_expr.cpp && not_expr.exe --reporter compact --success
```
Result
```
prompt>not_expr.exe --reporter compact --success
not_expr.cpp:10: failed: ! true for: false
not_expr.cpp:12: passed: ! --a for: true
not_expr.cpp:14: passed: hello < world for: "hello" < "world"
not_expr.cpp:15: passed: ! ( world < hello ) for: true
Failed 1 test case, failed 1 assertion.
```

**Comment by luxe** [comment]
Oh!  'Decomposition' refers to showing the expression in the output.  
I was confused into thinking it had something to do with how the actual expression got evaluated, and whether the result was a passing/failing test.  

So the only real danger of using an expression prefixed with "!", is that may appear less clear in the diagnostic output.  CHECK_FALSE exists to provide a more cosmetic output, but it's not required to get the expression to evaluate correctly.  Thanks, that makes more sense now.
