### ISSUE TITLE
SECTIONS execute multiple time

### ISSUE THREAD

**Issue by testhound** [philsquared/Catch#581]
I have what appears to be a simple test with a TEST_CASE and two non-nested SECTIONS. I was receiving unexpected failures and determined that the first SECTION is called the second time through the test which invalidates some of  my preconditions. In fact from debug printouts the second section is being run multiple times as well.

From the documentation my expectation was that the first SECTION is executed, then the variables are re-created, the REQUIRE conditions run, and then the second SECTION.

I determined that the first section was being called multiple times using debug statements in the test.

I am running Linux. I have tried g++ 4.8.4 and g++ 5.3.0. I downloaded and and using catch.hpp from the single_include directory.

**Comment by testhound** [comment]
Never mind I found the problem: my SECTON statements had semicolons at the end of them. So I had

SECTION ("Verify"); instead of SECTION("Verify")

Perhaps error checking could be improved. Sorry for the false alarm

**Comment by diemoschwarz** [comment]
> From the documentation my expectation was that the first SECTION is executed, then the variables are re-created, the REQUIRE conditions run, and then the second SECTION.

Hi, where is that behaviour documented?
You might also want to close the issue, when it's not an issue anymore =-)
Cheers

**Comment by testhound** [comment]
From the tutorial: "For each SECTION the TEST_CASE is executed from the start - so as we enter each section we know that size is 5 and capacity is at least 5. We enforced those requirements with the REQUIREs at the top level so we can be confident in them. This works because the SECTION macro contains an if statement that calls back into Catch to see if the section should be executed. One leaf section is executed on each run through a TEST_CASE. The other sections are skipped. Next time through the next section is executed, and so on until no new sections are encountered."

Not an issue.
