### ISSUE TITLE
Clear INFO logs at each CHECK or REQUIRE

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#587]
Sometimes I like to write `INFO` logs a few times before I do a `CHECK` macro. This should provide me more context if that check fails. However, it seems that the `INFO` logs are not cleared. Thus if 5 `CHECK` calls later it fails, I get all the info logs leading up to that point, which makes things confusing.

Is there a flag to make `CHECK` and `REQUIRE` type macros clear info logs? If not, would it be reasonable to add configuration for this?

**Comment by rcdailey** [comment]
Looks like `INFO` logs are cleared each time you end a `SECTION` or `TEST_CASE`. Is this true? If so, I guess it's the responsibility of text structure to make sure that `INFO` messages are properly decomposed via scope and thus will be cleared?

**Comment by lightmare** [comment]
INFO / CAPTURE logs are cleared at the end of scope, so you can do:
```c++
    {
        INFO("foo");
        CHECK(foo());
    }
    {
        INFO("bar");
        CHECK(bar());
    }
```

**Comment by rcdailey** [comment]
Thank you
