### ISSUE TITLE
Color is disabled in debug mode

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#590]
I noticed that while running a debug build, colors are disabled. This is noticable in the single-header catch.hpp:

```
    void Colour::use( Code _colourCode ) {
        static IColourImpl* impl = isDebuggerActive()
            ? NoColourImpl::instance()
            : platformColourInstance();
        impl->use( _colourCode );
    }
```

Why are colors disabled if the debugger is active? I was wondering why I was getting no color output; I thought initially it was bugged. The reason for this is not documented anywhere. As such, I am not able to directly understand the reasoning for this.

**Comment by kirbyfan64** [comment]
I would think that it would cause insanely weird coloring if a breakpoint were activated before the ANSI color reset code is printed.

**Comment by rcdailey** [comment]
But logs are not printed while stepping through a test case right? And isn't your issue specific to Linux?

**Comment by philsquared** [comment]
That's a very good question.
I can see that I specifically made that change in a dedicated commit (dbcd833c724dee84b70154e3d55213042dd639ff) three years ago - but the commit message just says, "Don't use ANSI colour codes when debugging" - with no rationale or associated issue number (go me!)

I _think_ it's to do with the messages being sent to a debug output console (e.g. in XCode). Depending on your environment and how it is set-up this may or may not happen - so it would be nice to have finer grained control.

There is a `--force-colour` command line option (which I have just noticed is not documented - must fix that). Currently that's only looked at once it has already selected the `platformColourInstance()` path - but it probably makes sense to consult it here too. I might actually be changing that flag anyway (to incorporate #502 as well). I'll try and cover all bases soon...

**Comment by rcdailey** [comment]
I think you are on the right track to step back and rethink and redesign
this small feature. I can see how having colors enabled could not written
well in certain consoles. So toggling this via command line parameter is
reasonable. Thanks for your feedback.

**Comment by nabijaczleweli** [comment]
Can `--force-colour`/some other option set ANSI escapes regardless of platform?

**Comment by philsquared** [comment]
@nabijaczleweli not easily. The platform specific parts of the code make platform specific calls (e.g. `isatty()` in the POSIX case and `SetConsoleTextAttribute()` in the Windows case). So those definitions are not even compiled in unless the platform is detected.
I know there are some cases where more than one platform may be detected (cygwin?) and I suppose it's possible in that case but the code would have to be changed considerable for that case.

**Comment by nabijaczleweli** [comment]
With `--force-colour` you don't need to check if `isatty()`, so you can compile the ANSI colourer *and* the WinAPI colourer at the same time and select them at runtime.

**Comment by philsquared** [comment]
...only if the platform is Windows.
It's not that it's not doable - it will just require a fair bit of rearranging the code - along with introducing certain inconsistencies.
I'm not sure if it's a valuable enough shade of feature at this point (but am open to being convinced).

**Comment by philsquared** [comment]
ok. I have `--use-colour` working now (in a local commit). It takes `yes`, `no` or `auto` (although the latter is the default).
If `yes` or `no` are specified they override the debugger present or isatty() conditions.
I'll push soon.
I'll look at the platform override angle later.

**Comment by philsquared** [comment]
I should have mentioned before that `--use-colour` is in.
