### ISSUE TITLE
Conversion error with overloaded stream operator

### ISSUE THREAD

**Issue by MojaveWastelander** [philsquared/Catch#595]
I have following code example that fails in catch, but I can't understand what is the problem (in code there is a generic function that overrides operator<< for enums and it works properly with loggers and std streams, but fails when tested with Catch):
```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
enum class en
{
    vala,
    valb,
    valc
};
template <class S>
S& operator<<(S& stream, en e)
{
    return stream << static_cast<int>(e);
}
TEST_CASE("test", "[test]")
{
    en x = en::vala;
    REQUIRE(x == en::vala);
}
```
In VS 2015 I get the error

> error C2440: 'return': cannot convert from 'std::basic_ostream<char,std::char_traits<char>>' to 'std::ostringstream &'
  e:\code\libs\catch\include\internal\catch_tostring.h(150): note: see reference to function template instantiation 'S &operator <<<std::ostringstream>(S &,en)' being compiled
          with
          [
              S=std::ostringstream
          ]

**Comment by lightmare** [comment]
Your template declaration says it would return `S&`, reference to the same type it received; but when given `std::ostringstream&` (or any other `std::ostream` derived object, for that matter), the expression in your operator uses `std::ostream& operator<<(ostream&, int)`, i.e. it returns `std::ostream&`

The correct way to overload stream output operator is:
```c++
std::ostream& operator<< (std::ostream& os, en e)
{
    return os << static_cast<int>(e);
}
```

**Comment by nabijaczleweli** [comment]
Very good point

**Comment by MojaveWastelander** [comment]
_**en**_ is an enum class so it is not implicitly converted to int so why it will choose `std::ostream& operator<<(std::ostream&, int)` over more suitable version? The problem is that I overloaded stream operators for any enum types like this (actually I need it only for file streams, but is not essential):
```c++
template <class S, class E>
typename std::enable_if<std::is_enum<E>::value, S&>::type operator<<(S& stream, E f)
{
    return stream << static_cast<int>(f);
}

template <class S, class E>
typename std::enable_if<std::is_enum<E>::value, E >::type& operator>>(S& stream, E& mode)
{
    int m;
    stream >> m;
    return (mode = static_cast<E>(m));
}
```
and as I specified it works with all streams and loggers that use streams, Catch don't compare expressions as enums, but convert them to strings (using stringstreams) and then compare them as strings (even with C++11 enums define it works the same way). Right now I just cast boolean operations with enums to bool and it works:
```c++
        REQUIRE((bool)(Test() == Enum::en_val));
```

**Comment by lightmare** [comment]
> en is an enum class so it is not implicitly converted to int so why it will choose std::ostream& operator<<(std::ostream&, int) over more suitable version?

It does not *choose*, your operator function template *requests* `int` output:
```c++
    // this line calls std::ostream& operator<<(std::ostream& os, int);
    return stream << static_cast<int>(f);
```

Standard output operator templates have parameters `<CharType, TraitsType>` but not `StreamType`. They all take and return `std::basic_ostream<CharType, TraitsType>&`. Custom operators should do exactly the same, or if you're lazy like me, write them only for `std::ostream&` and not care about `wchar_t` and such.

> it works with all streams

No it doesn't. The reason you might think it works is because you probably use it like this:
```c++
somestream << "a = " << en::vala; // this accidentally works
somestream << en::vala; // this won't compile
```
The first line seems to work because it's equivalent to `((somestream << "a = ") << a)`.
`(somestream << "a =")` returns `std::ostream&` no matter what the type of `somestream` is (as long as it's derived from `std::ostream&`), so your operator template substitutes `S=std::ostream` and compiles fine. But it won't compile when `S` is a derived stream type (which happens on the second line).

**Comment by MojaveWastelander** [comment]
I did some tests and it works when used directly (it doesn't work with file streams though):
```c++
        std::cout << Options::en_ExtractMode::ExtractInSingleFile;
```
and the call stack

> Tests.exe!std::basic_ostream<char,std::char_traits<char> >::operator<<(int _Val)
Tests.exe!operator<<<std::basic_ostream<char,std::char_traits<char> >,enum Options::en_ExtractMode>(std::basic_ostream<char,std::char_traits<char> > & stream, Options::en_ExtractMode f)

```c++
        Options::en_ExtractMode x;
        std::cin >> x;
```
call stack

> Tests.exe!std::basic_istream<char,std::char_traits<char> >::operator>>(int & _Val)
Tests.exe!operator>><std::basic_istream<char,std::char_traits<char> >,enum Options::en_ExtractMode>(std::basic_istream<char,std::char_traits<char> > & stream, Options::en_ExtractMode & mode)

I use this with boost::property_tree to store/load settings and it works there in the same way. Anyway, thanks for explanations.
