### ISSUE TITLE
identifier "assert" is undefined

### ISSUE THREAD

**Issue by eyalsk** [philsquared/Catch#599]
I'm using Catch v1.3.4 with Visual Studio 2015.

The compiler reports that assert is undefined 9 times.

I tried to use v1.3.3 too but it happens there too so I just added the include to the top, probably _wrong_ thing to do but at least it works.

**Comment by nabijaczleweli** [comment]
Have you included `<cassert>` for `assert()`?
Post a minimal code example that reproduces your problem.

**Comment by eyalsk** [comment]
Funny but I fired Visual Studio again and it works! I don't know what happened.

I'll close the issue for now until I'll be able to reproduce it.
