### ISSUE TITLE
Do not use exit() when detecting duplicate test names

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#608]
Slightly related to #472, I find it very difficult to detect when Catch is failing when it calls `exit()` internally. Example:

```
    void enforceNoDuplicateTestCases( std::vector<TestCase> const& functions ) {
        std::set<TestCase> seenFunctions;
        for( std::vector<TestCase>::const_iterator it = functions.begin(), itEnd = functions.end();
            it != itEnd;
            ++it ) {
            std::pair<std::set<TestCase>::const_iterator, bool> prev = seenFunctions.insert( *it );
            if( !prev.second ){
                Catch::cerr()
                << Colour( Colour::Red )
                << "error: TEST_CASE( \"" << it->name << "\" ) already defined.\n"
                << "\tFirst seen at " << prev.first->getTestCaseInfo().lineInfo << "\n"
                << "\tRedefined at " << it->getTestCaseInfo().lineInfo << std::endl;
                exit(1);
            }
        }
    }
```

Note the usage of `exit(1)` above. Instead of that, can you throw an exception? On Windows development, my console window disappears immediately when this happens. Whereas in Visual Studio I can tell my program to stop (auto-breakpoint) when an exception is thrown. I can also set a break point after executing `Catch::Session().run(argc, argv)` if you exit normally.

**Comment by kirbyfan64** [comment]
Why not just set a breakpoint at the `exit` function?

**Comment by rcdailey** [comment]
@kirbyfan64 I think maybe you're misunderstanding. I'm not saying it's impossible to break when duplicates are detected. I've got issues with *how* it's done.

Using `exit()` is unpredictable and difficult to diagnose its point of invocation. I had to grep the code base to find this instance. It's very difficult to maintain a set of breakpoints all over the place to intercept `exit()` calls. Using exceptions here would be far superior. it allows a single point of contact. For example, those that choose to define and control their own `main()` could have an opportunity to handle these exceptions.

This is a design issue that, IMHO, needs to be addressed for the long-term. I'll probably work on this since @philsquared seems pretty swamped right now. Open to feedback on design.

**Comment by kirbyfan64** [comment]
...I meant in the actual exit function, not where it's called (like `break exit` in gdb or [this](http://stackoverflow.com/a/2617724/2097780)) in VS.

I agree with you on the issues of `exit`; I'm just saying that there's a workaround. :)

**Comment by sldr** [comment]
Yes, please embrace exceptions! No more printf(stdXXX, ...) and exit() (or in this case cXXX << "stuff"; exit(); ).

My $0.02 worth.

For great info on exceptions see the three part videos at [Exception-Safe Coding in C++](http://exceptionsafecode.com/).

Thanks,
SLDR
(Stephen L. De Rudder)

**Comment by horenmar** [comment]
I did some digging and apparently this was changed for the `develop-v2` branch, but that branch is currently quite obsolete. It will probably have to be reimplemented as the code has diverged quite a bit, but it should get into master at some point in relatively near future.

**Comment by philsquared** [comment]
In fact @rcdailey's PR was merged at some point and is on master.
So, unless I'm missing anything (and someone points it out) I think this issue can be close?

**Comment by horenmar** [comment]
@philsquared There are still 2 places that call directly `exit(1)`, `enforceNotReservedTag` and `RegistrarForTagAliases`'s constructor.

**Comment by philsquared** [comment]
Fair point. They should probably be changed too - although they are not named in this issue (possibly raise another one?)

**Comment by rcdailey** [comment]
I agree that another issue should be opened that refers to this one

**Comment by horenmar** [comment]
I created new issues for the other 2 callsites, so I am going to close this one.
