### ISSUE TITLE
How Approx handle INF

### ISSUE THREAD

**Issue by DarwinSenior** [philsquared/Catch#612]
So, I have a question regarding to `Approx(INF)`, it seems that `REQUIRE(Approx(INF) == INF)` is false if I use `float INF = std::numeric_limits<float>::infinity()`.

here is what I got

```
/Users/DarwinSenior/Desktop/cs419/tracer2/test/misc.cc:13: FAILED:
  REQUIRE( INF == Approx(INF) )
with expansion:
  inff == Approx( inf )
```

And my test case file

``` cpp
#include "catch.hpp"
#include <iostream>
#include <limits>

using namespace std;

namespace{
    float INF = std::numeric_limits<float>::infinity();

}

TEST_CASE("MISC", "[MISC]"){
    REQUIRE(INF == Approx(INF));
}

```

So, is there any way I could use `Approx` along with `INF`?

**Comment by lightmare** [comment]
Mathematically, `Approx(inf)` doesn't make sense. No finite number is "close enough" to infinity.

If you want to check that `x` is so large that adding something to it would overflow, resulting in `+infinity`, there's `std::numeric_limits<float>::max()`.
```c++
CHECK(x >= std::numeric_limits<float>::max())
```

It's probably safe to use `Approx` with float max (not with double max, as that might overflow in `operator==(double, Approx)`). Although I still don't see the point, `Approx` is intended to check that calculation results are within a margin of error; not that they're (close to) overflowing.

**Comment by horenmar** [comment]
Why exactly do you want to have Approx of infinity?

**Comment by DarwinSenior** [comment]
That was long time ago for the course project when I decided to write test case for ray tracing. Using infinity for the the parallel cases. I will close this issue.

**Comment by horenmar** [comment]
Ok. I am not categorically opposed to making Approx infinity aware (although it would most likely start as "hey, don't do that" error on construction), but I wanted to know the motivation to do so.
