### ISSUE TITLE
force color output

### ISSUE THREAD

**Issue by agauniyal** [philsquared/Catch#619]
while using meson build system, I discovered that it captures the test output and shows them afterwards. Since `catch` would find it as non-terminal, it will print a non-colored output. See here - https://github.com/mesonbuild/meson/issues/425. Is there any flag or some way to force coloured output?

**Comment by nabijaczleweli** [comment]
See https://github.com/philsquared/Catch/issues/590#issuecomment-188404016

**Comment by agauniyal** [comment]
@nabijaczleweli did this change made it into new release? or still in development.

**Comment by nabijaczleweli** [comment]
It's in

**Comment by philsquared** [comment]
Sorry, yes, I didn't update that issue to say it had been pushed, but it did go in:

https://github.com/philsquared/Catch/commit/8ccb18daa9c380c35ae4d13751e2a1aeed905815
