### ISSUE TITLE
CHECK expression is hitting a static assert

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#621]
I have the following piece of code in a test case:

```
   auto mismatch_pair = std::mismatch(expected_result.begin(), expected_result.end(),
      DeliveryWidget::s_widgetNames.begin());

   CHECK(
      mismatch_pair.first == expected_result.end() &&
      mismatch_pair.second == DeliveryWidget::s_widgetNames.begin());
```

The errors I get:

> error C2027: use of undefined type 'Catch::STATIC_ASSERT_Expression_Too_Complex_Please_Rewrite_As_Binary_Comparison'

I tried wrapping the two binary expressions utilizing `==` in parenthesis, this did not help. What am I supposed to do here? There is nothing in the documentation regarding this.

**Comment by kirbyfan64** [comment]
What about just separating them:

```c++
CHECK(mismatch_pair.first == expected_result.end());
CHECK(mismatch_pair.second == DeliveryWidget::s_widgetNames.begin());
```

It would have the same effect at run-time anyway. The expression is "too complex" because of the `&&`.

**Comment by ev-mp** [comment]
Had the same issue in my code with:REQUIRE(  A ==B) && (C==D)) - reporting '..to complex'..Then additional parentheses and explicit '==true' condition worked for me :REQUIRE( true ==  ((A ==B) && (C==D)) )

 

    On Wednesday, March 23, 2016 8:32 PM, Ryan Gonzalez <notifications@github.com> wrote:
 

 What about just separating them:CHECK(mismatch_pair.first == expected_result.end());
CHECK(mismatch_pair.second == DeliveryWidget::s_widgetNames.begin());It would have the same effect at run-time anyway. The expression is "too complex" because of the &&.—

**Comment by rcdailey** [comment]
I'm fine doing that. I'd just like to learn more about why that expression won't work in one `CHECK` macro. There is nothing in the documentation to help me understand this.

**Comment by philsquared** [comment]
Good point. I should add something to the docs about that.
It is, indeed, the `&&` (`||` would have the same effect).
For `&&` @kirbyfan64's approach seems best.
`||` is a little trickier, but is seldom useful.

The reason for this limitation is that Catch decomposes the expression, then must reconstruct it so it can evaluate whether it was successful or not. While it is decomposed it can capture the values of the LHS and RHS of the expression for reporting purposes. If you introduce`&&` (or `||`) into the expression it is no longer a simple, binary, expression. Splitting the expression up (@kirbyfan64's approach), or wrapping in parentheses (thereby losing the LHS/ RHS reporting capability) are the usual ways to deal with it.

**Comment by rcdailey** [comment]
Maybe this could be solved with a new type of assertion macro (variable arguments):

```
CHECK_AND(a == b, c == d);
CHECK_OR(e != f, g != h, x == z);
```

Another thought is to create `AND` and `OR` macros, but those would conflict too easy and is probably not the best approach:

```
CHECK(a == b AND c == d);
CHECK(e != f OR g != h OR x == z);
```

Just some food for thought.

**Comment by kirbyfan64** [comment]
@rcdaily The problem with the first one is that it would be too easy to use accidentally:

```c++
CHECK(myfunc<int, int>() == 1); // Oops!
```

**Comment by tamboril** [comment]
Note you can always apply [DeMorgan's Law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) to convert an _OR_ to an _AND_ so you can split it as mentioned above:

Instead of:
 `CHECK(a == 1 || b == 2)`,
 do:
 `CHECK_FALSE(a != 1);`
`CHECK_FALSE(b != 2);`

**Comment by mattfbacon** [comment]
@tamboril, this doesn't work. According to <https://github.com/catchorg/Catch2/blob/devel/docs/assertions.md>, the correct resolution is to put the expression in parentheses:

```cpp
CHECK((a == 1 || b == 2));
```

**Comment by tamboril** [comment]
Thanks for the (belated) update!

**Comment by BeriPeric** [comment]
Thank you so much for this. I wrapped mine and it worked. I have literally spent hours on this stupid issue. I tried using the equal function to compare objects and it didn't work and then I tried using '==' didn't work. Then I tried '&&' didn't work. I even tried making my own method for equals with override, which didn't work and it hurt my brain.
