### ISSUE TITLE
INTERNAL_CHECK_THAT evaluates argument twice

### ISSUE THREAD

**Issue by TorstenRobitzki** [philsquared/Catch#642]
Hi,
is there a chance to change INTERNAL_CHECK_THAT, so that the expression to be tested is evaluated only once. It's a little bit counter intuitive to have the argument evaluated twice.

```
REQUIRE_THAT( f(), check_f );
```

Will call f() two times and if f() is not Idempotent, we have to write:

```
const auto x = f();
REQUIRE_THAT( x, check_f );
```

kind regards,
Torsten

**Comment by horenmar** [comment]
This is no longer true. When I try this against Catch v1.8.1:
```cpp
int cnt = 0;

std::string foo() {
    ++cnt;
    return "aaa";
}

TEST_CASE("Double eval") {
    REQUIRE_THAT(foo(), Catch::EndsWith("a"));
    std::cout << cnt << '\n';
}
```
it prints out 1. Not sure at which point it was fixed, but the matchers were recently completely reworked, so...
