### ISSUE TITLE
Possible to avoid use of RTTI?

### ISSUE THREAD

**Issue by judgeaxl** [philsquared/Catch#648]
After 1.2.1, the new section tracker uses dynamic_cast, which requires RTTI, something my project cannot use, for various reasons. Is it a conscious decision to require RTTI, or is it simply not a use case you have considered?

I didn't look to closely at the code yet to find if there was an easy way to avoid the dynamic_cast. If I decide I really want the new features, I'll take a look and offer a pull-request.

**Comment by philsquared** [comment]
I actually hadn't realised there wasn't use of `dynamic_cast` already. Looking back at the code I don't think it would be too hard to avoid their use (three cases of movement within a small, fixed, hierarchy - only one of them speculative).

I'll try and get those out in the near future.

**Comment by judgeaxl** [comment]
Much appreciated! Catch has turned out to be my favorite C++ testing framework over the last year.

**Comment by philsquared** [comment]
Cool. I've been meaning to look at this for some time (there are a few other issues and PRs relating to it).

**Comment by philsquared** [comment]
In fact this is done now. Please see 1.5.1!

**Comment by judgeaxl** [comment]
Now that's one sweet turnaround time! Works like a charm! Thanks!
