### ISSUE TITLE
"No tests ran" error

### ISSUE THREAD

**Issue by amigo421** [philsquared/Catch#654]
didn't use catch for a long time but now built a project (it uses auto update from github) and faced with an issue which was not there earlier . my test executable doesn't perform the output for auto parsing. I tried to run this manually and got the log below. not sure that it is a error, probably I'm somewhere wrong...
result of 
tests.exe -l
.....
  Backward sorted sequence
      [MergeSort][Sequental][Unit]
33 test cases

I tried a few cases , just for sure, 
please explain what I'm doing wrong? 

C:\dev\workspace\build\algolist\BuildTools_x64\Default\tests>tests.exe MergeSort
===============================================================================
No tests ran

C:\dev\workspace\build\algolist\BuildTools_x64\Default\tests>tests.exe "MergeSort"
===============================================================================
No tests ran

C:\dev\workspace\build\algolist\BuildTools_x64\Default\tests>tests.exe "Backward sorted sequence"
===============================================================================
No tests ran

**Comment by nabijaczleweli** [comment]
Have you tried running tests?

**Comment by amigo421** [comment]
do you mean without parameters? run all ones? yes, successfully.

**Comment by philsquared** [comment]
Sorry. This was a regression introduced by recent changes to Clara (the spun-out command line parser).
I've fixed the issue in Clara and imported it into Catch. v1.5.2 now includes this fix.

**Comment by amigo421** [comment]
thanks a lot!
