### ISSUE TITLE
MSVC Warning C4800 now shows up for pointers

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#657]
Prior to upgrading to v1.5.3, this code generated no warnings (MSVC 2015, `/W3` in use):

    void* some_pointer = nullptr;
    REQUIRE(some_pointer);

Now this generates a warning:

> warning C4800: 'void *': forcing value to bool 'true' or 'false' (performance warning)

Normal comparisons of pointers in boolean context such as `if` conditions are valid and do not normally generate warnings in MSVC.

I recommend either setting up Catch to do a `#pragma warning(disable)` on these OR change the code to make the warning go away.

**Comment by philsquared** [comment]
That's odd. Which version (of Catch) are you upgrading from?

**Comment by rcdailey** [comment]
From this version:

```
Catch v1.3.3
Generated: 2016-01-22 07:51:36.661106
```

**Comment by philsquared** [comment]
[This looks like most likely candidate](https://github.com/philsquared/Catch/commit/ffad3a0a39812083e56d5b083eeb45e1559c5a88)

I wonder if `!!(expr)` would solve both problems?

**Comment by rcdailey** [comment]
I just verified that works:

    static_cast<bool>(!!(expr))

**Comment by rcdailey** [comment]
I did a little sample that shows how `operator!` and `operator bool` are used in the `!!(expr)` case; looks like it won't require the `operator!` (as long as you have a typecast operator for `bool`) but will use it if it exists.

http://coliru.stacked-crooked.com/a/b89cb270243169f3

**Comment by philsquared** [comment]
Thanks. Yes - as I was trying to say in a reply that never got though (connection on the train!) I'm fairly confident in this approach and have pushed a commit with it in (which you've probably seen by now).
Thanks for raising this.
