### ISSUE TITLE
Issue when customize the main function of Catch with Eclipse on Windows with MinGW

### ISSUE THREAD

**Issue by p4535992** [philsquared/Catch#667]
Hi, i write all my test with succes by usin the default generating main function of catch:
File main.cpp (work)
```c++
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"
```
If's work fine, but now i need to customize the main function so i follow the documentation on this [link](https://github.com/philsquared/Catch/blob/master/docs/own-main.md), but eclipse show a error it's say "_Type 'Catch::Session' could not be resolved_"
Here the new main.cpp (not work)
```c++
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

int main( int argc, char* const argv[] )
{
	  Catch::Session session; // There must be exactly once instance
	  int returnCode = session.applyCommandLine( argc, argv );
	  if( returnCode != 0 )return returnCode;
	  return session.run();
}
```
The error change in "_Function 'Session' could not be resolved_" on the following example:
```c++
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

int main( int argc, char* const argv[] )
{
	int result = Catch::Session().run( argc, argv );
    return result;
}
```
I put a link to a image for make easy to see the errors [image](http://s6.postimg.org/oog31s0pt/eclipse_erorr_4.png)

**Comment by ianmacs** [comment]
The eclipse CDT parser is notorious for finding errors in valid code. You will still be able to compile the code. The issue is cosmetic and can be fixed in the eclipse CDT settings.

This is not a bug in Catch. This issue can be closed.

**Comment by p4535992** [comment]
K sorry for the misunderstanding.
Greetings.
