### ISSUE TITLE
What is the proposed way to test a try block?

### ISSUE THREAD

**Issue by dpservis** [philsquared/Catch#671]
REQUIRE_NOTHROW is a great way to work with exceptions but what if I want to test a larger block where there may be several calls that throw, e.g.

try
{
// Make a lot of things here
}
catch(...)
{
    FAIL("an exception was thrown");
}

**Comment by Darelbi** [comment]
bool exception = false;
    try{
        //...
    }catch(...){
        exception = true;
    }
    REQUIRE(exception == false);

**Comment by milleniumbug** [comment]
I use

```
REQUIRE_NOTHROW([&]()
{
	// your code
}());
```

**Comment by lightmare** [comment]
> REQUIRE_NOTHROW is a great way to work with exceptions but what if I want to test a larger block where there may be several calls that throw

Why would you want to hide which of those calls threw? I mean, wouldn't it be better to REQUIRE_NOTHROW each of them, so that when something fails, you know where the trouble is, instead of just "somewhere in this block"?

**Comment by milleniumbug** [comment]
@lightmare What if you want to test declarations? They aren't expressions.

**Comment by lightmare** [comment]
@milleniumbug How about SECTION?

**Comment by dpservis** [comment]
Hi all

thanks for the answers, my main motivation for this are throwing constructors of classes without default constructors and then using these to make other objects/calls etc.

**Comment by dpservis** [comment]
@milleniumbug good idea if using C++11

**Comment by lightmare** [comment]
@milleniumbug You need to wrap the anonymous function in parentheses, otherwise it will suffer the same problem with commas as a plain block:
```c++
REQUIRE_NOTHROW(
{
    // if there is a comma outside parentheses, it won't even pass preprocessing
    std::pair<int, int> nono;
});

REQUIRE_NOTHROW(([&]
{
    std::pair<int, int> ok;
})());
```

@dpservis You can do that with sections:
```c++
SECTION("foo and bar with some input")
{
    ThrowingFoo foo("input");
    ThrowingBar bar(foo, "more input");
    REQUIRE(bar.isValid());
    REQUIRE_NOTHROW(bar.doStuff());
    // etc.
}
```
If a constructor throws, it terminates the section and you get exactly as much information as you'd get from REQUIRE_NOTHROW with a block, i.e. only line number of the start of the section/block and exception.what();

**Comment by dpservis** [comment]
@milleniumbug great!

**Comment by philsquared** [comment]
Although the lambda suggestion works (assuming C++11 on) I don't think it adds much value in this case.
Any uncaught exceptions that escape the test case are reported as failures anyway. The advantage of using `REQUIRE_NOTHROW` explicitly is that (a) you better document your intent that this really should be a non-throwing operation and (b) you get file/ line information that pinpoints the responsible call. Once you use a multiline lambda with many potentially throwing sites you start to lose those advantages (increasingly so the larger the block).

So I would recommend either use `REQUIRE_NOTHROW` on each line that you want to be specific about - or just relax and let Catch, well,... catch, your exceptions outside the test case.

Either way I'm going to close this issue now as I think it's been resolved in one of several ways.
