### ISSUE TITLE
Parallel test running

### ISSUE THREAD

**Issue by mg262** [philsquared/Catch#681]
I have some slow tests that need to be run before every commit. Waiting for them to run is slowing down development a lot. Is there any way of running tests in parallel with Catch, similar to gradle's maxParallelForks setting for Tests?

**Comment by deeringc** [comment]
My team would also benefit from this greatly. Would be very nice to be able to add support for a -j n command line option.

**Comment by ruipacheco** [comment]
+1

**Comment by kkutsner** [comment]
+1
