### ISSUE TITLE
CHECK_NOTHROW with expression gives warning

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#682]
I tried doing this:

    CHECK_NOTHROW(myobject.IsValid() == false);

I wanted to verify 2 things:

1. The return value is `false`
1. The function `IsValid()` will not throw

However, MSVC gives the warning:

> warning C4553: '==': operator has no effect; did you intend '='?

I can resolve the warning by breaking it out into two checks:

```
CHECK_NOTHROW(myobject.IsValid());
CHECK(myobject.IsValid() == false);
```

What are the limitations on the provided expression for `CHECK_NOTHROW` compared to `CHECK`?

**Comment by vpashka** [comment]
>> The return value is false 
 CHECK_FALSE(...)  ?

**Comment by philsquared** [comment]
`CHECK_NOTHROW()` is for when you *just* want to check that a *statement* does not throw.
`CHECK()` and `REQUIRE()` already trap and report on exceptions - so based on what you've said you just need:
`CHECK(myobject.IsValid() == false );`

**Comment by rcdailey** [comment]
So just that I'm clear on this: `CHECK` effectively validates no thrown exception along with the expression? In other words, an exception thrown is treated as an assertion failure?

Then that means really `CHECK_NOTHROW` is for expressions that do not yield boolean values, such as wrapping it around a function call that returns `void`?

Thanks for clarifying.

**Comment by philsquared** [comment]
That's close enough, yes.
If I'm going to be pedantic I'd say `CHECK_NOTHROW` is for constructs you want to treat as *statements* (which don't return anything, or you don't care what they return), whereas `CHECK` evaluates an expression in a boolean context to determine success/ failure. Both catch exceptions and treat them as failures.
If you want to verify that an exception is thrown then use one of the `_THROWS_` variants.
I'll look at making that clearer in the docs - thanks!

**Comment by rcdailey** [comment]
I guess what threw me off is the parameter for `CHECK_NOTHROW` is named `expr`, instead of `stmt` or something, so I figured any expression would be acceptable.

Again thanks for explaining.
