### ISSUE TITLE
User defined reporter extending XmlReporter hindered by private members

### ISSUE THREAD

**Issue by robfywa** [philsquared/Catch#683]
An easy way to extend XmlReporter with additional info would be to inherit from the XmlReporter class, allowing use of e.g. its m_xml member. But these members are private rather than protected which makes them unusable from the derived class. 

It seems changing them from private to protected would enable easy extension of the reporter classes without any major downsides, since they would still not be publicly exposed.

**Comment by philsquared** [comment]
Thanks for the feedback. I'll take a look and consider this. 
OTTOMH: one possible downside is that it increases the scope for Fragile Base Class issues. It's possible the benefits outweigh the risks, though (or maybe other changes can be made to keep things more stable - e.g. protected method accessors).

For Catch2 I'm looking at reworking the reporter framework (yes, again, sorry) to make it more composable to start with.
