### ISSUE TITLE
Bug in generated XML for Fatal Error Condition in XmlReporter

### ISSUE THREAD

**Issue by robfywa** [philsquared/Catch#685]
For a Fatal Error Condition (e.g. SIGSEGV), the XmlReporter will generate an XML tag

```
<Fatal Error Condition>
...
</Fatal Error Condition>
```

There should not be a space in the tag name.. (against specification, or at least causes errors in XML parsers such as pythons inbuilt XML parser). The fix is to change the generated tag name in assertionEnded() to:                   

m_xml.scopedElement( "FatalErrorCondition" )

**Comment by philsquared** [comment]
Ouch! Not sure how that one slipped by! Thanks.
I'll try and get to this soon.

**Comment by philsquared** [comment]
(although do bear in mind that trying to complete a valid xml document in the face of a SIGSEGV is purely on a "best effort" basis - so even with the tag name fixed it may still have other problems).

**Comment by philsquared** [comment]
Where by "get to this soon" I mean in a few months, obviously :-s
Sorry about that. Simple enough fix but I've been swamped.
I've just committed the fix in locally and it should appear here on the next push.
