### ISSUE TITLE
approval tests need to be run in compiler-independent order

### ISSUE THREAD

**Issue by lightmare** [philsquared/Catch#687]
`approvalTests.py` should run `SelfTest` with `--order=lex` so that it works consistently across compilers.

The default `--order=decl` runs tests in initialization order, which, for a single translation unit, is determined by the order of definitions. But the order in which variables from different translation units are initialized is _indeterminate_.

**Comment by philsquared** [comment]
Good call.
I've only ever run those tests on my own Mac (and I didn't think anyone else really ran them), so not caught this before.
I might look in to a partial ordering by filename for "decl".
At the very least I'll change the approval tests to use "lex".
Thanks for pointing this out!

**Comment by horenmar** [comment]
This has been implemented in 79acc0504bf62020eefbb305c948718328aebade so I am going to close this.
