### ISSUE TITLE
Is there a way to execute tests by filename?

### ISSUE THREAD

**Issue by razeh** [philsquared/Catch#689]
I would like to be able to execute tests by filename, so that within my editor (emacs), I can run catch for the file I'm editing.

Are there any builtin ways to do this?

**Comment by dmcardle** [comment]
Your test program will accept command-line arguments and options that might help you (See `./test -h`).  

The high-level usage is defined as `test [<test name, pattern or tags> ...] [options]`.


### Example

    /* test.cpp */
    #include "catch.hpp"

    TEST_CASE("MyClass", "[tag]") {
        SECTION("firstTest") {
            /* ... */
        }
        /* ... */
    }

When you execute `./test MyClass`, all the sections of that test case will run.

**Comment by philsquared** [comment]
If you run Catch with -# it automatically tags all test cases in a file with the filename stem (ie the filename with no directory or extension). So if you have tests in the file, `AllMyTests.cpp` (in the executable MyTestExe) you should be able to run them with:

`MyTestExe -# [#AllMyTests]`

See: https://github.com/philsquared/Catch/blob/master/docs/test-cases-and-sections.md#special-tags
And also: http://www.levelofindirection.com/journal/2015/7/8/a-game-of-tag.html (under the section "Filenames As Tags")
