### ISSUE TITLE
Execute test only if a condition is true

### ISSUE THREAD

**Issue by paolobolzoni** [philsquared/Catch#693]
I am writing an algorithm that explores a graph to do stuff and I use catch for testing. The REQUIRE macro appears inside a loop and I need to test only is the exploration is in well known nodes.

At the moment I use the ternary operator:
```
REQUIRE(good_node(node) ? node.value1 == expectedvalue1  : true);
```
And it works fine, however since you cannot overload the ternary operator the message in case of failure looks like: "false" expected "true" instead of the usual nice output.

So my question is, what is the correct approach in this case? Perhaps catch should support conditional tests?

**Comment by rioderelfte** [comment]
You could simply use an `if`:

```c++
if (good_node(node)) {
    REQUIRE(node.value1 == expectedvalue1);
}
```

**Comment by paolobolzoni** [comment]
I was really missing the obvious. Thanks.
