### ISSUE TITLE
wrong catch.hpp included?

### ISSUE THREAD

**Issue by agauniyal** [philsquared/Catch#694]
Can someone confirm that the file being included here - https://github.com/philsquared/Catch/blob/master/docs/build-systems.md#cmake

```
ExternalProject_Get_Property(catch source_dir)
set(CATCH_INCLUDE_DIR ${source_dir}/include CACHE INTERNAL "Path to include folder for Catch")
```

is the right one? Shouldn't it be the single header inside `single_include` instead?

**Comment by OMGtechy** [comment]
Pretty sure you're right, so I made https://github.com/philsquared/Catch/pull/779

**Comment by lightmare** [comment]
`single_include/catch.hpp` is not always up to date, i.e. between tagged releases.

**Comment by horenmar** [comment]
I am not quite sure about this one, but its probably right.

While `single_include` is only updated on tagged releases, that also means its much better for external consumption. On the other hand, if someone wants to refer to current master, then it should refer to `include`, so...

**Comment by horenmar** [comment]
After some discussion, we decided that steering people to take latest tagged release as a dependency is better idea than steering them to ToT, so #779 is in.
