### ISSUE TITLE
Clipboard issue

### ISSUE THREAD

**Issue by sharifahmad2061** [philsquared/Catch#695]
I would like to point out an issue to you people. I guess that may have happened to many people. When you click the download link for the one file headerFile of Catch it would open a separate tab in which there is like 10000 lines of code and you copy it and paste it in a file and then include that file in your project and all of sudden you see a lot of errors in project build. Well i guess what happens is that your clipboard memory might not be able to hold that 10000 lines and so the OS might do something else and might mess up with your code. But if within the same project you include the catch.hpp from the downloaded repository of catch, the errors goes away and everything will be fine then.
So kindly let people directly download the file not copy and paste it.
Kindly let me know if I'm right or wrong.

**Comment by nabijaczleweli** [comment]
lol what

**Comment by philsquared** [comment]
@sharifahmad2061 there's a link at the top of the readme file (available on the main page of the repo) that lets you download it directly.

**Comment by horenmar** [comment]
Your browser automatically opens plaintext files, because it thinks it would be useful for you. If you don't want it to do so, right click the link and select save as.
