### ISSUE TITLE
Document commandline option -#, --filenames-as-tags 

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#696]
Issue #689 mentions option --filenames-as-tags  (-#). It should be documented in section [Command line](https://github.com/philsquared/Catch/blob/master/docs/command-line.md).

**Comment by horenmar** [comment]
ATM it is documented (albeit not in detail). Do you have something more in mind?

**Comment by philsquared** [comment]
I think I only added it a couple of weeks ago
