### ISSUE TITLE
Providing a hook for custom logging

### ISSUE THREAD

**Issue by dutow** [philsquared/Catch#698]
I have a library/application with an extensive internal logging system, which helps in understanding failing tests when I can easily identify which test case which log messages belongs to.

Currently I see two options to inject test case information into my logs:
- Disable coloring and default stdout, and redirect catch messages into my log (or into my log and std out)
- Include catch with prefixed macros and provide my own non-prefixed macros for logging the parameters before calling the original macros

I think both are hacks and limited in what they can do (the first requires disabled colors, the latter requires custom messages based on the macro parameters ; by default catch only outputs only failing test cases limiting the first version even more).

It would be great if catch supported this functionality in a built in way, e.g. by checking a define for an additional logger stream.

**Comment by blueskyjunkie** [comment]
Here's how I solved this problem:

* My application uses Dependency Injection for distributing a "MessageLogManager" around the application.
* My logging framework has the concept of Sink where log messages are directed and the Sink can be custom implemented.
* The MessageLogManager is abstract virtual and has concrete children to implement a specific type of log relating to the log framework (rotating log, etc).
* For tests where I just don't want logging in relation to Catch tests I use a NullLogManager to hand into classes such that any log messages generated in the application test go nowhere.
* For tests where I might want logs as a useful part of Catch tests I use a InfoLogManager with a custom Sink that redirects log messages to the Catch INFO macro. This way for passing tests the log messages never appear, but when tests fail, any log messages generated appear as part of the test diagnostic per Catch test output.

Hope this helps.

**Comment by philsquared** [comment]
Catch has the concept of a "listener" which should allow you to do what you want much more cleanly.
I've not had a chance to properly document it yet (so sorry you've done a lot of possibly unnecessary work to workaround it) - but please see this thread for the details you should need: https://github.com/philsquared/Catch/issues/475

**Comment by dutow** [comment]
@philsquared  Thank you, that's exactly what I'm looking for, unfortunately, I didn't check the closed tickets.

@blueskyjunkie While that solution would work, and I do use DI for other parts of my application, I don't think that adding an additional abstraction around logging just to support a better output for unit tests is justified.

**Comment by philsquared** [comment]
@dutow "unfortunately, I didn't check the closed tickets." - and I wouldn't expect you to. I should have documented it. I'll try and fix that when I get back from holiday

**Comment by blueskyjunkie** [comment]
@dutow Fair enough. I had the abstraction anyway so it was almost trivial to extend it to unit tests.

**Comment by philsquared** [comment]
(re-opening until Listeners are documented)

**Comment by philsquared** [comment]
Listeners are now documented :-)

https://github.com/philsquared/Catch/blob/master/docs/event-listeners.md
