### ISSUE TITLE
Show trace on run

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [philsquared/Catch#700]
Hi, i don't find any information on how to show this message when writing test with "Scenario, given, then''.
Thanks for your help!

"Conveniently, these tests will be reported as follows when run: Scenario: vectors can be sized and resized"

**Comment by philsquared** [comment]
Sorry I didn't catch this when you first raised it.
In case you're still waiting for an answer, I suspect what's happening is all your tests are passing so you're not seeing any output by default.
If you run with `-s` on the command line it will print successful results too.

**Comment by horenmar** [comment]
Since there has been no further inquiry in ~3 months, I am going to close this.
