### ISSUE TITLE
Unit test memory issues

### ISSUE THREAD

**Issue by FlYnN91** [philsquared/Catch#708]
Hi,

I am getting to grips with Catch by trying to write a Circular buffer and unit tests for it. It all compiles and the .exe is generated correctly. When I run it, I get error: 
```
FAILED: due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```
I suspect this has something to do with 

```
Buffer_Response Buffer_Init(Circular_Buff *cb, U16 item_size, U16 item_count)
{
    U8 response = BUFFER_OK;

    cb->max_buffer_size = item_size * item_count;
    cb->buffer = (U32 *)malloc(item_size * item_count); <--- THIS LINE
    cb->buffer_end = (U8 *)cb->buffer + (cb->max_buffer_size);
    cb->item_count = item_count;
    cb->current_index = 0;
    cb->current_index = 0;
    cb->head = cb->buffer;
    cb->tail = cb->buffer;
    cb->item_size = item_size;

    return (response);
}
```

This is my test 
```
TEST_CASE("Initialise Circular Buffer", "[buffer]" ) {

    U16 dummy_item_size = 8;
    U16 dummy_item_count = 1;
    Circular_Buff *buffer = 0;
    Buffer_Response response;

    response = Buffer_Init(buffer,dummy_item_size,dummy_item_count);

    REQUIRE(response == BUFFER_OK);
}
```

I suspect the .exe asks Windows for 8 bytes of memory and the OS goes "nope - crash". Is there a way around this where Catch or the Unit test can ask for memory?
Thanks

**Comment by lightmare** [comment]
This is not an issue with Catch, but your code ;)

You haven't allocated memory for `Circular_Buffer *buffer`. ` cb->anything = something;` dereferences a null pointer and tries to write into a structure at address 0.

**Comment by FlYnN91** [comment]
Oh wow, that's embarrassing. Holding my head in shame. Thank you for the comment.
