### ISSUE TITLE
Assert macros doesn't support template arguments

### ISSUE THREAD

**Issue by abbradar** [philsquared/Catch#709]
For example,
```
		REQUIRE(run_test<test_1_1_pub_t, decltype(process_pub)>(process_pub));
```
will give you an error (on Clang 3.8.0):
```
src/test_client.cpp:182:36: error: too many arguments provided to function-like macro invocation
                REQUIRE(run_test<test_1_1_pub_t, decltype(process_pub)>(process_pub));
                                                 ^
```

The problem is described [here](http://stackoverflow.com/questions/4295890/trouble-with-template-parameters-used-in-macros). One solution is to use `__VA_ARGS__` internally everywhere instead of one `expr` argument. I'm not sure how viable this is.

P.S. I've misclicked when creating an issue, sorry.

**Comment by abbradar** [comment]
Workaround:
```
#define REQUIRE_VA(...) \
	({																						\
		auto f = [&]() { return (__VA_ARGS__); };		\
		REQUIRE(f());																\
	})
```

**Comment by abbradar** [comment]
Another workaround, but notice backwards incompatible arguments swap:
```
#define REQUIRE_THROWS_AS_VA(type, ...)					\
	({																						\
		auto f = [&]() { return (__VA_ARGS__); };		\
		REQUIRE_THROWS_AS(f(), type);								\
	})
```
If we want to fix this with backwards compatibility then we unfortunately need to leave `REQUIRE_THROWS_AS` and other more-than-one-argument macros as is (at least I don't see any other way).

**Comment by nabijaczleweli** [comment]
How about 
```cpp
REQUIRE((run_test<test_1_1_pub_t, decltype(process_pub)>(process_pub)));
```
or
```cpp
REQUIRE((run_test<test_1_1_pub_t, decltype(process_pub)>)(process_pub));
```
?

**Comment by abbradar** [comment]
Ugh, I feel stupid -- I haven't thought that it would work. Thanks!

**Comment by nabijaczleweli** [comment]
Parens save lives
