### ISSUE TITLE
Test names starting with # are ignored when using -f

### ISSUE THREAD

**Issue by philsquared** [philsquared/Catch#717]
`-f` allows a file to be specified containing test names (one per line) to execute (usually the result of `--list-test-names-only`).
But it recognises the `#` character as the start of a comment, so any test names beginning with `#` are skipped.

Probably the best way to work around this is to support quoted test names (as on the command line) and have `--list-test-names-only` quote all test names, or at least those starting with `#`

**Comment by philsquared** [comment]
This was raised in response to: https://youtrack.jetbrains.com/issue/RSCPP-13702

**Comment by lightmare** [comment]
IMO this is over-complicating it. Why even have comments in a list file to begin with? There's no point. If you look at how common utilities like `xargs`, `grep -f`, `diff -X` handle list files, they're just that: no special syntax, just raw strings, one per line.

**Comment by philsquared** [comment]
Good question!

Personally I found it very useful when I have some unexpected interaction between tests. I generate the list, using `--list-test-names-only`, then selectively enable tests in and out using `#` until I find the culprit.

**Comment by lightmare** [comment]
For that use case, you can use any other character or string that doesn't occur in test names, without Catch parsing it -- it won't match any test name and ignore that line.

**Comment by philsquared** [comment]
Did you have a character in mind?
I didn't think `#` would be common (it's not something I've ever used at the start of a test name) - but it is very common as a comment character.

**Comment by lightmare** [comment]
That's irrelevant. If someone has test names starting with `#`, they can use `%`. If they have test names starting with all kinds of weird characters, they can use `DON'T RUN THIS`. For example having test cases `first` and `second` and passing this file to -f:
```
first
SKIP second
```
Catch will run only `first`.
