### ISSUE TITLE
CTest integration

### ISSUE THREAD

**Issue by amigo421** [philsquared/Catch#719]
This is a feature request.
I see , in docs, piece of cmake script for the getting this from github.
however would be nice to have the script (cmake) for automatically adding CATCH scripts to CTest.
to make a single fully workable script which clones the Catch, scan the project for the tests and adds CTest target. 
There is a few scripts , somewhere in github which do this, I'm using this ability from time to time , 
would be perfect to have such module in Catch distribution, your opinion?

**Comment by horenmar** [comment]
Not against it, but I admit I don't want to do this myself.

**Comment by amigo421** [comment]
okay, I'll review which I'm using one, 
if this will look okay for a publishing , I'll create PR
