### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by Mikaka27** [philsquared/Catch#721]
Hi, is it possible to release this library as a nuget package?

**Comment by kirbyfan64** [comment]
Wait, I thought nuget was a .NET thing... Do people put C++ libraries there now?

Package management these days, I swear...

**Comment by Mikaka27** [comment]
Yes, for example boost library is there for the taking.

**Comment by kirbyfan64** [comment]
Well, Boost is pretty big, but Catch is basically just one header file. Is it really worth it, rather than just popping it in your project?

```
$ curl -L -O catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
```

**Comment by Mikaka27** [comment]
Well, it's not a problem, but I guess it wouldn't hurt also having it on nuget :)
Just asking, not my decision anyway.

**Comment by ZaldronGG** [comment]
These days I suppose Catch should be released via [vcpkg](https://github.com/Microsoft/vcpkg)

**Comment by ras0219-msft** [comment]
It has been added to `vcpkg`: https://github.com/Microsoft/vcpkg/pull/195

**Comment by philsquared** [comment]
Sorry, I didn't see this the first time around - only once it was closed.
We don't need to re-open it, but I just had a question: I presume this means the vcpkg entry will need to be kept updated?
Do you know what's involved in that? Is it just a case of updating the catch file(s) in the repo, there, along with an update to the version field?
I'm thinking this is something that can probably be automated (I'm trying to streamline the release process here_.

**Comment by mKlus** [comment]
+1
Would like to see Catch in vcpkg updated regularly.

Not sure what it takes to get it updated but looking at this commit it seems quite simple
https://github.com/Microsoft/vcpkg/commit/7c89415a6f4ee418e912744fb2a519f62c22f163

**Comment by ras0219-msft** [comment]
@philsquared Updates should be as simple as submitting a PR to bump the version field and change the download URL.

We definitely are interested in improving automation down the road -- automatically picking up package updates, testing them, then making them available. However, that's not available quite yet, so the above is as simple as it can be for now :).

**Comment by horenmar** [comment]
@ras0219-msft I am working on a script that would make the PR as a part of an update.

Its annoying, but not that hard, what I'd really like to see is the ability to publish more versions side by side, so users can keep an older version if the new one broke them.

**Comment by dvirtz** [comment]
@horenmar please see if you can also make the script issue a PR for [Hunter](https://github.com/ruslo/hunter) package at https://github.com/hunter-packages/Catch

**Comment by Mikaka27** [comment]
Hi, I'm new to github so I'm not sure if you need me to reopen this or can someone else do it (if it's needed of course).
If only I can do it please let me know if you want it.

**Comment by ras0219-msft** [comment]
@horenmar We do have exactly that, courtesy of Git [1]. Every version that has ever been published through Vcpkg will be forever available.

https://github.com/Microsoft/vcpkg/blob/master/docs/FAQ.md#how-do-i-use-different-versions-of-a-library-on-one-machine

**Comment by mwpowellhtx** [comment]
Running into a possible project, and I have discovered this may be possible. I think that is incredible, and frankly, long overdue IMO.

**Comment by ras0219-msft** [comment]
Because Catch is available via vcpkg, you can use vcpkg to make a NuGet package:
```
vcpkg install catch2 catch2:x64-windows
vcpkg export --nuget catch2 catch2:x64-windows
```

**Comment by mwpowellhtx** [comment]
@ras0219-msft Is `vcpkg` available "out of the box"? Or is it another standalone toolchain analog to `nuget.exe`?

**Comment by ras0219-msft** [comment]
https://github.com/Microsoft/vcpkg#getting-started will always be updated with the current best way to get vcpkg; as of right now, it is a standalone toolchain similar to nuget.exe.

**Comment by mwpowellhtx** [comment]
@ras0219-msft Also, not really a `catch` issue per se, but what I really like to see, if possible, is to leverage `<PackageReference />` in _directory build properties_, same as we can do today for awhile now in _CSharp dotnet_ projects. I think of cases where I have the same cross-cutting dependencies, i.e. multiple test projects, that sort of thing, and I want to make the reference _"only one time"_.
