### ISSUE TITLE
One empty test crashes the app

### ISSUE THREAD

**Issue by amigo421** [philsquared/Catch#724]
catch crashed at runtime, if this compiled with /RTC1 /RTCc compiler options

**Comment by nabijaczleweli** [comment]
Full source code, full compilation command, compiler version, Catch version?

**Comment by amigo421** [comment]
catch version - latest, autoclone from git at build stage
compiler - v19.00.24310
CXX_FLAGS = /Zi /EHsc /W4 /cgthreads4 /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1 /RTCc

#define CATCH_CONFIG_MAIN
#include <catch.hpp>

namespace testing {

TEST_CASE( "Test1", "[unit]" ) {
}

**Comment by krvajalmiguelangel** [comment]
In Windows it works just fine for me without the **/RTCc** flag.

**Comment by horenmar** [comment]
Could not reproduce this bug with current version of Catch.

**Comment by amigo421** [comment]
no changes in latest version of Catch - it still does have this problem.
judt checked

**Comment by amigo421** [comment]
![image](https://cloud.githubusercontent.com/assets/3259933/21741696/61d30302-d4ef-11e6-8c76-7ab2b9e3444d.png)

**Comment by amigo421** [comment]
you see MS even suggest the solution to mask the issue if the reducing of size  is really required

**Comment by horenmar** [comment]
This is weird, my email notifications tell me there are new posts here, but I don't see them. Anyway, apparently its still there, I just hadn't managed to turn on the RTCc flag properly.

**Comment by amigo421** [comment]
yes, I still see the problem, if you look at VC runtime exception popup you can see even the suggestion how to solve the issue, just the reducing the size forcely

**Comment by horenmar** [comment]
I am going to need some convincing that this is actually inside Catch, because the picture shows error in VS 2015 `<streambuf>`, at line 255, which is `*_IGcount = (int)(_Last - _Next);` in this function
```cpp
	void __CLR_OR_THIS_CALL setg(_Elem *_First, _Elem *_Next, _Elem *_Last)
		{	// set pointers for read buffer
		*_IGfirst = _First;
		*_IGnext = _Next;
		*_IGcount = (int)(_Last - _Next);
		}
```
This cast can discard some information (although it seems quite unlikely), by going from `ptrdiff_t`, which is 64bits on x64 arch, to `int` which remains 32bits. The cast happens as a part of `setg` standard operation and should have nothing to do with us.

Also I am still unable to reproduce with VS2015 Update 3, /RTCc enabled
```cpp
#define _ALLOW_RTCc_IN_STL
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

namespace testing {

TEST_CASE("Test1", "[unit]") {
}
}
```

```
*  Catch v1.5.8
*  Generated: 2017-01-07 12:34:30.379000
Visual Studio Version 14.0.25431.01 Update 3
19.00.24215.1
```

**Comment by nabijaczleweli** [comment]
FWIW I can't repro with Catch v1.5.9 and g++ 6.2.0.

**Comment by amigo421** [comment]
I'll re-check this today
