### ISSUE TITLE
Creating temporary object with space in class name (unsigned int) within REQUIRE() parsing error

### ISSUE THREAD

**Issue by jamespharvey20** [philsquared/Catch#732]
I don't know if this is an easy, hard, or impossible fix.  There's an easy workaround, but I tend to make a bug report whenever I run into something.  This is of course a reduced test case, otherwise pointless.  `i` takes the place of a function being tested.

    #define CATCH_CONFIG_MAIN
    #include <catch.hpp>
    TEST_CASE("") {
       unsigned int i = 0;
       REQUIRE(unsigned int { 0 } == i);
    }

Gives

    In file included from catchUnsigned.cpp:2:0:
    catchUnsigned.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____13()’:
    catchUnsigned.cpp:22:12: error: expected primary-expression before ‘unsigned’
        REQUIRE(unsigned int { 0 } == i);
                ^
    catchUnsigned.cpp:22:12: error: expected ‘)’ before ‘unsigned’
    catchUnsigned.cpp:22:12: error: expected primary-expression before ‘unsigned’
        REQUIRE(unsigned int { 0 } == i);
                    ^
    catchUnsigned.cpp:22:12: error: expected ‘)’ before ‘unsigned’
    catchUnsigned.cpp:22:4: error: expected ‘;’ before ‘)’ token
        REQUIRE(unsigned int { 0 } == i);
        ^
    catchUnsigned.cpp:22:4: error: expected primary-expression before ‘)’ token

The same happens for `signed int`.  I'm thinking the space in the variable type is what's causing it.  Using `int` or a fixed-width `uint32_t` works fine.

Easiest workaround to stick with `unsigned int` is:

    #define CATCH_CONFIG_MAIN
    #include <catch.hpp>
    using uint = unsigned int;
    TEST_CASE("") {
       uint i = 0;
       REQUIRE(uint { 0 } == i);
    }

Could of course define the expected value, then compare against it instead of a temporary, also.

**Comment by lightmare** [comment]
This is not an issue with catch. `unsigned int { 0 }` is not legal C++. Wrap the multi-word type in parentheses: `(unsigned int) { 0 }`.

**Comment by jamespharvey20** [comment]
Huh.  You're right, sorry about that!

`int {0}` is legal c++11, but `unsigned int {0}` even in an `if` statement without involving catch at all gives the same type of error.  Weird!
