### ISSUE TITLE
cppcheck: out of bound access to string

### ISSUE THREAD

**Issue by steohan** [philsquared/Catch#733]
While checking with cppcheck I found an out of bound access to a string in the catch header: [catch.hpp:4151](https://github.com/philsquared/Catch/blob/88732e85b2ac0233bba6fec5c032d02f9c5c230b/single_include/catch.hpp#L4150-L4151)

It should be 

``` c++
for( std::size_t i = 0; i < arg.size(); ++i )
```

instead of 

``` c++
for( std::size_t i = 0; i <= arg.size(); ++i )
```

, shouldn't it?

**Comment by lightmare** [comment]
Yes, there's also a pending PR #660 fixing it.

**Comment by horenmar** [comment]
This has been fixed in Clara (which is an external dependency), closing the issue.
