### ISSUE TITLE
Not able to build c++ .exe in visual studio 2012 with CATCH

### ISSUE THREAD

**Issue by pareshdp** [philsquared/Catch#739]
Hi,

I am new to CATCH framework and wanted to build a simple windows console application to run a simple test.

I had created a win 32 console app in visual studio and added catch.hpp in my project from /single_include directory available on net. My code looks like below - 

// MyApp.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "catch.hpp"

int _tmain(int argc, _TCHAR* argv[])
{
	return 0;
}
int add (int a,int b)
{
	return a*b;
}

TEST_CASE()
{
	REQUIRE(add(1,2) == 3);
}

But when I try to build I get linker errors as below - 

1>------ Build started: Project: MyApp, Configuration: Debug Win32 ------
1>  MyApp.cpp
1>MyApp.obj : error LNK2019: unresolved external symbol "public: __thiscall Catch::SourceLineInfo::SourceLineInfo(char const *,unsigned int)" (??0SourceLineInfo@Catch@@QAE@PBDI@Z) referenced in function "void __cdecl `anonymous namespace'::`dynamic initializer for 'autoRegistrar17''(void)" (??__EautoRegistrar17@?A0xde0545bc@@YAXXZ)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: __thiscall Catch::AutoReg::AutoReg(void (__cdecl*)(void),struct Catch::SourceLineInfo const &,struct Catch::NameAndDesc const &)" (??0AutoReg@Catch@@QAE@P6AXXZABUSourceLineInfo@1@ABUNameAndDesc@1@@Z) referenced in function "void __cdecl `anonymous namespace'::`dynamic initializer for 'autoRegistrar17''(void)" (??__EautoRegistrar17@?A0xde0545bc@@YAXXZ)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: __thiscall Catch::AutoReg::~AutoReg(void)" (??1AutoReg@Catch@@QAE@XZ) referenced in function "void __cdecl `anonymous namespace'::`dynamic atexit destructor for 'autoRegistrar17''(void)" (??__FautoRegistrar17@?A0xde0545bc@@YAXXZ)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: __thiscall Catch::ResultBuilder::ResultBuilder(char const *,struct Catch::SourceLineInfo const &,char const *,enum Catch::ResultDisposition::Flags,char const *)" (??0ResultBuilder@Catch@@QAE@PBDABUSourceLineInfo@1@0W4Flags@ResultDisposition@1@0@Z) referenced in function "void __cdecl ____C_A_T_C_H____T_E_S_T____17(void)" (?____C_A_T_C_H____T_E_S_T____17@@YAXXZ)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: class Catch::ResultBuilder & __thiscall Catch::ResultBuilder::setResultType(bool)" (?setResultType@ResultBuilder@Catch@@QAEAAV12@_N@Z) referenced in function "private: class Catch::ResultBuilder & __thiscall Catch::ExpressionLhs<int const &>::captureExpression<0,int>(int const &)" (??$captureExpression@$0A@H@?$ExpressionLhs@ABH@Catch@@AAEAAVResultBuilder@1@ABH@Z)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: class Catch::ResultBuilder & __thiscall Catch::ResultBuilder::setLhs(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?setLhs@ResultBuilder@Catch@@QAEAAV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "private: class Catch::ResultBuilder & __thiscall Catch::ExpressionLhs<int const &>::captureExpression<0,int>(int const &)" (??$captureExpression@$0A@H@?$ExpressionLhs@ABH@Catch@@AAEAAVResultBuilder@1@ABH@Z)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: class Catch::ResultBuilder & __thiscall Catch::ResultBuilder::setRhs(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?setRhs@ResultBuilder@Catch@@QAEAAV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "private: class Catch::ResultBuilder & __thiscall Catch::ExpressionLhs<int const &>::captureExpression<0,int>(int const &)" (??$captureExpression@$0A@H@?$ExpressionLhs@ABH@Catch@@AAEAAVResultBuilder@1@ABH@Z)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: class Catch::ResultBuilder & __thiscall Catch::ResultBuilder::setOp(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?setOp@ResultBuilder@Catch@@QAEAAV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "private: class Catch::ResultBuilder & __thiscall Catch::ExpressionLhs<int const &>::captureExpression<0,int>(int const &)" (??$captureExpression@$0A@H@?$ExpressionLhs@ABH@Catch@@AAEAAVResultBuilder@1@ABH@Z)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: void __thiscall Catch::ResultBuilder::endExpression(void)" (?endExpression@ResultBuilder@Catch@@QAEXXZ) referenced in function "void __cdecl ____C_A_T_C_H____T_E_S_T____17(void)" (?____C_A_T_C_H____T_E_S_T____17@@YAXXZ)
1>MyApp.obj : error LNK2019: unresolved external symbol "public: void __thiscall Catch::ResultBuilder::useActiveException(enum Catch::ResultDisposition::Flags)" (?useActiveException@ResultBuilder@Catch@@QAEXW4Flags@ResultDisposition@2@@Z) referenced in function __catch$?____C_A_T_C_H____T_E_S_T____17@@YAXXZ$0
1>MyApp.obj : error LNK2019: unresolved external symbol "public: void __thiscall Catch::ResultBuilder::react(void)" (?react@ResultBuilder@Catch@@QAEXXZ) referenced in function __catch$?____C_A_T_C_H____T_E_S_T____17@@YAXXZ$0
1>MyApp.obj : error LNK2019: unresolved external symbol "public: bool __thiscall Catch::ResultBuilder::shouldDebugBreak(void)const " (?shouldDebugBreak@ResultBuilder@Catch@@QBE_NXZ) referenced in function __catch$?____C_A_T_C_H____T_E_S_T____17@@YAXXZ$0
1>MyApp.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Catch::toString(int)" (?toString@Catch@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) referenced in function "private: class Catch::ResultBuilder & __thiscall Catch::ExpressionLhs<int const &>::captureExpression<0,int>(int const &)" (??$captureExpression@$0A@H@?$ExpressionLhs@ABH@Catch@@AAEAAVResultBuilder@1@ABH@Z)
1>MyApp.obj : error LNK2019: unresolved external symbol "bool __cdecl Catch::isDebuggerActive(void)" (?isDebuggerActive@Catch@@YA_NXZ) referenced in function __catch$?____C_A_T_C_H____T_E_S_T____17@@YAXXZ$0
1>c:\users\mohini\documents\visual studio 2012\Projects\MyApp\Debug\MyApp.exe : fatal error LNK1120: 14 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Could anyone please help me to resolve this ? am I doing something wrong here? appreciate quick help on this.

**Comment by martinmoene** [comment]
Perhaps start with an [example](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#writing-tests) given in the Catch documentation?

**Comment by pareshdp** [comment]
Hi Martin,

I tried the same example which was shared by Phil in his video (on Youtube) with simple add function.

Could you please help me to understand how to resolve these linker errors ?

Thanks in advance.

-Regds,
Paresh

**Comment by onqtam** [comment]
I think you need to implement the test runner somewhere - do this IN EXACTLY ONE SOURCE FILE:

```
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"
```

and then in your ```_tmain``` do this: ```return Catch::Session().run( argc, argv );```

Also make sure to have read the documentation.

**Comment by pareshdp** [comment]
Finally it worked..Below is the modified code. Thanks a ton onqtam :) !! Really appreciate your help..
Was struggling with these errors... Will try more features from CATCH and let you know if any help needed.

// MyApp.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <conio.h>
#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

int main( int argc, char* const argv[] )
{
  // global setup...

  int result = Catch::Session().run( argc, argv );

  // global clean-up...
  _getch();
  //return result;
}

int add(int a,int b)
{
	return a+b;
}

TEST_CASE("My First Test case","Test case1")
{
	REQUIRE(3 == add(1,2));
}
