### ISSUE TITLE
compilation errors using C++11 enums and clang

### ISSUE THREAD

**Issue by onqtam** [philsquared/Catch#742]
The following code compiles fine with gcc and errors with clang:

```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

enum A : bool {
    Yup = true,
    Nop = false,
};

TEST_CASE("") {
    REQUIRE(A::Yup == A::Nop);
}
```

here are links to an online compiler:
- [clang](http://melpon.org/wandbox/permlink/FF225w6tpGgAgbRj)
- [gcc](http://melpon.org/wandbox/permlink/FLeJDFj2Yilhy05T)

Any idea why? The problem seems to be in the stringification and the ```operator<<``` detection trait

actually the same issue can be reproduced with [doctest](https://github.com/onqtam/doctest)

**Comment by kirbyfan64** [comment]
FWIW, the issue here seems to stem from the use of typed enums via `: bool`; without that, this compiles.

**Comment by onqtam** [comment]
this seems to be [a clang issue](http://stackoverflow.com/a/40504951/3162383)
