### ISSUE TITLE
Add a brief progress output

### ISSUE THREAD

**Issue by nlohmann** [philsquared/Catch#744]
For [JSON for Modern C++](http://www.github.com/nlohmann/json) I am heavily using Catch for the unit tests. Right now, we are close to 10 million assertions and everything is fine.

However, the test suite may take quite a while to build, and it would be nice to have some progress output, e.g. including the number of executed/remaining test cases. This would not only help to assess whether it makes sense to wait for the tests to complete, but it can also allow to execute a test suite in the first place: continuous integration services like AppVeyor will cancel builds if they do not create any output for 10 minutes.

Any thoughts on this?

**Comment by philsquared** [comment]
That's a nice set of tests!

When you say "take quite a while to build" it sounds like you mean compile time - but your query about a progress bar suggests runtime - so do you mean the running of the tests?

If the latter then it's certainly possible - and something I've thought about from time to time.
The best part is that it can be done orthogonally to Catch itself - it would just be another reporter (you could take the console reporter as a starting point - or even extend it.

Although It's something I might get around to at some point I'm currently running very behind on other issues and PRs, as well as other ongoing development - so I can't promise it would be any time soon. So it may make more sense for you to have a stab at it yourself (there's an interface you need to implement, and a macro to register it - just have a look at the existing reporters for examples (sorry it's not currently documented).

**Comment by nlohmann** [comment]
Oh, my wording was bad: I meant the runtime of the tests, not the build time. (The build time is something I have to look into, but it is not the issue here).

I have not looked into writing a reporter. I may check it out - but maybe I help myself with some `printf` calls in the moment :)

Thanks again for the great library!

**Comment by horenmar** [comment]
This is a job for custom reporter, or just hacking in some local changes to your favourite Catch's reporter (not that I would condone such a thing of course 😄), but probably not worth making a specific reporter that is bundled with the single-include header.

**Comment by allanleal** [comment]
Has there been any progress on this? I see the issue above has been marked as resolved, but it is not clear how to enable progress output (like pytest, for example) while the tests/assertions are executed.

**Comment by horenmar** [comment]
> This is a job for custom reporter, or just hacking in some local changes to your favourite Catch's reporter

**Comment by chrysante** [comment]
Sorry for necromancing this, but I tried to implement a progress reporter and it worked okay, but I have one problem: Is there any way I can get the total number of test cases being run _before_ they are run? Right now I inherit from `StreamingReporterBase` and print a dot for every incoming test case. This helps, but it would be nicer if I could count the number of run tests and divide by the number of total tests to print a progress bar.
