### ISSUE TITLE
The XML header is always written to the console and not the output file

### ISSUE THREAD

**Issue by gerikintercede** [philsquared/Catch#745]
Found in 1.5.8

Ran test:

>     Tests.exe -r xml -o test.xml
>     <?xml version="1.1a" encoding="UTF-8"?>
> 

The xml header is sent to the console and is not present in the output file.
This fix to catch_reporter_xml.hpp fixes it:

```
     public:
         XmlReporter( ReporterConfig const& _config )
         :   StreamingReporterBase( _config ),
-            m_sectionDepth( 0 )
+            m_sectionDepth( 0 ),
+            m_xml( _config.stream() )
         {
             m_reporterPrefs.shouldRedirectStdOut = true;
         }

```
This was caused by "Fixes for XML encoding. #701"

**Comment by horenmar** [comment]
Oops, duplicated report for this without noticing. (issue #750)

The given fix would trigger `-Wreorder` warnings though, because m_xml is second member in the `XmlReporter`.

**Comment by PureAbstract** [comment]
> The given fix would trigger -Wreorder warnings though, because m_xml is second member in the XmlReporter.

`-Wreorder` is always worth fixing - since there's no cost to doing so, and it's surprising how many people don't understand order of initialisation.

It's easily solved though - just correct the order of the initialisers:
```
  +            m_xml( _config.stream() ),
  +            m_sectionDepth( 0 )
```

**Comment by philsquared** [comment]
Thanks.
I've accepted #751 on the basis that it's already in the right order.
