### ISSUE TITLE
XML reporter writes encoding line to stdout, even if -o is specified

### ISSUE THREAD

**Issue by horenmar** [philsquared/Catch#750]
I was testing another issue and fix when I came across the fact that if I run catch binary as `small.exe -r xml -o test` then the xml writer writes the line `<?xml version="1.1" encoding="UTF-8"?>` to stdout, even though it should be written to file `test`.

This is caused by `XmlReporter` improperly initializing `XmlWriter`.

PR coming soon.

**Comment by philsquared** [comment]
Thanks for raising this - and for the PR (#751) which I've now accepted.
I'm not sure how it got that way in the first place - must have been a refactoring artefact at some point!
