### ISSUE TITLE
Is there a way to implement inheritance with Catch?

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#758]
I have a class that can be instantiated in a number of ways and to test it I end up copy/pasting the same tests over and over. If this was a OO framework I'd implement an abstract class and specialisations for each set of configuration parameters. Is there a way to go around this with Catch?

**Comment by lightmare** [comment]
You can put common tests in a function and call it on each instance:

```c++
void run_common_checks(C& x) {
   REQUIRE(x.is_ok());
   ...
}

TEST_CASE("default-constructed") {
    C x;
    run_common_checks(x);
}

TEST_CASE("constructed from string") {
    C x("hello dolly");
    run_common_checks(x);
}
...
```

**Comment by Bu11etmagnet** [comment]
Seems to me Catch needs something similar to gtest's parametrized tests.

**Comment by philsquared** [comment]
Right now @lightmare's suggestion is pretty sound.
The plan is to integrate a data generators system, which is somewhat similar to the parameterised tests that @Bu11etmagnet mentions - but also the basis for property based testing.
While I've done a lot of preparatory work on that it's currently deferred to the upcoming Catch2 version.

**Comment by ruipacheco** [comment]
when do you think Catch 2 will be released?

**Comment by philsquared** [comment]
Closing this as I believe the question has been answered (at least for now).
Feel free to re-open if you feel there is more to it.
