### ISSUE TITLE
Time to test

### ISSUE THREAD

**Issue by samaursa** [philsquared/Catch#76]
It would be great if I could get information on how long it took to test. Some control over it would be nice as well (via command line arguments) where the default might be to display the total time it took to test and command line arguments allow me enable timers for specific tests (something like <b>-time "_"</b> for all and <b>-time "Core_"</b> for all tests that fall under Core).

**Comment by horenmar** [comment]
This has gotten into Catch under `-d yes` command line argument in the meantime (over 4 years, wow). Note that it is not a benchmark but rather just a "time taken" log.

Closing because it is solved and the issue backlog needs to be cleared. :-)
