### ISSUE TITLE
Failing on purpose

### ISSUE THREAD

**Issue by semmel** [philsquared/Catch#765]
Sometimes I find it useful to let a test fail deliberately. 
For this matter I discovered the `FAIL` macro digging around in `catch.hpp`.
Nice! :+1: 

However `FAIL` - like `REQUIRE` - aborts the execution of the local scope.
I needed something like `FAIL` but in the flavor of `CHECK`:
```cpp
#define FAIL_CHECK( ... ) INTERNAL_CATCH_MSG( Catch::ResultWas::ExplicitFailure, Catch::ResultDisposition::ContinueOnFailure, "FAIL", __VA_ARGS__ )
``` 

Is that macro future-proof? I.e is `FAIL` part of Catch' public API?
`INTERNAL_CATCH_MSG` is certainly not meant to be used be clients, or is it? 

Now I can let the test fail deliberately e.g. from inside a timeout callback which has previously crashed using `FAIL`
Example with Reactive Extensions for C++:
```cpp
auto sequence = rxcpp::observable<>::interval(std::chrono::milliseconds(100));
sequence
.take(2)
.timeout(std::chrono::milliseconds(50))
.subscribe([](int value)
{
	CHECK(value == 1);
},
[](std::exception_ptr exPtr)
{
	try
	{
		std::rethrow_exception(exPtr);
	} 
	catch (const rxcpp::timeout_error&)
	{
		FAIL_CHECK("expected timeout failure");
	}
});
```

**Comment by philsquared** [comment]
You're right to be suspicious of using anything that starts with `INTERNAL_`.
In practice that's been stable for a long time.
But in this case this feature probably makes sense in the framework itself. I'll try and get it added soon.

**Comment by philsquared** [comment]
That's in now on master (but not the single include).
I'm going to mark this issue for closure soon.

**Comment by semmel** [comment]
Great! 👍 
Thanks!

**Comment by horenmar** [comment]
This is in the latest release, so I am going to close the issue.
