### ISSUE TITLE
Travis CI doesn't run tests under C++11/14

### ISSUE THREAD

**Issue by horenmar** [philsquared/Catch#771]
Travis CI should also run tests with C++11/14 enabled, not just with whatever the default language standard setting is.

**Comment by jjcamp** [comment]
This is a travis issue, but you're likely using the default build VM, which uses compiler without c++11 support.

If you want c++11, check the [Travis docs on using ubuntu trusty](https://docs.travis-ci.com/user/trusty-ci-environment/).

If you want c++14, that's more work.  I know I've seen stackoverflow answers on it so I would check there.

**Comment by horenmar** [comment]
@jjcamp There are two parts of the issue

1) Build VM configuration. I am fairly sure this is ok as it is now, because we are test compiling with Clang up to 3.8, but it will have to be checked anyway.
2) Set up build configs so that C++11 and C++98 are both built. Right now we built C++98 and only 98, but there might be bugs lurking in our conditional use of C++11 features, so it should be tested as well.


Also I don't know enough about Travis to make this a quick fix, so this is a kind of a post-it note for later, when I have time to read through the docs. Or maybe someone will see this and think "I know how to do that" before I get around to it.

**Comment by horenmar** [comment]
Travis now compiles Catch with C++11 under g++ 4.8, g++ 6 and clang++ 3.8.
