### ISSUE TITLE
Catch 1.5.9 Klocwork errors

### ISSUE THREAD

**Issue by miikka75** [philsquared/Catch#776]
Please verify if following errors from KW static analysis on catch.hpp v1.5.9 are valid:

--------------------------------------
Operands in a bitwise operation have different size
8529            clearBuffer |= (*it)->assertionEnded( assertionStats );

CWARN.BITOP.SIZE
Operands of different size in bitwise operation
The CWARN.BITOP.SIZE checker looks for code in which bitwise operations (&=, |=, and ^=) have operands with different sizes. Both operands of a bitwise operation must normally be either 32-bit or 64-bit values, although the checker won't flag a 64-bit mask used on a 32-bit value.

Vulnerability and risk
When an unsigned 32-bit value is converted to a 64-bit type, the 32 higher bits are set to zero, which probably isn't the original design intent and can cause unexpected results.

--------------------------------------
Pointer 'listed.nullableValue' returned from call to function 'Option<unsigned long int>' at line 6413 may be NULL and may be dereferenced at line 6414.

6413                if( Option<std::size_t> listed = list( config() ) )
6414                    return static_cast<int>( *listed );

NPD.FUNC.MIGHT
Possible null pointer may be dereferenced
An attempt to access data using a null pointer causes a runtime error. When a program dereferences a pointer that is expected to be valid but turns out to be null, a null pointer dereference occurs. Null-pointer dereference defects often occur due to ineffective error handling or race conditions, and typically cause abnormal program termination. Before a pointer is dereferenced in C/C++ code, it must be checked to confirm that it is not equal to null.

The NPD checkers look for instances in which a null or possibly null pointer is dereferenced.

The NPD.FUNC.MIGHT checker flags situations in which a pointer value from a function call that might return null might subsequently be dereferenced explicitly or passed to a function that dereferences it without checking it for null.

Vulnerability and risk
Null-pointer dereferences usually result in the failure of the process. These issues typically occur due to ineffective exception handling.

**Comment by lightmare** [comment]
> 8529 clearBuffer |= (*it)->assertionEnded( assertionStats );

`bool& |= bool` is fine, no information is lost.

> 6413 if( Optionstd::size_t listed = list( config() ) )
> 6414 return static_cast( *listed );

This will only dereference if the pointer is non-NULL, the warning is spurious.

**Comment by horenmar** [comment]
The first one is perfectly OK, even if weird, the second one is also a false positive (the if guards the dereference and the dereference can happen only iff the pointer is nonnull).
