### ISSUE TITLE
Cannot execute tests by name if they contain , or [ characters

### ISSUE THREAD

**Issue by philsquared** [philsquared/Catch#777]
While parsing test specs `,` and `[` have special meanings (`,` starts an alternate name or tag, '[' starts a tag).

e.g.

`./SelfTest "std::pair<int,const std::string> -> toString"`

Parses to `"std::pair<int"` _or_ `"const std::string> -> toString"`

To address this an escape character is needed. `\` can be used as the escape character, and also serves to escape itself (so `\` can be represented by `\\`).

The example can then be written as:

`./SelfTest "std::pair<int\,const std::string> -> toString"`

**Comment by lightmare** [comment]
Escaping is not the best solution. You suddenly can't just copy&paste the string from source, you have to go through it, know what the metacharacters are and not miss any of them.

Better add an option to pass literal test names, and/or option to disable parsing for all arguments:
```
./SelfTest --test-this "std::pair<int,const std::string> -> toString" --test-this "another [evil] test case"
./SelfTest --dont-parse-args "std::pair<int,const std::string> -> toString" "another [evil] test case"
```

**Comment by philsquared** [comment]
I don't disagree with you - but bear in mind you couldn't copy & paste from source before, either. I think the issue is rare enough that it shouldn't be a big burden.
Also it doesn't preclude using an option-argument as well (I find it very convenient to be able to specify tests without an option currently).

In fact it might be better the other way around: Don't interpret special characters in the arg string - but provide an option-argument for the more complex cases.

I might consider that for the future. But for now escaping seems the least disruptive change to address the issue - without too much inconvenience - and I've committed that change already (in v1.6.0).

**Comment by lightmare** [comment]
> I don't disagree with you - but bear in mind you couldn't copy & paste from source before, either. I think the issue is rare enough that it shouldn't be a big burden.
> Also it doesn't preclude using an option-argument as well (I find it very convenient to be able to specify tests without an option currently).

I don't quite understand the second part, and am not sure whether it's simply because I missed something, or you misunderstood my suggestion. The fact that copy&paste doesn't work in some cases is obvious from the issue title. What I tried to say was that there's a way to make it work.

```sh
./SelfTest "this always works" "but, this, is, special"  # here copy&paste doesn't work
./SelfTest --test-this "but, this, is, special" "this always works"  # here it does
./SelfTest "this always works" "but\, this\, is\, special"  # can't like this, sorry
```

**Comment by philsquared** [comment]
That's the bit "I don't disagree with you" on :-)

But there's another way to make it work. Have the current way (a direct argument - no `-` or `--` option) work the way your `--test-this` would work, but add options for the case when you need what those special chars were giving you (and would require escaping).

e.g. something like:

`./SelfTest "this, is, normal" --spec "test1, test2, [tag]"`

**Comment by lightmare** [comment]
I see. I was only considering changes that leave currently-working behaviour as is.

**Comment by philsquared** [comment]
I'm going to close this one as my changes described above address the immediate issue.
I agree with @lightmare that it's not a perfect or complete solution and should probably be revisited at some point (perhaps for Catch2).
