### ISSUE TITLE
REQUIRE problem XCode

### ISSUE THREAD

**Issue by fegauthier** [philsquared/Catch#790]
Hi guys,

I have some errors in XCode when i want to run the test scripts.

<img width="888" alt="screen shot 2017-01-24 at 9 48 47 pm" src="https://cloud.githubusercontent.com/assets/12112673/22276033/ecb71d0e-e27e-11e6-823a-f50627955d72.png">

I don't know why i've these errors. Does some body can help me?

Thanks

**Comment by krvajalmiguelangel** [comment]
Did you added the 
``#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
``
at the top. I am asking because maybe it is not visible on the screenshot. Also can you let us know what version of XCode you are using.

**Comment by krvajalmiguelangel** [comment]
I tested in Version 8.2.1 (8C1002) of XCode  and it works just fine.

**Comment by krvajalmiguelangel** [comment]
@horenmar can you check this please?

**Comment by fegauthier** [comment]
I'm using the latest version of XCode.

I'm not able to test it now. I will test it in 2-3 hours. Thanks for your help :)

**Comment by fegauthier** [comment]
I'm using Xcode 8.2.1 too

There is my full main

<img width="1142" alt="screen shot 2017-01-26 at 4 26 15 pm" src="https://cloud.githubusercontent.com/assets/12112673/22351067/496945e8-e3e4-11e6-92f6-f49ea54dc2ab.png">

**Comment by krvajalmiguelangel** [comment]
Can you attach the full xcode project in a zip file so i can try it

**Comment by fegauthier** [comment]
[CatchTest.zip](https://github.com/philsquared/Catch/files/733655/CatchTest.zip)

There is my project. Thanks for your help

**Comment by krvajalmiguelangel** [comment]
Your project indeed does not work but mine worked with your code.

**Comment by fegauthier** [comment]
It works with your project. So it's the project configuration... I don't what i forget...

**Comment by krvajalmiguelangel** [comment]
Glad to help. As this not a catch issue will close this now.
