### ISSUE TITLE
Catch Does Weird Things when Optimizations are On

### ISSUE THREAD

**Issue by CorneliaXaos** [philsquared/Catch#792]
So.. I'm not sure if Catch was intended to run with Optimizations..  You'd think it would run just fine.. but it seems that the REQUIRE macro just breaks down for me when I ran it under my release targets..  Having any optimizations set causes REQUIRE to just fail for some reason...

EDIT: I should add that it results in the REQUIRE code causing a segfault some 15 or so stack frames in.
EDIT EDIT:  Catch's last function call is at line 8132 in the single header.. it then goes a bit into some libstdc++ calls before crashing and burning in there...  so it may or may not be Catch?

**Comment by horenmar** [comment]
Can you provide some extra information, ie stack trace, g++ version or example test file that causes the issue?

**Comment by CorneliaXaos** [comment]
Welp...  Sorry this is a week late... but...  I can no longer reproduce the bug..  I have no idea what was going on.. Sorry to have bothered you. :P
