### ISSUE TITLE
Can't clone submodule Catch

### ISSUE THREAD

**Issue by ravstrix** [philsquared/Catch#794]
$ git clone --recursive https://github.com/ravstrix/Pathway.git
Cloning into 'Pathway'...
remote: Counting objects: 118, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 118 (delta 49), reused 106 (delta 42),Rec eiving obpack-reused 0
Receiving objects: 100% (118/118), 19.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (49/49), done.
Checking connectivity... done.
Submodule 'ThirdParty/Catch' (https://github.com/philsquared/Catch) registered for path 'ThirdParty/Catch'
Cloning into 'ThirdParty/Catch'...
remote: Counting objects: 12690, done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 12690 (delta 66), reused 0 (delta 0), pack-reused 12544
Receiving objects: 100% (12690/12690), 5.77 MiB | 1.28 MiB/s, done.
Resolving deltas: 100% (7851/7851), done.
Checking connectivity... done.
fatal: reference is not a tree: 7a74088fccb48ba643d2b319503d06a99a76764c
Unable to checkout '7a74088fccb48ba643d2b319503d06a99a76764c' in submodule path 'ThirdParty/Catch'

**Comment by philsquared** [comment]
Do you have local changes to your copy of Catch?

**Comment by ravstrix** [comment]
Oh, you're right. That's my fault. I fixed the problem in my repo.

**Comment by philsquared** [comment]
Glad I could help :-)
