### ISSUE TITLE
Is it possible to run specific sections?

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#795]
I have several sections under a single test case as they're all related but I need to run the whole test case every time I want to test a specific section, which is slow, or I need to ninja comment all sections except the code I need.

Reading the docs I can only find references to running test cases. Is there the equivalent for specific sections within test cases?

**Comment by horenmar** [comment]
You are in luck, e7bcbb35c0617a679422b29e8b402928a9d5c5ae should make it possible to run specific sections now. However, you will need to either build the single-include file from master by yourself (just clone the repository, go to the `scripts` folder and run `generateSingleHeader.py`), or wait for next release (should be Wednesday).

For details see #629.

**Comment by ruipacheco** [comment]
I'll wait for Wednesday and close this ticket. Thanks!
