### ISSUE TITLE
Approx() causing Clang/CLion errors

### ISSUE THREAD

**Issue by curio77** [philsquared/Catch#801]
## Description

`Approx()` causes errors with Clang/in CLion.

### Steps to reproduce
Using something like

```c++
double d = 0.0;
REQUIRE(Approx(0.1) == d);
```

yields this error in CLion/Clang: “Error after macro substitution: Can't resolve 'endExpression'”, “Error after macro substitution: Structure type required instead of 'bool'”.

The code compiles fine with GCC.

### Extra information

* Catch version: **v1.7.0**
* Operating System: **Linux x64 (Gentoo)**
* Compiler+version: **clang v3.7.1**

**Comment by horenmar** [comment]
Can't reproduce this one on 64bit Ubuntu with clang 3.6 - 3.8, so I am going to need more information. 

What exactly does CLion/Clang mean? Clang invoked from Clion? If so, can you provide your cmakelists.txt?

**Comment by curio77** [comment]
Sorry about the confusion. I had been assuming that CLion uses Clang as its backed for static analysis, as I'd seen similar messages from both. As it turns out, however, this is wrong and indeed not a Clang issue. I'll report this with CLion instead.
