### ISSUE TITLE
Catch single-header line endings changed in 1.7

### ISSUE THREAD

**Issue by bdb** [philsquared/Catch#804]
Prior to 1.7 Catch single-header line endings were LF (Unix) now 1.7 is CRLF (Win). This caused git to loose all diff info. Easy enough to convert before commit. But why not just leave the endings as LF?

**Comment by horenmar** [comment]
Unintentional change -- Prior to about week and half ago, the download link in readme went to the raw file in repository, which is always stored with LF. This was changed to link to the file in a release, which however is not automatically converted to LF, and then the release was made on a Windows PC.

**Comment by horenmar** [comment]
New release has been made with LFs again and we (hopefully) will remember to check the generated header before uploading as part of a release.
