### ISSUE TITLE
Compilation fails on Windows with MinGW-32 GCC 5.3.0.

### ISSUE THREAD

**Issue by nyamatongwe** [philsquared/Catch#805]
## Description
The headers for MinGW-32 GCC 5.3.0. do not include gmtime_s  or SetThreadStackGuarantee and there
is no way to turn off the sections of Catch that use these.

gmtime_s is in Annex K of the C11 standard which is optional so gmtime_s is not portable. I think that gmtime  should be used instead of gmtime_s. This may require a #define to avoid compiler warnings from MSVC.
SetThreadStackGuarantee is a Win32 API so should be available in any Windows compiler but unfortunately isn't with this compiler. Other related functions like AddVectoredExceptionHandler weren't available in the previous 4.9.0 release of MinGW-32. When working with Win32 Structured Exception Handling, its fine to require a working, current version of the Windows headers and libraries. However, SEH is not important in many cases so turning off its use should be an option.

### Steps to reproduce
Here is a minimal Catch file:

~~~cpp
// Minimal catch test
#define CATCH_CONFIG_MAIN  // This tells Catch to provide a main() - only do this in one cpp file
#include "catch.hpp"
~~~

With MinGW-32 GCC 5.3.0, show the version and compile the file:

~~~
>g++ --version && g++ --std=c++11 -Wall -Wextra minimal.cxx -o minimal.exe
g++ (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

In file included from minimal.cxx:3:0:
catch.hpp: In constructor 'Catch::FatalConditionHandler::FatalConditionHandler()':
catch.hpp:6160:53: error: 'SetThreadStackGuarantee' was not declared in this scope
             SetThreadStackGuarantee(&m_guaranteeSize);
                                                     ^
catch.hpp: In member function 'void Catch::FatalConditionHandler::reset()':
catch.hpp:6167:57: error: 'SetThreadStackGuarantee' was not declared in this scope
                 SetThreadStackGuarantee(&m_guaranteeSize);
                                                         ^
In file included from minimal.cxx:3:0:
catch.hpp: In function 'std::__cxx11::string Catch::{anonymous}::getCurrentTimestamp()':
catch.hpp:9809:41: error: 'gmtime_s' was not declared in this scope
             gmtime_s(&timeInfo, &rawtime);
                                         ^
~~~

### Extra information
* Catch version: **v1.7.0**
* Operating System: **Microsoft Windows 10 Home 64-bit**
* Compiler+version: **MinGW-32 GCC 5.3.0 from mingw.org**

**Comment by horenmar** [comment]
The first one is fair, but trying to be windows compiler without supporting Win32 API  is just... ugh. SEH will end up MSVC only for now, because splitting apart the handling behind guards for various MinGW versions is probably not worth it.

As far as using `gmtime_s`, it will probably end up MSVC only as well, because I'd prefer not to disable compilation errors for people who use Catch's runner, instead of just main.

**Comment by horenmar** [comment]
Can you test the attached single-header version? It should disable SEH, unless MSVC is used to compile Catch and do the same with `gmtime_s` usage.

[catch.zip](https://github.com/philsquared/Catch/files/752262/catch.zip)

**Comment by horenmar** [comment]
@sdsahib @nyamatongwe 
The attached single header version should have SEH and `gmtime_s` as MSVC only, can you test if it works for you?
[catch.zip](https://github.com/philsquared/Catch/files/753237/catch.zip)

**Comment by sdsahib** [comment]
@horenmar Now number of errors have increased exponentially HAha.

some of them : - 
catch.hpp:7508:32: error: 'WORD' has not been declared
catch.hpp:7511:9: error: 'HANDLE' does not name a type
catch.hpp:7512:9: error: 'WORD' does not name a type
catch.hpp:7513:9: error: 'WORD' does not name a type

by the way, THanks for quick reply..

**Comment by sdsahib** [comment]
@horenmar  pls suggest me the compiler version with which it will work fine..

**Comment by horenmar** [comment]
Third time's charm, this time I actually installed MinGW to test it before-hand.

_And I found an interesting bug waiting to happen in the script used to generate single header version of Catch_

[catch.zip](https://github.com/philsquared/Catch/files/753255/catch.zip)

**Comment by sdsahib** [comment]
@horenmar  you nailed it sir 👍  👍 thanks a ton (💯) ,, 
Actually I had to explain about **unit testing in C++** in a Seminar in my university, and I have gone through each n every resource I can to fix this but unable to ,, Actually I like to talk much haha 
Thanks a 💯 Sir ,

**Comment by nyamatongwe** [comment]
This one works well with both MinGW and MSVC.
Thanks.

**Comment by mrWor1d** [comment]
Hi @horenmar,

Im having the same problem in the header file catch_reporter_junit.cpp. I tried to look at this solution but it is from an older version and doesn't apply to the current one.

![imagen](https://github.com/user-attachments/assets/f068acab-3b95-4480-b86b-86fbcc9f0a7c)

### Extra information
- Catch version: v3.7.1
- Operating System: Microsoft Windows 11 Home 64-bit
- Compiler+version: MinGW-32 GCC 14.2.0 from mingw.org
- IDE: VSCode v1.93.1
