### ISSUE TITLE
Comparison issues with ExpressionLhs

### ISSUE THREAD

**Issue by foonathan** [philsquared/Catch#809]
## Description

As of the newest Catch version something seem to have changed with the Catch ExpressionLhs comparison operators.
Previously, code worked fine, now I'm getting errors.

See for examp.e this build log here: https://travis-ci.org/foonathan/type_safe/jobs/197372853
There is an ambiguity between my optional comparison operator and the one of ExpressionLhs.

### Steps to reproduce

I couldn't reprocude the ambiguity in a minimal example, but a different related error:

```cpp
struct foo
{
    int i;
};

template <typename T>
bool operator==(const T& val, foo f)
{
    return val == f.i;
}

TEST_CASE("foo")
{
    foo f{42};
    REQUIRE(42 == f);
}
```

This gives an error: `request for member ‘endExpression’ in ‘operator==<Catch::ExpressionLhs<const int&> >(Catch::ResultBuilder::operator<=(const T&) [with T = int](42), f)’, which is of non-class type ‘bool'`

### Extra information

* Catch version: latest one from master branch
* Operating System:  Arch Linux 
* Compiler+version: clang 3.9.1

**Comment by lightmare** [comment]
You can blame this one on me. I added `const` qualifiers to `ExpressionLhs` operators, not realizing that the absence of `const` served as a disambiguator between these member operators and user-defined global operator templates that take `const` references.

**Comment by horenmar** [comment]
I removed the `const` qualifiers and tested it against type_safe master, which now compiles. Can you rerun the CI on your end?

**Comment by foonathan** [comment]
When I first noticed the error, I did fix it for one file by wrapping every check in `REQUIRE` in extra parenthesis. I reverted that now - cause I thought all issues were fixed - and rebuild CI, it fails: https://travis-ci.org/foonathan/type_safe/jobs/198969793

In `REQUIRE(optional<T>() == optional<T>())`, the ambiguity is resolved but wrong: the `operator==` called is the `operator==(const U&, optional)` (and compiler complains about `BinaryExpression` not being a boolean), not the one from Catch!

I didn't have this issue before, so there seemed to be another change.
(It could also be my fault, in which case I'll just undo the reversion of the commit fixing that)

**Comment by horenmar** [comment]
It is (was) on our end, and it should be fixed, but your pipeline won't pick it up until next release (most likely tomorrow).

Just to make sure, after I cloned your repo I did this to reproduce the error and verify that it is fixed:
```
git checkout flag_set
cmake -BBuild -H.
cd Build
make -j4
```
This triggered the compilation error. After I replaced the downloaded Catch version with one generated from current master (not the one from 1.7.0 release), the compilation finished succesfully and tests all passed.

**Comment by foonathan** [comment]
Ah, the single include is only generated on each release. Then alright, I'll wait.

**Comment by horenmar** [comment]
The build is up now.

**Comment by foonathan** [comment]
Thanks, all green now.
