### ISSUE TITLE
Using the -c flag is extremely slow

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#812]
## Description
I have a TEST_CASE() with several SECTION()s. If I run just the test case by passing the test case name to the executable, it runs in 1 to 2 seconds. If I pass the -c flag and the name of a section, its at least 2 seconds until the test starts to run:

`$ time tests/unit_tests "TESTCASENAME"`
...
`tests/unit_tests "TESTCASENAME"  0.05s user 0.01s system 33% cpu 0.164 total`

And with the section specified, which is a subsection of the test case above, meaning that it is also run on the test above:

`time tests/unit_tests -c "Test parse_parameter_status()"`
...
`tests/unit_tests -c "Test parse_parameter_status()"  0.05s user 0.01s system 0% cpu 18.207 total`

and with gcc:

`tests/unit_tests -c "Test parse_parameter_status()"  0.06s user 0.01s system 0% cpu 18.240 total`

I believe my tests are setup as the documentation recommends as this slowdown didn't happen before.

This delay makes the -c flag sort of... useless? If the whole test case takes less to run than a subsection then there is no point in having the ability to run subsections.

* Catch version: **v1.7.0**
* Operating System: **Latest OSX Sierra**
* Compiler+version: **Latest Clang; GCC 4.8.5**

**Comment by philsquared** [comment]
I appreciate the documentation could be better, but I did try to tag a bit at the end of https://github.com/philsquared/Catch/blob/master/docs/command-line.md#run-section:

"If you specify a section without narrowing to a test case first then all test cases will be executed (but only matching sections within them)."

What I meant by that is you need both the test case name *and* the section name(s) - so in your case, I believe, you want:

```$ time tests/unit_tests TESTCASENAME -c "Test parse_parameter_status()"```

The reason for this is that the only way it can find the sections is by executing to them - so if you don't give it a test case (or test cases) to go into then it will have to try *all* of them.

Probably I should make it an error to specific `-c` without specifying a test case, or at least a set of test cases.

**Comment by ruipacheco** [comment]
That's it.
