### ISSUE TITLE
Regression with REQUIRE_THROWS_AS

### ISSUE THREAD

**Issue by joto** [philsquared/Catch#817]
## Description
I used to be able to write code such as:

    REQUIRE_THROWS_AS({
        statement1;
        statement2;
        ...
    }, std::runtime_error);

This does not work any more (tested in version 1.7.1, it worked in 1.5.9, didn't test anything in between). Clang reports this as `error: expected expression` at the `{` and GCC as `expected primary-expression before ‘{’ token`.

The simpler

    REQUIRE_THROWS_AS(statement, std::runtime_error);

still works fine.

### Extra information
Might be related to #798.

**Comment by horenmar** [comment]
Also a duplicate of #806.
The problem still is that since 1.7.0, Catch now relies on the passed expression being actual expression.

If you have C++11 or later available, just use lambdas.

**Comment by joto** [comment]
Thanks for the quick answer. I am changing my code.
