### ISSUE TITLE
Combined REQUIRE_THROWS_AS and REQUIRE_THROWS_WITH

### ISSUE THREAD

**Issue by joto** [philsquared/Catch#818]
It would be nice to have a macro that combines `REQUIRE_THROWS_AS` and `REQUIRE_THROWS_WITH` allowing to check the exception type and message in one go.

**Comment by horenmar** [comment]
There are more requests for this, so it might happen.

The question is, what the API should be like... the obvious option would be `REQUIRE_THROWS_WITH_AS(expr, exception-type, matcher)`, but the name might not be a good idea and I am not sure whether the API couldn't be better if done differently.

**Comment by lightmare** [comment]
You could add an optional third arg
```c++
REQUIRE_THROWS_AS(stuff(), std::runtime_error, "failed");
```
At first I was going to suggest changing the second arg from exception type to matcher, plus the ability to pass an exception object instead, as in `REQUIRE_THROWS_AS(stuff(), std::runtime_error("failed"))` (which would construct `what()`-equality matcher), but that would probably be both more difficult to implement pre-C++11 and break existing code.

**Comment by horenmar** [comment]
I am going to close this issue in favour of #641. See latest post there for an update.
