### ISSUE TITLE
[Doubt] Call test case with different inputs

### ISSUE THREAD

**Issue by ernanirst** [philsquared/Catch#820]
This is no bug, I'm new to catch, and this is the only thing that I couldn't find how to do using this framework.

It is very usual for me to have classes with multiple constructors, in one specific project, I have a class that has 5 constructors. So I started writing the tests for this class and once I was done, I realized something, I needed to use that same test case with the other four constructors.

What I did was copy a 20 assert test case four times which is a very ugly and bad solution, but its one that works.

Is there a way of creating a test case that could receive an object as parameter? This way I could write one test case and just pass all my constructors as parameter. I try to find something like this on the documentation and I only found TEST_CASE_METHOD, which I couldn't find good examples with.

Best Regards, Ernani

**Comment by kirbyfan64** [comment]
Is there a reason you couldn't just do:

```c++
TEST_CASE("constructors", "[constructors]") {
    REQUIRE(MyType{one_arg} == MyType{one_arg, two_arg});
    // ...
}
```

in order to test the constructors?

**Comment by philsquared** [comment]
I think @ernanirst is after having a common set of asserts on an object that may be constructed different ways.
Assuming that's the case this is ultimately a job for generators - but you can achieve the same effect without too much overhead just by putting the common asserts in a separate function that takes the object, and constructing, and repeatedly calling, the helper function. Ideally have each construction in a different `SECTION`. Something like:

```
void helper( MyType const& myObj ) {
    REQUIRE( myObject.doesThis() );
    REQUIRE( myObject.doesThat() );
    REQUIRE( myObject.value() == 42 );
}

TEST_CASE( "constructors" ) {
    SECTION( "one way" )
        helper( MyType( a ) );
    SECTION( "one way" )
        helper( MyType( a, b ) );
    SECTION( "one way" )
        helper( MyType( a, b, c ) );
}
```

**Comment by ernanirst** [comment]
@philsquared you are completely right. Thanks for the tip and congrats for this very complete test framework.
