### ISSUE TITLE
Catch won't work without RTTI again, issue/bug reintroduced

### ISSUE THREAD

**Issue by BobLoblaw27813789132** [philsquared/Catch#821]
Looks like Issue #648 was reintroduced again... Trying try build catch (unified 1.7.1) with "-fno-rtti" results in:

```
catch.hpp: In member function ‘Catch::Totals Catch::RunContext::runTest(const Catch::TestCase&)’:
catch.hpp:6385:60: error: ‘dynamic_cast’ not permitted with -fno-rtti
                 dynamic_cast<SectionTracker&>( rootTracker ).addInitialFilters( m_config->getSectionsToRun() );
```

You can't mix "-fno-rtti" and "-frtti" code. g++ defaults to RTTI, and my project disables it with "-fno-rtti". Catch won't build with "-fno-rtti" because of the dynamic_cast. Looking at issue #648 it looks like dynamic_cast was removed but recently readded elsewhere with new code.

**Comment by philsquared** [comment]
Sorry about that. Looks like it was me, just recently. Forgot about the convention.
I'll try and work it back out again.

**Comment by philsquared** [comment]
In fact it was quite straightforward.
Please confirm this now works fine for you.

**Comment by BobLoblaw27813789132** [comment]
Confirmed. This fixes the issue and everything works. Thank you!

**Comment by philsquared** [comment]
Thanks. Will try to preserve the invariant now :-)
