### ISSUE TITLE
Duplicate function definition in catch_common.h line 84 and 85

### ISSUE THREAD

**Issue by pasuka** [philsquared/Catch#822]
## Description
In Catch/include/internal/catch_common.h
Line 84 and Line 85 are duplicated
`bool contains( std::string const& s, std::string const& infix );`
`bool contains( std::string const& s, std::string const& infix );`

### Steps to reproduce
According to Catch/include/internal/catch_common.hpp it should be
`bool contains( std::string const& s, std::string const& infix );`
`bool contains( std::string const& s, char infix );`

### Extra information
* Catch version: **v1.7.1**
* Operating System: **Windows 10**
* Compiler+version: **gcc v6.3.0**

**Comment by philsquared** [comment]
Good catch - thanks!
I've completely removed (67d513aa73cabff710e50680ec8ef25804b9fe09) the second one (including the mismatched impl) as it wasn't being used anyway.
