### ISSUE TITLE
REQUIRE_THROWS etc no longer accept a block

### ISSUE THREAD

**Issue by tomhughes** [philsquared/Catch#823]
Although the exception testing macros were documented as taking an expression they would in fact accept a block, so a test like this would work:

```c
REQUIRE_THROWS({
    item.next();
    item.skip();
});
```

As of 0dabd951ba115f682e387d72f7f9866de824db0b this is no longer the case as these macros now cast the first argument to void which results in a compiler error if a block is given.

This should probably at least be clearly documented as I've found at least one project using Catch which has been caught by this.

**Comment by horenmar** [comment]
If you have access to C++11, you can wrap any complex sequence of operations in a lambda.

If not, but aren't declaring new objects, you can abuse parens + the comma operator to chain multiple expressions into one.

If not *and* you want to declare new objects, then it becomes problematic.

**Comment by tomhughes** [comment]
Yes. I didn't think of a lambda but I worked around it with a comma operator in https://github.com/mapbox/protozero/pull/74. Only one of them actually had multiple statements anyway, but several others had a block with a single statement.

**Comment by AdRiley** [comment]
I was using this to test error cases in constructors:

So 

`REQUIRE_THROWS_WITH(MyClass myClass(-1), "N must be positive");`

The lambda workaround works

`REQUIRE_THROWS_WITH([](){MyClass myClass(-1);}(), "N must be positive");`

but adds a lot of extra brackets as clutter to my test.

Will the block functionality be coming back?  Seems like I could write my own macro to do the lambda wrapping, but prefer to stick to core functionality where possible.

**Comment by horenmar** [comment]
Does `REQUIRE_THROWS_WITH(MyClass(-1), "N must be positive")` not work?

**Comment by AdRiley** [comment]
Ah... Yes it does...  

Much better.  Thank you :)
