### ISSUE TITLE
Catch doesn't seem to compile on Windows (Appveyor)

### ISSUE THREAD

**Issue by james-d-mitchell** [philsquared/Catch#834]
## Description
I've been using catch for unit tests in this [C++ library](https://github.com/james-d-mitchell/libsemigroups) and I just updated to catch version v1.7.2 from v1.5.8, and the continuous integration tests run on Appveyor now fail because of some issue in catch. 

The error is shown here on [Appveyor](https://ci.appveyor.com/project/james-d-mitchell/libsemigroups/build/1.0.42/job/x9akmcg1dgkyxbtb) and the raw log is [here](https://ci.appveyor.com/api/buildjobs/x9akmcg1dgkyxbtb/log).

**Comment by horenmar** [comment]
Cygwin does not properly support signals. This (and couple other) cygwin compatibility issues are fixed in master, but aren't yet in a release.

**Comment by james-d-mitchell** [comment]
Great, any idea which version of Catch will contain this fix?

**Comment by horenmar** [comment]
The next one.
The actual answer you probably want is that it will be released at some point this week (likely tomorrow).

**Comment by james-d-mitchell** [comment]
That's great, I'm happy with either answer, since everything is working smoothly with v1.5.8 at the moment :)

**Comment by horenmar** [comment]
1.8.0 is out.

**Comment by james-d-mitchell** [comment]
Thanks!
