### ISSUE TITLE
Catch resets errno to zero when printing

### ISSUE THREAD

**Issue by m-ou-se** [philsquared/Catch#835]
The following test passes when run without any flags, but fails when run with `-s`:

```c++
TEST_CASE("errno") {
  errno = 1;
  REQUIRE(f() == 0);
  REQUIRE(errno == 1); // Check that f() doesn't touch errno.
}
```

Printing the success result of the first REQUIRE resets errno to 0.

Should catch save errno, so we can test error numbers returned through it?

* Catch version: **v1.7.2**
* Compiler+version: **clang version 3.9.1**

**Comment by horenmar** [comment]
We don't touch `errno` directly and mostly stay away from C parts of the standard library, so I wonder what exactly resets it.

**Comment by lightmare** [comment]
I saw some `sprintf`.

**Comment by horenmar** [comment]
@lightmare  Only when `-d yes` is also specified, and its new to the v1.8

**Comment by m-ou-se** [comment]
The problem seems to be the destructor of the `std::ifstream` object in `isDebuggerActive()`, which resets errno: https://github.com/philsquared/Catch/blob/master/single_include/catch.hpp#L8570

**Comment by m-ou-se** [comment]
Looks like libstdc++ breaks a promise:

https://gcc.gnu.org/onlinedocs/libstdc++/manual/errno.html:

> The C and POSIX standards guarantee that errno is never set to zero by any library function. The C++ standard has less to say about when errno is or isn't set, but libstdc++ follows the same rule and never sets it to zero.


libstdc++-v3/config/io/basic_file_stdio.cc:198-202:
> ```C
> int __err;
> errno = 0;
> do
>    __err = this->sync();
> while (__err && errno == EINTR);
(https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/config/io/basic_file_stdio.cc#L199)

**Comment by m-ou-se** [comment]
Filed a libstdc++ bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79820

Should Catch work around this problem by manually saving and restoring errno when std::fstream is used?

**Comment by horenmar** [comment]
We are willing to have a workaround for bug, as long as the complexity cost is reasonable -- this seems to be (even though 


Much more interesting is that this happens even without `-b`, because `isDebuggerActive` shouldn't be called then.

**Comment by horenmar** [comment]
I found out why this happens even without `-b`... we check whether a debugger is active, before using colourized output.

I wonder whether this is actually needed, shouldn't `isatty` be sufficient? If the debugger is run from terminal, colours should just work anyway, otherwise `isatty` shouldn't return true.

**Comment by horenmar** [comment]
This should be fixed, but I'd still like feedback from someone who understands the linux internals better, whether we need the debugger check when deciding to use colours.
