### ISSUE TITLE
Private copy constructor for AssertionPrinter

### ISSUE THREAD

**Issue by Tocic** [philsquared/Catch#843]
The '=' operator is declared as private in the 'AssertionPrinter' class, but the default copy constructor will still be generated by compiler. This may be a bug.

**Comment by lightmare** [comment]
The `operator=` is there only to silence pesky warnings that it won't be generated by the compiler (because it can't be generated when there's a reference, const, or otherwise non-assignable member in the class). Copying would be okay, although it's not needed.

**Comment by horenmar** [comment]
@lightmare is correct, it was added recently because VS 2013 would warn on a class that has copy constructor, but not copy assignment operator. It is however completely OK with it being private and undefined 😄

**Comment by Bu11etmagnet** [comment]
If catch used C++11, that would be `operator=() = delete` and `copy constructor = default`, right?
This combination seems highly suspicious to me. If assignment is disabled, the copy constructor should be disabled too.

**Comment by philsquared** [comment]
Catch needs to support C++03 (although Catch2 will be C++11).
I agree that it seems like a code smell to only "disable" `operator=` and not the copy ctor, so I'm supportive of disabling the copy ctor, too (or better still just derive from `NonCopyable`, which deletes them if C++11 is detected!)

**Comment by lightmare** [comment]
What's suspicious, or smelly? Being copyable doesn't imply being mutable. Ever.
```c++
static_assert( std::is_copy_constructible<const int>::value == true, "");
static_assert( std::is_copy_assignable<const int>::value == false, "");

// or if you want a class example:
struct Foo {
  const int c;
  int m;
};
```
