### ISSUE TITLE
MatcherUntypedBase class has virtual functions, but destructor is not virtual

### ISSUE THREAD

**Issue by GatoRat** [philsquared/Catch#844]
## Description

Compiling with Visual Studio 2017 RC and Visual Studio 2015 Update 3.
Treat specific warning as error: 4265

MatcherUntypedBase has virtual functions, but not a virtual destructor. Adding an empty virtual destructor fixes the issue.

* Catch version: **v1.8.1**
* Operating System: **Windows 10**
* Compiler+version: **VS 2015 and 2017**

**Comment by philsquared** [comment]
Thanks for that. I've added that specific warning to the VS solution generation, too, now
