### ISSUE TITLE
REQUIRE_THROWS_AS doesn't seem to work under certain MSVC

### ISSUE THREAD

**Issue by foonathan** [philsquared/Catch#847]
## Description

REQUIRE_THROWS_AS() doesn't seem to catch the exception properly.

### Steps to reproduce

Following test case:

```cpp
auto dummy1 = 0, dummy2 = 0;

constrained_type<int*, constraints::non_null, throwing_verifier> a(&dummy1);
std::cerr << "1\n";
REQUIRE_NOTHROW((a = &dummy2, true));
std::cerr << "2\n";
REQUIRE_THROWS_AS(a = static_cast<int*>(nullptr), constrain_error);
std::cerr << "3\n";
```

(Taken from my type_safe library)

Results in this output on Appveyor: https://ci.appveyor.com/project/foonathan/type-safe/build/230
(very bottom, 1 is printed, 2 is printed, then abort()).

**Comment by foonathan** [comment]
My bad, still happens after a try-catch so could be an issue on my side.

**Comment by foonathan** [comment]
Okay, my fault, sorry about the noise.

**Comment by philsquared** [comment]
lol - np. Glad you got it sorted (or did you?)

**Comment by foonathan** [comment]
Yes, I did. It was a conditional noexcept that wasn't working.
