### ISSUE TITLE
Environment setup()/teardown()

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#851]
Following on my interest for parameterised tests I'd like to add a suggestion to case #850; I'm opening a new ticket so as to not pollute that issue.

We should be able to parameterise tests on 3 levels: environment with setup()/teardown() when the test suit starts and ends; at the file level, when all tests in a file start/end and per test.

My experience with pytest shows that this allows for a much finer separation of tests into logical units and makes code reuse much easier.

**Comment by philsquared** [comment]
I'm not sure that what works well for Python automatically transfers - so let's take this on it's own merits.
setup/teardown is usually modelled, in Catch, by just having things on the stack in a `TEST_CASE`, with multiple peer `SECTIONS` reusing them.
For cases where that's not sufficient, class-based test fixtures are supported. I hadn't planned to extend generator support to those text fixtures (although I haven't really given much thought to how much that complicates things, if at all). Do you have concerns about the `SECTION` based separation?

**Comment by philsquared** [comment]
(thanks for your input on this, btw)

**Comment by ruipacheco** [comment]
I hadn't thought about the SECTION separation though.

I still think an Environment setup/teardown is important - I was toying with GoogleTest and what made me decide to continue migrating my tests to it is, besides the parameterised tests, the ability to setup and clean external resources like databases on each test run.

Also, is code placed after a section called immediately after that section?

**Comment by philsquared** [comment]
You can do that by adding a `Listener`. I really need to document that.
I'll do it now!

**Comment by ruipacheco** [comment]
Never heard of it. Please let me know when it's done, I might not migrate to gtest then. Save me a lot of trouble.

**Comment by philsquared** [comment]
In short a Listener hooks into the reporter pipeline (but before the reporter itself), and has the same interface (with defaults, so you only implement the events you're interested in - e.g. `testCaseStarting()`, `testCaseEnded()`).

**Comment by ruipacheco** [comment]
I know nothing about the reporter pipeline. Is there any documentation for it? Btw, this is very interesting.

**Comment by philsquared** [comment]
You got me! Reporters are not (yet) documented either!
I'm knocking up some listener documentation now.
In the meantime you might want to have a look here: https://github.com/philsquared/Catch/issues/475#issuecomment-129543664

**Comment by ruipacheco** [comment]
Going through the docs, and judging only by the method names, I'd love to be able to overload these methods: https://github.com/philsquared/Catch/blob/bc68b9f454021455f35fc005e59663a62ed71bca/include/internal/catch_interfaces_reporter.h#L223

This would be exactly what I want.

**Comment by philsquared** [comment]
Yup - that's exactly what it gives you

**Comment by ruipacheco** [comment]
This is excellent, exactly what I needed. I'm going to have more questions but I'll wait for the documentation.

This may put an end for my need for parameterised tests and if `testRunStarting/end` behaves as I assume it does (what is a test run?) I'll just not move to gtest at all.

**Comment by philsquared** [comment]
That sounds great! I hope it works out. The only limitation (currently - this may change in the future) that may be of note is that you can't do any assertions in a listener event.

**Comment by ruipacheco** [comment]
I just need them to setup and clean data.

Very surprised this was lurking in the code all along. Can't wait for the docs.

**Comment by philsquared** [comment]
First cut of the docs are here: https://github.com/philsquared/Catch/blob/master/docs/event-listeners.md
If there's anything not clear there let me know and I'll update it (sorry for the cop-out "look in the source" at the end - but fully documenting all those structs would be a big task for little value).

Also note that I have also just changed the registration macro to `CATCH_REGISTER_LISTENER` (as documented) - as it previously still had the prefix `INTERNAL_` - so if you're using an older version of Catch (including the, still current, single include) you'll need that `INTERNAL_` prefix for now. We should be doing a new release of the single include on Monday.

**Comment by ruipacheco** [comment]
This is absolutely perfect. No more need for parameterised tests or environment setup/teardown. And it behaves very much like Python, at least the granularity.

Still shocked this secret weapon was hidden since 2015.

Closing this ticket with a big smile.

**Comment by philsquared** [comment]
Ha! Well I'm glad it's a happy ending for you.
But it's a black mark for me for putting this off for so long (which is why I decided to just get on with it now).

**Comment by ruipacheco** [comment]
One more question: in gtest the properties of classes used in parameterised tests are available for each test. Is there a way to do something similar by sharing values set on listeners?

**Comment by philsquared** [comment]
I'm not 100% sure I follow what you're asking - but if you mean you want to maintain state in the listener that you make available to your tests then you're pretty much stuck with manipulating globals or singletons.
If that's not what you mean, though, perhaps you could restate your requirement?

**Comment by ruipacheco** [comment]
You answered my question, thanks!
