### ISSUE TITLE
Incorrect values when using rvalue std::optional in REQUIRE

### ISSUE THREAD

**Issue by Hedanito** [philsquared/Catch#861]
## Description
When comparing to an the value of an rvalue std::optional, the returned value seems to be random.

Some example results:
```
1980750608 (0x760fdb10) == 1
-1461722400 == 1
-888087712 == 1
-701308704 == 1
1633345968 (0x615ae1b0) == 1
```

### Steps to reproduce
```
// Works correctly
int i = std::optional<int>(1).value();
REQUIRE(i == 1);

// Works correctly
auto i = std::optional<int>(1);
REQUIRE(i.value() == 1);

// Random value
REQUIRE(std::optional<int>(1).value() == 1);

// Random value
REQUIRE((std::optional<int>(1).value()) == 1);

// Workaround by just wrapping the entire expression
REQUIRE((std::optional<int>(1).value() == 1));
```

### Extra information
* Catch version: v1.8.2
* Operating System: Windows 10
* Compiler+version: Visual Studio 2017

**Comment by onqtam** [comment]
same happens with doctest - but MSVC generates a warning even for the following:

```c++
if(std::optional<int>(1).value() == 1)
```

```warning C4172: returning address of local variable or temporary```

**Comment by horenmar** [comment]
>When comparing to an the value of an rvalue std::optional, the returned value seems to be random.

This pretty much definitely means that invalid memory is being accessed. Seeing @onqtam post, it might not be our fault though, I will have to investigate it later.

**Comment by horenmar** [comment]
Can you test this again with Catch 1.10? Using VS 15.3.2 and Catch 1.10 I cannot reproduce the issue anymore.

**Comment by Hedanito** [comment]
I am currently using Catch v1.9.4 with Visual Studio 15.3.3, and it no longer seems to be an issue.

**Comment by horenmar** [comment]
@Hedanito Thanks. I'll consider the issue resolved.
