### ISSUE TITLE
In Visual Studio 2015 there is no colored output and the window doesn't stay open.

### ISSUE THREAD

**Issue by kim366** [philsquared/Catch#863]
In VS 2015 when I use Catch, it immediately closes and I had to resort to 

```
#define CATCH_CONFIG_RUNNER
#include <catch.hpp>

int main(int argc, char** argv)
{
	int result = Catch::Session().run(argc, argv);
	system("pause");
	return (result < 0xff ? result : 0xff);
}
```

to get that "Press any key to continue...", which I saw people have even when they did `#define CATCH_CONFIG_MAIN`.

My bigger issue, though, which is probably not at all tied to Catch, but someone here might still be able to  resolve is that there is no colored output in Visual Studio debug. I have to start the .exe myself to get colored output, which is really weird, because it is literally the same program.

Anyone have solutions?

**Comment by kim366** [comment]
Thank you very much. This worked like it should.

**Comment by kim366** [comment]
Just one thing: how do I close a thread here? I never used GitHub issues before.

**Comment by nabijaczleweli** [comment]
Smash the gigantic close issue button
