### ISSUE TITLE
losing expansion in CHECK due to CAPTURE

### ISSUE THREAD

**Issue by maiermic** [philsquared/Catch#864]
If I run

```c++
#include <catch.hpp>
#include <vector>

TEST_CASE("capture variable without losing expansion") {
    std::vector<int> v {1, 2, 3};
    CHECK(2 == v.size());
}
```

an expansion of the right hand side expression `v.size()` is printed

```
/path/to/my_test.cpp:6: Failure:
  CHECK(2 == v.size())
with expansion:
  2 == 3
```

If I add a `CAPTURE`

```c++
#include <catch.hpp>
#include <vector>

TEST_CASE("capture variable without losing expansion") {
    std::vector<int> v {1, 2, 3};
    CAPTURE(v);
    CHECK(2 == v.size());
}
```

I get the expected `CAPTURE` message, but I lose the expansion

```
/path/to/my_test.cpp:7: Failure:
  CHECK(2 == v.size())
with message: 
  v := { 1, 2, 3 }
```

I expect the output to be

```
/path/to/my_test.cpp:7: Failure:
  CHECK(2 == v.size())
with expansion:
  2 == 3
with message: 
  v := { 1, 2, 3 }
```

Is this a bug or a feature?

---

Catch v1.8.2

**Comment by lightmare** [comment]
What compiler? I took your second example, only added `#define CATCH_CONFIG_MAIN` on top, and am getting the expected output with both expansion and message. gcc 4.8, 5, 6, clang 3.6, 3.8, 4.0

**Comment by lightmare** [comment]
Are you using a custom reporter? Because I searched for the word "Failure"
```sh
git grep -w 'Failure' $(git rev-list --all) -- include/reporters/
```
and it only appears in the xml reporter.

**Comment by philsquared** [comment]
Ah!
Are you using CLion, by any chance, @maiermic?
(CLion's integrated Catch test runner uses the XML reporter, but then presents it back in a way that looks similar to the console reporter.
That might explain the difference. I'll take a look at that.

**Comment by maiermic** [comment]
@philsquared You are right. I use Clion 2017.1 EAP with a _Catch Test_ configuration. If I use an _Application_ configuration it shows the correct result. Sorry, I should have checked that earlier.

**Comment by maiermic** [comment]
I have updated to the latest version *CLion 2017.1 RC2, build 171.3780.103, March 22nd, 2017*. Same issue. I created a [bug report](https://youtrack.jetbrains.com/issue/CPP-9305) for Clion.

**Comment by philsquared** [comment]
Perfect - thanks, @maiermic - saves me doing that.

**Comment by philsquared** [comment]
Running your example with the XML reporter confirms that all the information is present in the report - so this is a pure CLion issue.
Therefore do you have any objection to me closing this ticket, @maiermic?
