### ISSUE TITLE
enforceNotReservedTag should not call exit(1) when an error is detected

### ISSUE THREAD

**Issue by horenmar** [philsquared/Catch#865]
## Description
On error, some places in Catch used to call `exit(...)`. The one in `enforceNoDuplicateTestCases` (#608) was fixed, but there are two places still left. This issue is for `enforceNotReservedTag`.

**Comment by horenmar** [comment]
This needs to be revisited, because letting exception escape out of global constructor works reasonably on linux (what() is printed), the same cannot be said for Windows -- on Windows it just aborts the program.

This could probably be solved by installing our own terminate handled via `std::set_terminate` and `std::current_exception`, or, we could conditionally compile in a try-catch block.

Note, the same applies for RegistrarForTagAliases in #866.

**Comment by philsquared** [comment]
my idea was to, instead of throwing the exceptions, log them somewhere (yes, another singleton) and continue. Then when the Catch session object is instantiated throw any stored exceptions then.

**Comment by horenmar** [comment]
@philsquared That would probably work as well, but creating a singleton to store exceptions from global object so you can throw them later on seems perverse. 😄
