### ISSUE TITLE
Provide a templatized Approx

### ISSUE THREAD

**Issue by tomvierjahn** [philsquared/Catch#873]
## Description
We are using a rather paranoid warning level including `-Werror`.
Consequently using `Approx` on `float` breaks compilation:
```
implicit conversion increases floating-point precision: 'float' to 'double' [-Werror,-Wdouble-promotion]
```

Could you provide a templatized `Approx` supporting `float` and `double`?

### Extra information

* Catch version: **v2.0.0-develop.3** (git hash afc0b31)
* Operating System: **MacOs X 10.12.3**
* Compiler+version: **Apple LLVM version 8.0.0 (clang-800.0.42.1)**

**Comment by horenmar** [comment]
Wouldn't a float constructor be enough?

**Comment by tomvierjahn** [comment]
As long as the comparison operators are also taking floats and doubles.

**Comment by tomvierjahn** [comment]
> Also you can just cast the float to double.

That would yield bulky, ugly code:
```
CHECK(static_cast<double>(variable) == Approx(5.0))
```

**Comment by horenmar** [comment]
@tomvierjahn If you are using C++11, all of the `Approx`'s operators support any type that can be converted to double, including strong typedefs.

**Comment by tomvierjahn** [comment]
Would you mind also including it into the single-header version?

**Comment by horenmar** [comment]
Next release, so hopefully at some point this week.

If you want it now, you can make it using `scripts/generateSingleHeader.py`.
