### ISSUE TITLE
Concurrent INFO() calls crash [multithreading]

### ISSUE THREAD

**Issue by theWayofthecode** [philsquared/Catch#875]
## Description
As the title suggest the test case below crashes either by segfault or double free. The problem does NOT occur with, say, WARN(). I assume because INFO() buffers the messages in a non-thread-safe way.

### Steps to reproduce
```
TEST_CASE("concurrent infos")
{
  std::thread t([]() {
    for (int i = 0; i < 100; ++i)
      INFO("i: " << i);
  });
  for (int i = 0; i < 100; ++i)
    INFO("i: " << i);
  t.join();
}
```

### Extra information

* Catch version: 3a3f1529794059e1f8947c1d44ed10327b2a35d8
* Operating System: **CentOS (devtoolset-6)**
* Compiler+version: **gcc 6.2/icc 2017**

 Many thanks for Catch!

Aram

**Comment by horenmar** [comment]
[I probably should have mentioned other macros as well as assertions, but Catch is not thread safe.](/philsquared/Catch/blob/master/docs/limitations.md#thread-safe-assertions)

**Comment by theWayofthecode** [comment]
I see. In that case I believe it would be helpful to mention it also in the "Assertion macros" "Logging macros" doc files in the reference section.

**Comment by horenmar** [comment]
I will think about it
