### ISSUE TITLE
[feature request]: Optionally disable tests during configuration

### ISSUE THREAD

**Issue by rianquinn** [philsquared/Catch#897]
It would be great if there was a way to disable the compilation of the unit tests during cmake's configuration. Specifically for CI. When we include Catch via ExternalProject_Add, the unit tests are compiled during each CI test which wastes time. A simple -DDISABLE_UNITTESTS would go a long way to shaving off a minute from each test for people using Catch.hpp.

**Comment by kirbyfan64** [comment]
FWIW is there a reason you can't just run:

```
curl -L https://github.com/philsquared/Catch/releases/download/v1.9.3/catch.hpp -o catch.hpp
```

first?

**Comment by horenmar** [comment]
Do you mean Catch's own selftests?

**Comment by rianquinn** [comment]
@kirbyfan64 curl is not present on all systems. 
@horenmar yes, Catch's own selftests. A lot of people use CMake's ExternalProject_Add to get Catch instead of using git submodules, or maintaining a copy in their repo, but Cactch's CMakeList.txt is currently setup so that a `make install` first builds the self tests, so this is being done on every CI test for projects that use Catch.

**Comment by rianquinn** [comment]
This is a good example of what I'm talking about. 
https://travis-ci.org/Microsoft/GSL/builds/226877346?utm_source=github_status&utm_medium=notification

For our hypervisor project we maintain a patched version of Catch to fix this, but I couldn't do that for Microsoft's GSL patch to switch to Catch, so at the moment, its always building the self tests.

**Comment by kirbyfan64** [comment]
> curl is not present on all systems.

Yes, but it's available:

> Specifically for CI

;)

FWIW there's other stuff you can do too, but in general, curl is present on *most* systems. Heck, Git uses curl for HTTPS transport, so if someone's downloaded the source code, there's a good chance they also have curl installed.

**Comment by rianquinn** [comment]
For CI, yes we probably could make that work. It's not as elegant though as we would have two ExternalProject_Add blocks, one for CI, and one for everything else. Plus, I think in general when someone wants to say build and test the GSL, they don't want build and test the GSL's unittest selftests. I think it would be a useful option for projects using Catch, and it would be a pretty simple mod to the CMakeLists.txt file to support.

**Comment by horenmar** [comment]
While I still think that either getting the single-include directly, or vendoring it, is the better option, especially if you are using tagged version and don't want automatic update, there is no reason not to support this.

Anyway, just sticking `if (!NO_SELFTEST)` and `endif()` around defining the `SelfTest` and `Benchmark` targets should be enough, correct?

**Comment by rianquinn** [comment]
This is my patch. I don't think you need all of this. You do at least have to disable setting the compiler options for these targets if they do not exist. 
https://github.com/Bareflank/Catch/commit/61080717bf7706a94ab115441d5357911c02907d

**Comment by rianquinn** [comment]
👍 Thanks a ton
