### ISSUE TITLE
Bug :: error: redefinition of Catch::AutoReg {anonymous}::autoRegistrar9

### ISSUE THREAD

**Issue by hassanfarid** [philsquared/Catch#901]
## Description
I read a bit about this bug report [here](https://github.com/philsquared/Catch/issues/296).

My project has following design:
includes.h -- this file includes all *.h files that have test cases for different modules. Like module1.h, module2.h, etc.

In files module1.h & module2.h: The first test case in each module is defined at line number 9. Both test cases have different names, and tags.

Do I have to define test cases on different lines across all files? This is not easily scalable, and hard to ensure that all users do it accordingly.

What is the work around? Defining all test cases in one files isn't a solution.

### Extra information
* Catch version: **v1.5.6**
* Operating System: **Linux flavor**
* Compiler+version: **GCC 5.2 or newer**

**Comment by philsquared** [comment]
First question is why are you writing your tests in header files? Why not just write them in separate .cpp files?

That said this *should* work, now, as the `TEST_CASE` macro should be using `__COUNTER__` instead of `__LINE__`. Have you tried this and hit problems? If so what is the error?

**Comment by philsquared** [comment]
After writing that I saw that the issue title is probably the error you're seeing.
Could you try defining `CATCH_CONFIG_COUNTER` (either for your project, or as a `#define` just before `#include`ing Catch)

**Comment by philsquared** [comment]
For reference, this is possibly a continuation of: https://github.com/philsquared/Catch/issues/435

**Comment by hassanfarid** [comment]
In parallel, I did my research on existing reported issues and found solution to use `CATCH_CONFIG_COUNTER` , and this is solution to this problem. Thanks for the help.

On a side note, is it recommended to use .cpp files instead of header? Is it something related to good practices?

**Comment by philsquared** [comment]
Well, `CATCH_CONFIG_COUNTER` is a workaround. It should be automatically defined for you.
If using it explicitly fixes it for you then it suggests it is not being automatically used. It could be good to work out why that is.

As for using .cpp files - yes that's the normal way to do it - unless you have specific reasons for putting them in headers (I can't really think of any).
