### ISSUE TITLE
INTERNAL_CATCH_MSG compilation error without variadic macro support

### ISSUE THREAD

**Issue by grahamshanks** [philsquared/Catch#902]
## Description

Simple statements like `FAIL( "Here" );` do not compile if the compiler does not support variadic macros. 

It appears that the `INTERNAL_CATCH_MSG` macro has a different, and incorrect, order of declaration of its parameters for compilers without variadic macro support.

### Extra information

* Catch version: **v1.9.3**
* Operating System: **Windows 7 x64**
* Compiler+version: **Visual Studio 2008**

**Comment by horenmar** [comment]
This should be fixed in master (commit 5ffc8a84cda91b5da037a923480236450f7f4586) but it hasn't gotten into official release yet.

**Comment by horenmar** [comment]
It took me longer than I expected to get around making a new release, but it is out.

Can you check whether 1.9.4 fixed this issue for you?

**Comment by grahamshanks** [comment]
Confirmed as fixed with 1.9.4
