### ISSUE TITLE
Please support CONFIG_NO_EXCEPTIONS or similar

### ISSUE THREAD

**Issue by JonChesterfield** [philsquared/Catch#907]
I would like to use catch with a C++ project that has exceptions disabled. Out of the box this causes compiler errors for the try {} within CHECK.

I'm working around by setting CATCH_CONFIG_FAST_COMPILE and using REQUIRE instead of CHECK, but native support would be nicer.

Cheers

**Comment by horenmar** [comment]
Catch currently uses exceptions internally and that is unlikely to change, so test failures would have to abort the whole binary. I don't think that would be a good idea.
