### ISSUE TITLE
Are spaces valid in tags?

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#909]
Is it valid to have spaces in tag names? For example:

    "[this has spaces in it]"

If so, could you update [the documentation](https://github.com/philsquared/Catch/blob/master/docs/test-cases-and-sections.md) to describe, more in-depth, the valid structure for normal tags? At the very least, explicitly specify whether or not spaces are valid, similar to how you specify that the tags are case-insensitive.

**Comment by horenmar** [comment]
At this moment pretty much anything is allowed, as long as it is between `[` and `]`. Whether this is good idea is open to question.

I'll see about make the documentation more specific.
