### ISSUE TITLE
Include external test runner for best CI integration

### ISSUE THREAD

**Issue by tsondergaard** [philsquared/Catch#920]
## Description
Catch should supply an external test runner to add full support for stdout and stderr redirection and to be able to deal with tests that crash. The external test runner application should take the same command line argument as catch process today plus the name of the test executable (possibly multiple)

When catch tests are run today by e.g Jenkins it is not sufficient to look at the junit output as tests can crash and some of the stdout and stderr output may not be have been properly captured. With an external runner controlling test execution it becomes possible to make a robust solution.

**Comment by philsquared** [comment]
I'm closing this in favour of: #853 - so you might want to add yourself as a watcher to that issue.
