### ISSUE TITLE
Msvc with ‘/std:c++latest’:  std::uncaught_exception() is deprecated in C++17 

### ISSUE THREAD

**Issue by PhoebeHui** [philsquared/Catch#927]
std::uncaught_exception() is deprecated in C++17, which is breaking builds by msvc with ‘/std:c++latest’ option on Windows. 
Even I  pass '/D_SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING' to avoid the warning , but Catch need address the issue since it affects all users. 

https://github.com/philsquared/Catch/blob/master/include/internal/catch_section.hpp#L36 

Failures:
..\catch\include\internal\catch_section.hpp(36): error C2220: warning treated as error - no 'object' file generated [D:\RxCpp\build_x86\test\rxcpp_test_group_by.vcxproj]
..\catch\include\internal\catch_section.hpp(36): warning C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by horenmar** [comment]
This is weird, because we already have AppVeyor configured to build with MSVC 2017 and `/std:c++latest` enabled.

**Comment by StephanTLavavej** [comment]
Please note that Phoebe is referring to a C++17 deprecation warning that I've implemented in an unreleased build of MSVC 2017 (the second toolset update; not 2017 15.3 which is the first toolset update). So that's why you aren't seeing the warning yet.

**Comment by horenmar** [comment]
@PhoebeHui Sorry, can't reproduce this with an up to date VS 2017, can you give better repro steps?

**Comment by StephanTLavavej** [comment]
Yes. The best way is to detect whether C++17 `uncaught_exceptions()` is available (unconditionally for VS 2015 and above; libstdc++ 6.1 provides a feature-test macro; I believe libc++ 3.7 provides a feature-test macro), and replace `uncaught_exception()` with `uncaught_exceptions() > 0`.

**Comment by horenmar** [comment]
@StephanTLavavej I would prefer not to bring in even more compile time configuration into Catch Classic, paving over differences from C++98 to C++14 is already painful enough, so I am going to disable the warning for MSVC and tag this with revisit for Catch 2.

**Comment by StephanTLavavej** [comment]
That works, thanks!

**Comment by davidaue** [comment]
I'm getting this same issue with Catch2 on the current MSVC++2017
