### ISSUE TITLE
Incorrect detection of GCC version

### ISSUE THREAD

**Issue by robson3** [philsquared/Catch#928]
Condition to check if GCC version is above 4.3 is incorrect (catch.hpp line 223)
`( defined __GNUC__ && __GNUC__ >= 4 && __GNUC_MINOR__ >= 3 )`
For example it is false for GCC 5.2 or GCC 7.1, as a result `__COUNTER__` macro is not used even though it is available in those compilers.

Possible fix
`( defined __GNUC__  && (__GNUC__ > 4 || __GNUC__ == 4 && __GNUC_MINOR__ >= 3 ))`

**Comment by horenmar** [comment]
That is embarassing, especially since I remember fixing this in different place.
