### ISSUE TITLE
Feature Request: Make more info available from command line

### ISSUE THREAD

**Issue by BMBurstein** [philsquared/Catch#930]
## Description
Option to get more information about the tests without running them.
For example, get file names and line numbers for each test and get sections list for a test.

This will be useful when trying to connect to an external runner (I am currently trying to connect to Visual Studio's Test Explorer, but this information would probably be relevant for other runners, too).

**Comment by horenmar** [comment]
This is in both Catch 1 and 2, so I am going to close it.
