### ISSUE TITLE
[Question] Section execution order

### ISSUE THREAD

**Issue by stevemk14ebr** [philsquared/Catch#944]
This title sucks, sorry, easiest to explain via example. I have the following

```
TEST_CASE(...)
{
    //Initial object state that all following sections use
   SECTION(...)
   {
        //Modifies the object and does specific checks to make sure modification worked
   }

   SECTION(...)
   {
      //Modifies the object in a different way and check to make sure modification worked
   }

   //Some further checks that modification worked, but it is shared between both sections. Does this code
here get executed for both sections.
}
```

So i've got a few sections that do some checks of their own, and then i have some other code that is common between the sections. I know that any code placed before sections is executed for each section, and that it occurs before the code written in the section blocks. Is it true that code written after the section blocks is also executed for each section, but AFTER the section block executes?

I need a nice way to structure this, currently i have the checks duplicated into both sections but these are quite complex checks and it is not scallable in it's current form.

**Comment by horenmar** [comment]
Yes

**Comment by horenmar** [comment]
I am going to close this as resolved.
