### ISSUE TITLE
SelfTest compile errors with c++1y and c++11

### ISSUE THREAD

**Issue by thoughton** [philsquared/Catch#946]
Hi,

I'm a new Catch user, just starting off by cloning the entire repository and doing a standard CMake build.

I work in an environment which has the C++ standard set by default to `-std=c++1y`, and upon attempting the aforementioned build I encountered many errors along the lines of:
```
[  8%] Building CXX object CMakeFiles/SelfTest.dir/projects/SelfTest/BDDTests.cpp.o
/Catch-master/projects/SelfTest/ApproxTests.cpp:178:14: error: 
      invalid operands to binary expression ('StrongDoubleTypedef' and 'Catch::Detail::Approx')
  REQUIRE(td == Approx(10.0));
          ~~ ^  ~~~~~~~~~~~~
/Catch-master/include/catch.hpp:181:91: note: expanded from
      macro 'REQUIRE'
#define REQUIRE( expr ) INTERNAL_CATCH_TEST( "REQUIRE", Catch::ResultDisposition::Normal, expr  )
                                                                                          ^
/Catch-master/include/internal/catch_capture.hpp:80:60: note: 
      expanded from macro 'INTERNAL_CATCH_TEST'
    } while( Catch::isTrue( false && static_cast<bool>( !!(expr) ) ) ) // expr here is never evaluated at runtime but it forces the co...
                                                           ^
/Catch-master/include/internal/catch_approx.hpp:59:66: note: 
      candidate template ignored: disabled by 'enable_if' [with T = StrongDoubleTypedef]
        template <typename T, typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
                                                                 ^
/Catch-master/include/internal/catch_approx.hpp:70:66: note: 
      candidate template ignored: disabled by 'enable_if' [with T = Catch::Detail::Approx]
        template <typename T, typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
                                                                 ^
/Catch-master/projects/SelfTest/ApproxTests.cpp:179:24: error: 
      invalid operands to binary expression ('Catch::Detail::Approx' and 'StrongDoubleTypedef')
  REQUIRE(Approx(10.0) == td);
          ~~~~~~~~~~~~ ^  ~~
/Catch-master/include/catch.hpp:181:91: note: expanded from
      macro 'REQUIRE'
#define REQUIRE( expr ) INTERNAL_CATCH_TEST( "REQUIRE", Catch::ResultDisposition::Normal, expr  )
                                                                                          ^
```
...and many, many pages more.

I wondered whether it might be due to my environment's C++ standard setting, so I tried with `c++11` instead - however I hit similar compile issues again.

As a last attempt, I tried removing the `-std` setting from my environment altogether, and to my surprise this actually worked!  (I will admit I'm not sure what the C++ std defaults to in this case.)

So I was wondering if anyone could help me to configure a build that works in my default `c++1y` environment? Are there some build variables that I perhaps need to set?

I'm using `Mac OS X 10.9.5`, and here's some compiler info:
```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```
Please let me know if there're any other details that would be helpful.

Thanks in advance!

**Comment by horenmar** [comment]
The reason it works without `-std=x` is that it defaults to C++98 and those tests are `ifdef`ed away.

Anyway, for some reason, your particular setup has trouble with `std::is_constructible` type trait, so that a type with explicit conversion to double returns false, instead of returning true, so the proper overload is SFINAEd away, causing the compile error you see.

I am phone posting and don't have any Mac, but if @philsquared doesn't get around this before Friday, I'll see what I can do.

**Comment by horenmar** [comment]
Took me a bit longer to get back to this, but please try this bit of code in your env, with c++11 enabled.

```cpp
#include <iostream>
#include <iomanip>
#include <type_traits>

struct weak_typedef {
    operator double() const { return 1;}
};

struct strong_typedef {
    explicit operator double() const { return 2;}
};

int main() {
    std::cout << std::boolalpha;
    std::cout << std::is_constructible<double, float>::value << '\n';
    std::cout << std::is_constructible<double, weak_typedef>::value << '\n';
    std::cout << std::is_constructible<double, strong_typedef>::value << '\n';
}
```
The output should be
```
true
true
true
```

**Comment by thoughton** [comment]
Hi again! Thanks for the reply.

Here's the output I get from your code suggestion:
```
$ ./build/CatchDebug 
true
true
false
```

**Comment by horenmar** [comment]
By my understanding, that means your stdlib is broken and Catch's SelfTest can't build cleanly in C++11 (or newer) mode.

Is there a reason you need to build it? Because Catch itself should still work, just missing a feature.

**Comment by thoughton** [comment]
Oh, that's really strange. Maybe it's because my version of Mac OS X (and therefore XCode toolchain) are stuck on an old version, and maybe its compiler and libs are buggy in that version...?

Anyway, no, there's no reason I need to build it.  I'm just a curious new user, and I just presumed building it all might be a good first step to learning more about it.

So it sounds like I should just go ahead and try to use it anyway, and simple not worry about being unable to compile the SelfTests?

Thanks for your help!

**Comment by horenmar** [comment]
You can also delete the last `TEST_CASE` in `projects/SelfTest/ApproxTests.cpp`, but if you want to use the library, I would generally recommend playing around with your own tests, rather than with our selftest. The SelfTest project and scripts around it are meant for further development of Catch.

**Comment by thoughton** [comment]
Thanks very much, I will happily just ignore the `SelfTest`s then and proceed with actually implementing my own tests.

Thanks again for your help, it's much appreciated!
