### ISSUE TITLE
Mention C++ standard(s) supported in title?

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#948]
To get a better result for CATCH in [searches for C++ (98) test frameworks](https://github.com/search?q=language%3AC%2B%2B+98+test+framework&type=Repositories&ref=advsearch) it likely helps to include the C++ standard(s) it supports.

For example:
```
A modern, C++-native, header-only, framework for unit-tests, TDD and BDD using C++98 or later 
```

**Comment by horenmar** [comment]
AFAICS only repository owner can do this, so I assigned this to @philsquared

**Comment by philsquared** [comment]
Thanks for the suggestion, @martinmoene 
Done!
