### ISSUE TITLE
Mention relevant topics below title

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#949]
Below the repositorie's title there's room to mention topics that hold for CATCH, e.g.
```
testing cpp98 cpp11 single-file header-only no-dependencies tdd bdd framework
```
See for example [lest](https://github.com/martinmoene/lest).

**Comment by horenmar** [comment]
AFAICS only repository owner can do this, so I assigned this to @philsquared

**Comment by martinmoene** [comment]
Hi @philsquared,

Did you intentionally avoid adding  [topics](https://help.github.com/articles/about-topics/), or was the issue unclear?

Cheers, Martin

**Comment by philsquared** [comment]
Sorry - I thought I'd done this already and just not updated the ticket.
I must have dreamt it :-)
Added now - thanks for the prompt

**Comment by martinmoene** [comment]
Great!
