### ISSUE TITLE
Callable test case?

### ISSUE THREAD

**Issue by nuyir** [philsquared/Catch#950]
I'll be very happy if I can write a code like the following:

    CALLABLE_TEST_CASE("common_test", type1 arg1, type2 arg2) {
        REQUIRE( ... ); // Some tests with arg1 and arg2
    }
    
    TEST_CASE("test1") {
        type1 t1;
        type2 t2;
    
        // Do something with t1 and t2 and then
        CALL_TEST_CASE("common_test", t1, t2);
    }
    
    TEST_CASE("test2") {
        type1 t1;
        type2 t2;
    
        // Do another something with t1 and t2 and then
        CALL_TEST_CASE("common_test", t1, t2);
    }

If the test fails, a stacktrace would be printed.

    Test.cpp:100: FAILED:
    called from Test.cpp 120:
       REQUIRE(...)

Is that possible? If not, would you please consider implementing this feature?

**Comment by dvirtz** [comment]
You can put REQUIRE in a plain function and call that from both tests.

**Comment by nuyir** [comment]
@dvirtz Of course, I can make a function. However, it does not give the stacktrace when the test in the function fails. If each test case has only one call of the function, I can inverstigate the log and decide which test failed. However, if there are several calls in a test case, I think there is no way to decide which call fails.

**Comment by rioderelfte** [comment]
You could capture the parameters at the beginning of the helper function using the `CAPTURE` macro. If a `REQUIRE` inside the helper function fails the values of the parameters will be included in the error message.

**Comment by nuyir** [comment]
@rioderelfte It does not help. It's impossible to identify the caller of the helper function by the parameter values in general.

**Comment by philsquared** [comment]
Full solution to this will be generators: #850

In the meantime you can approximate it by putting a `SECTION` in your helper function.
The caveat is that the section name must have a unique name on each invocation (i.e. the name must be uniquely dependent on the inputs).
BTW in your example you might also want to combine your two test cases into one, with sections.
Something like this (untested, based on your example):

```c++
void verifyProperty( type1 arg1, type2 arg2 ) {
    std::ostringstream oss;
    oss << "Property holds for: " << arg1 << ", " << arg2;
    SECTION( oss.str() ) {
        REQUIRE( ... ); // Some tests with arg1 and arg2
    }
}

TEST_CASE("tests") {
    type1 t1;
    type2 t2;

     SECTION( "test 1" ) {
          // Do something with t1 and t2 and then
          verifyProperty( t1, t2);
      }

     SECTION( "test 2" ) {
        // Do another something with t1 and t2 and then
        verifyProperty( t1, t2);
    }
}
```

**Comment by nuyir** [comment]
@philsquared Thank you. It works. It is sufficient for my use case.

**Comment by jheruty** [comment]
```
#define CALL(func, ...) \
[&]() { /* Create scope for INFO */ \
    INFO("Calling " << #func << " on line " << __LINE__ << ".");\
    return func(__VA_ARGS__);\
}()\
```

I was looking for this feature and ended up writing this macro. You can then use it like `auto val = CALL(Function, arg);`. A similar macro can be written for zero argument calls. Seems to work well for my purposes.
