### ISSUE TITLE
Approx margin has surprising edge-case behaviour with precise values

### ISSUE THREAD

**Issue by TBBle** [philsquared/Catch#952]
## Description
If you use `Approx` and `margin` with precisely-representable values, and the value is precisely `Approx` +- `margin`, the test fails. The documentation states:
> **margin** serves to set the the absolute value by which a result can be erroneous before it is rejected. By default set to `0.0`.

My understanding of this is that if the result is erroneous by precisely the margin, then it should not be rejected.

### Steps to reproduce
```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE( "Approx with exactly-representable margin" )
{
    CHECK( 0.25f == Approx( 0.0f ).margin( 0.25f ) );

    CHECK( 0.0f == Approx( 0.25f ).margin( 0.25f ) );
    CHECK( 0.5f == Approx( 0.25f ).margin( 0.25f ) );

    CHECK( 245.0f == Approx( 245.25f ).margin( 0.25f ) );
    CHECK( 245.5f == Approx( 245.25f ).margin( 0.25f ) );
}
```

*Current result:* All five assertions fail.
*Expected result:* All five assertions pass.

### Extra information

* Catch version: **v1.9.6**
* Operating System: **CentOS 7 Linux on AMD64**
* Compiler+version: **g++ "Red Hat 4.8.5-4"** (stock) and **g++ Red Hat 6.2.1-3** (devtoolset-6)

**Comment by horenmar** [comment]
The current implementation only accepts values that are off by less than margin.

I can see how that is not reflected by the docs, and having the margin be inclusive is likely a better idea, but it could be a breaking change, so we will need some time to decide.

**Comment by TBBle** [comment]
I *think* that the right value would be achieved by `margin( epsilonVal + epsilonVal * std::numeric_limits<decltype( epsilonVal )>::epsilon() )`. If that's correct (my floating-point math is a little weak) then perhaps a new method (`marginInclusive`?) could be added that sets `m_margin` to the above, and hence avoids breaking backwards compatibility.

```c++
TEST_CASE( "Approx with exactly-representable margin and epsilon added" )
{
    CHECK( 0.25f == Approx( 0.0f ).margin( 0.25f + std::numeric_limits<float>::epsilon() * 0.25f ) );

    CHECK( 0.0f == Approx( 0.25f ).margin( 0.25f + std::numeric_limits<float>::epsilon() * 0.25f  ) );
    CHECK( 0.5f == Approx( 0.25f ).margin( 0.25f + std::numeric_limits<float>::epsilon() * 0.25f ) );

    CHECK( 245.0f == Approx( 245.25f ).margin( 0.25f + std::numeric_limits<float>::epsilon() * 0.25f ) );
    CHECK( 245.5f == Approx( 245.25f ).margin( 0.25f + std::numeric_limits<float>::epsilon() * 0.25f ) );
}
```

passed.

**Comment by pip010** [comment]
0.0 == Approx( 0.0 )
fails too !

**Comment by pip010** [comment]
CHECK( 0.25f == Approx( 0.0f ).margin( 0.25f + std::numeric_limits<float>::epsilon() * 0.25f ) );

SHOOT ME NOW :D 

when testing is more complicated than what is tested :D

**Comment by horenmar** [comment]
I am consolidating the Approx issues into one, #980.
