### ISSUE TITLE
Approx scale and other default parameters

### ISSUE THREAD

**Issue by rvanvenetie** [philsquared/Catch#953]
Why is the default scale parameter of the approx class currently set to 1.0? 

Assuming normal scales, it seems to me that 0.0 should be the default case. 
With the current default settings, it gives `pow(10,-5) == Approx(pow(10,-7))`, while
the first number is 100 times larger..

Aside, is it possible to change the default parameters (epsilon, scale) for all Approx initialization in my test script, without creating my own derived class?

**Comment by rvanvenetie** [comment]
Also, currently `0.0 != Approx(0.0).scale(0)`

I suggest changing

`std::fabs(lhs_v - rhs.m_value) < rhs.m_epsilon * (rhs.m_scale + (std::max)(std::fabs(lhs_v), std::fabs(rhs.m_value)));`

to

`std::fabs(lhs_v - rhs.m_value) <= rhs.m_epsilon * (rhs.m_scale + (std::max)(std::fabs(lhs_v), std::fabs(rhs.m_value)));`

**Comment by horenmar** [comment]
I am consolidating the Approx issues into one, #980.
