### ISSUE TITLE
Solo test cases

### ISSUE THREAD

**Issue by j2bbayle** [philsquared/Catch#959]
It would be very nice to have a way to "solo" test cases, especially when working on one -- without the need to execute all of them, which can be time consuming. For now the only way I know is to add tags to each and every other test cases.

A way to implement it could be to add a special tag `[!solo]` similar to `[!hide]`, which, if present, excludes all test cases without it.

**Comment by philsquared** [comment]
Does supplying the test name on the command line not work for you?

`./exeName "test case name"`

**Comment by j2bbayle** [comment]
Indeed it works perfectly. Since I'm working in an IDE, I very rarely add command line arguments when building and running my projects, but this is a good point @philsquared. Thanks!

**Comment by philsquared** [comment]
no problem - which IDE are you using, btw?

**Comment by j2bbayle** [comment]
Xcode in its latest version. It's a little bit of a hassle to add/remove arguments each time you run, that's the only (small) issue.

**Comment by philsquared** [comment]
Ah , yeah.
It's not too bad, though - in fact probably still less hassle than writing a tag and recompiling?

**Comment by j2bbayle** [comment]
You're probably right! Although I feel like one expects it, knowing that `[!hide]` exists -- to tell the truth I used it without thinking about it and discovered the error at runtime.

But I don't think it's worth the trouble of adding it since a single command line argument does the job.

**Comment by philsquared** [comment]
Yeah - the big difference is that `[!hide]` (or the shorter `[.]`) is something you'll usually leave on indefinitely - whereas a hypothetical, `[!solo]` would be intended for short term use.

Also, some IDEs (notably CLion and Visual Studio with the ReSharper C++ plug-in) have test runner integration that will let you run an individual test with a single mouse command.

At some point I do still hope to get to Xcode integration.

**Comment by j2bbayle** [comment]
That’d be **very** nice indeed, and make it extremely pleasant to use!
Thanks anyway for your work!

**Comment by j2bbayle** [comment]
That’d be *very* nice indeed, and make it extremely pleasant to use!
Thanks anyway for your work!
