### ISSUE TITLE
Approx.epsilon bug

### ISSUE THREAD

**Issue by JeroenBoschma** [philsquared/Catch#962]
First time use of Github, hope everything is according to the rules :-)

The following test, which should obviously fail, passes:

`REQUIRE(1e-14 == Approx(1e-15).epsilon(0.01));`

The problem is in the Catch-code line 2790 (probably also elsewhere):

`bool relativeOK = std::fabs(lhs_v - rhs.m_value) < rhs.m_epsilon * (rhs.m_scale + (std::max)(std::fabs(lhs_v), std::fabs(rhs.m_value)));`

Because the scale parameter has a default value 1, the RHS of the above expression becomes epsilon itself if the values of lhs and rhs are very small because "scale + very_small = scale = 1". So for large lhs and rhs values the above expression is a relative error check, but for very small values it gradually becomes an absolute check (parameter 'margin' was ment for that). That was not the intention. Depending on the meaning of scale (vaguely described in the documentation because it does not state whether scale is applied to rhs or lhs) it is better to get scale out of the above expression, and scale lhs or rhs before using the remaining expression to get the intended effect.

I am using the .hpp-file, Catch v1.9.1 *  Generated: 2017-04-09 21:21:06.285364

Regards,

     Jeroen

**Comment by rvanvenetie** [comment]
I also stumbled upon this, see #953

**Comment by horenmar** [comment]
I am consolidating the Approx issues into one, #980.
