### ISSUE TITLE
[Documentation suggestion] matcher namespace requirement

### ISSUE THREAD

**Issue by codyhan94** [philsquared/Catch#972]
The [matchers documentation](https://github.com/philsquared/Catch/blob/master/docs/matchers.md) currently does not mention anywhere that calls to the built-in matchers (StartsWith, Equals, EndsWith, etc) need to be qualified.

## Expected
```cpp
// file test.cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
TEST_CASE("matcher namespace")
{
    CHECK_THAT("foo", Equals("foo"));
}
```
should compile and work, as per the documentation.

## Actual
Need to qualify `Equals` as `Catch::Equals` or `Catch::Matchers::Equals` in order for `test.cpp` to compile. This is OK, but having it explicitly mentioned in the documentation would be nice. I can submit a pull request if you'd like.

**Comment by horenmar** [comment]
We don't want to place more things into global namespace without user's request, so it is intended, but I agree that it should be said so in the documentation.

It might be a while until I get around to fixing it, but you are welcome to submit a PR.
