### ISSUE TITLE
Feature Request: Profiling the test execution duration

### ISSUE THREAD

**Issue by M-Fabian** [philsquared/Catch#974]
I like the -d option which shows me how long individual tests take. However, I have some requests:

- show the total time for all tests at the bottom of the report
- show only the N slowest tests in the list (similar to pytest, see [here](https://docs.pytest.org/en/latest/usage.html#profiling-test-execution-duration), sorted by duration

Since I run all tests each time I compile, these two features would help me to optimize my test suite to be as quick as possible.

**Comment by horenmar** [comment]
The first we might do, but as to the second I think you should look for an external tooling (think `sort` and `take`).

**Comment by M-Fabian** [comment]
Thank you for replying. I wonder if a custom reporter could also do the second part. Would you consider this possible with the current reporter API?

**Comment by M-Fabian** [comment]
I just wrote my custom reporter, which is almost identical to the internal ConsoleReporter, except for sectionEnded() and testRunEnded(). I cannot specify how many tests are printed, so I default to 10. And I make them yellow and red if they take too long.

The API works quite nicely. It was easy for me to add my custom reporter. Good work!

**Comment by horenmar** [comment]
I see you already answered your own question.

Yeah, generally Reporters can do a lot, if you aren't afraid to get your hands dirty and save various information passed to them.
