### ISSUE TITLE
Feature request: Output list of sections used before failed assertion

### ISSUE THREAD

**Issue by Hedanito** [philsquared/Catch#975]
I am writing an emulator, and I use `SECTION`s to set the specific parameters and expected outcomes of a CPU instruction, while placing CPU setup/teardown and generic assertions before and after these sections. The problem here is that when once of the generic assertions fails, I don't have any idea which sections were used before it got to that assertion. I end up having to comment out sections until I run into the one that failed.

Silly example:
```
TEST_CASE("Test")
{
    int foo;

    SECTION("Section 1")
    {
        foo = 1;
    }

    SECTION("Section 2")
    {
        foo = 2;
    }

    REQUIRE(foo == 1);
}
```
When this test fails, it will not tell me which sections were used when it failed.

A practical example can be found [here](https://github.com/Hedanito/MGBE/blob/master/src/test/cpu/instruction_adc.cpp).

I would really like to see a list of all the sections that were run before a failed assertion. This way I would know the exact path the code took.

**Comment by philsquared** [comment]
You're not the first to ask this. I agree it would be useful for this sort of scenario and has been on the wishlist for a while.
I'm going to close this one in favour of the existing issue, which you can find in #734
