### ISSUE TITLE
Allow for test listeners to be defined in arbitrary files

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#986]
The current [documentation](https://github.com/philsquared/Catch/blob/master/docs/event-listeners.md) for test listeners states that these must be defined in the file where main is defined. I suggest we change that to allow for listeners to be defined in arbitrary files where catch.hpp is defined to avoid cluttering a single file with all the listeners we may want to add.

In my case I believe this will get unwieldy pretty fast.

**Comment by horenmar** [comment]
This limitation is there to decrease overall compilation times -- currently only the main file contains the listeners interface and it is not compiled in the common case.

I'll see if I can rearrange things around to allow selectively enabling reporters and listeners interfaces, but for now I recommend cutting out the relevant parts of `catch.hpp` into your own header.

**Comment by ruipacheco** [comment]
I'd like to expand on this but can't do it right now. I'm going to close this ticket and open a more detailed one in a few days.
