### ISSUE TITLE
Reporters should capture std::clog the same way they do std::cout/cerr

### ISSUE THREAD

**Issue by FabioFracassi** [philsquared/Catch#989]
## Description
When code writes output to std::clog (as e.g. boost::log does by default) the output is not handled correctly by reporters that capture output (e.g. JUnit xml).

### Steps to reproduce
create a test case that ouputs to std::clog

### Extra information
* Catch version: **v1.9.5**

**Comment by horenmar** [comment]
The fact that there are two error streams in C++ is one of those things that are obvious in hindsight, but you have to think about them first. I have fixed this locally and it will be in master whenever my internet stops acting up and lets me push.

**Comment by philsquared** [comment]
so this is now un-clogged?

(sorry, couldn't resist)
