### ISSUE TITLE
CATCH REQUIRE() macro isn't threadsafe

### ISSUE THREAD

**Issue by ned14** [philsquared/Catch#99]
Hi,

I'm using CATCH over at https://github.com/ned14/ISO_POSIX_standards_stuff. One unit test is creating 32 threads and thrashing a proposed POSIX permit object, but it turns out that REQUIRE() uses static storage and therefore isn't threadsafe.

Could you perhaps add an optional magic macro at the top which turns on the C++11 thread_local specifier for CATCH static data, at least those static data REQUIRE() uses? Intel's TBB and Microsoft's PPL know how to propagate CATCH exceptions out of parallel regions on C++11 compilers, so this actually should "fix" CATCH for multithreaded use.

Thanks,
Niall

**Comment by ned14** [comment]
For those needing a brutal hack job of a partially thread safe CATCH and are reading this issue, you may find my fork at https://github.com/ned14/Catch-ThreadSafe of use. I make no claims as to its reliability, but it works for me.

**Comment by horenmar** [comment]
Thread safety is planned for Catch2, but current Catch will be most likely left thread-unsafe.

I am closing this as part of backlog cleanup.

**Comment by mwpowellhtx** [comment]
@philsquared So, it's been several months, if not years, since this was posted. I see re: @horenmar 's post earlier this year re: Catch v2. This is now in development. Any plans when this will be released? I've got a client/server C++11 threading situation where this would be very welcome. Thank you!

**Comment by mwpowellhtx** [comment]
@ned14 Would you mind providing a synopsis of the things you addressed to achieve at least a hacked v1.5 thread safety? Thank you...

**Comment by ned14** [comment]
> @ned14 Would you mind providing a synopsis of the things you addressed to achieve at least a hacked v1.5 thread safety? Thank you...

That was a long time ago I am afraid. I remember hacking a mutex into the iostreams redirector which took some trouble to figure out. But I basically "giant lock"ed it.

I no longer use my hacked edition of CATCH as I needed a unit test framework which ran well with exceptions and RTTI disabled as well as under multiple threads, so I ended up writing my own even lighter weight test framework than CATCH which still outputs JUnit XML and I use that exclusively now: https://github.com/ned14/quickcpplib/blob/master/include/boost/test/unit_test.hpp. Yes, it's Boost.Test drop in compatible, and it's ridiculously simple, perhaps too simple for some folk. But it has near zero compile time overhead, which fixes the almost 30 second compile times I saw with CATCH.

Niall

**Comment by mwpowellhtx** [comment]
@ned14 I take to mean does not assume a Boost dependency. I happen to be here getting my knees wet with Catch after struggling to heavy lift Boost, BTW. I haven't noticed compile time issues (yet); that's not to say I would the further I get into it. I may have a look at that, however. Thank you.

**Comment by ned14** [comment]
Oh no, the whole point of that quickcpplib file is to *eliminate* the Boost dependency.

Compile time issues only appear if you're doing hefty metaprogramming and feeding those expressions into CATCH. CATCH runs further metaprogramming on such expressions you see, and compile times start breaking past twenty seconds quickly enough.

**Comment by mwpowellhtx** [comment]
@ned14 My interest is piqued. How do you handle "matcher" scenarios? Or "generator" scenarios? Can you "match" exceptions when they are handled? i.e. expectations of an exception, with a match on its user-defined state?
