### ISSUE TITLE
Compiler error on constructor with braced initializer list syntax in CHECK macro.

### ISSUE THREAD

**Issue by Nevsor** [philsquared/Catch#996]
## Description
Calling a constructor with a braced initializer list inside the CHECK or REQUIRED macro yields a compiler error. It works if the constructor is enclosed in paranthesis.

#### Example:
```example.cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

struct Person {
    std::string name;
    int age;
};

bool operator!=(const Person& a, const Person& b) {
    return a.name != b.name || a.age != b.age;
}

TEST_CASE("Test 1") {
    CHECK( (Person{"Alice", 42}) != (Person{"Bob", 42}) ); // works
    CHECK( (Person{"Alice", 42}) !=  Person{"Bob", 42}  ); // compiler error
}
```

#### Execute in bash:
```bash
cd /tmp

wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp

echo >test.cpp '
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

struct Person {
    std::string name;
    int age;
};

bool operator!=(const Person& a, const Person& b) {
    return a.name != b.name || a.age != b.age;
}

TEST_CASE("Test 1") {
    CHECK( (Person{"Alice", 42}) != (Person{"Bob", 42}) ); // works
    CHECK( (Person{"Alice", 42}) !=  Person{"Bob", 42}  ); // compiler error
}'

g++ test.cpp 
```

## Extra information
* Catch version: **v1.9.7**
* Operating System: **Arch Linux**
* Compiler+version: **GCC v7.7.1**

Error message:
```
test.cpp:16:57: error: macro "CHECK" passed 2 arguments, but takes just 1
     CHECK( (Person{"Alice", 42}) !=  Person{"Bob", 42}  ); // compiler error
                                                         ^
test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
test.cpp:16:5: error: ‘CHECK’ was not declared in this scope
     CHECK( (Person{"Alice", 42}) !=  Person{"Bob", 42}  ); // compiler error
     ^~~~~
```

**Comment by horenmar** [comment]
Sorry, this is "won't fix" for Catch 1 (and already fixed in Catch 2).

The error happens on any expression containing commas that are in a place to separate macro arguments (this is why enclosing the expression in parentheses works, it turns the entire expression into single macro argument) and to fix it, variadic macros are required. Since variadic macros are not supported on older compilers, it would also require us to keep two sets of all user facing and internal macros, further increasing the number of macros that need to be kept in sync upon changes (to 4 sets: `CATCH_` prefixed versus non-prefixed, variadic vs non-variadic).

**Comment by philsquared** [comment]
Given that this particular form occurs with braced initializer lists, which only came in with C++11, then you should have no problem moving to Catch2, anyway :-)

Please give it a try:
https://github.com/philsquared/Catch/releases/tag/v2.0.0-develop.2

(although it's considered "pre-release" at this point we're hoping to make it the main distribution very soon - so would appreciate as much feedback on how it's working for you as soon as possible).

**Comment by Nevsor** [comment]
Thanks, I just upgraded to Catch2 and everything works great so far.

**Comment by philsquared** [comment]
Perfect! Thanks for letting us know
