### ISSUE TITLE
separate test definition from declaration

### ISSUE THREAD

**Issue by dvirtz** [philsquared/Catch#997]
I'm using the `ParseAndAddCatchTests` module to run tests with ctest and it's working greate. The only 
problem is that I have to run CMake whenever I add a test for it to be processed.

To automate this I add all test files to [CMAKE_CONFIGURE_DEPENDS](https://cmake.org/cmake/help/latest/prop_dir/CMAKE_CONFIGURE_DEPENDS.html) property but now anything I change in those files causes CMake to run.

A solution for this would be to separate test declarations from definitions to different files so only when files with test declarations change will CMake run.

Actually, this is exactly what we do with regular code to save compilation time.

What do you think of this?

**Comment by dvirtz** [comment]
I managed to implement this locally but it requires the user to write the test name explicitly, instead of it being generated by `INTERNAL_CATCH_UNIQUE_NAME`. 

Do you think this is acceptable?
If so, then I'll send a PR.

**Comment by horenmar** [comment]
I think it would be preferable if the cmake script was changed so that it recognizes `REGISTER_TEST_CASE` macro, which already fulfills very similar function.

_note: I am phone posting, so I wasn't able to actually test my approach_

**Comment by dvirtz** [comment]
Thanks, I didn't know about this macro. Can you tell me the difference between this and `METHOD_AS_TEST_CASE`?

**Comment by horenmar** [comment]
`REGISTER_TEST_CASE` expects a free function and it is up to the user to call it, `METHOD_AS_TEST_CASE` expects a method of a class and provides auto registration:
```cpp
void testFunction() {
    REQUIRE(1 == 2);
}
struct AutoRegTests {
    AutoRegTests() {
        REGISTER_TEST_CASE(testFunction, "manually registered", "[bar]");
    }
};
AutoRegTests auto;

class TestClass {
    std::string s;
public:
    TestClass():s("Hello"){}
    void testMethod() {
        REQUIRE( s == "Hello" );
    }
};
`METHOD_AS_TEST_CASE(TestClass::testMethod, "sample test method", "[foo]");
```

**Comment by dvirtz** [comment]
Thanks. Is there a reason why `REGISTER_TEST_CASE` doesn't provide auto registration?
Also, can I call these macros on a header file?

**Comment by horenmar** [comment]
No idea, I found out that these macros exist 2 days ago, when I needed to crawl through all Catch-provided macros for a Catch 2 feature...

Looking at `REGISTER_TEST_CASE`, it even uses the internal `AutoReg` object to do the registration, it just doesn't provide it with a unique name, so it cannot be used in global scope... Quick test says that if I change it to provide it with a unique name, the old usage does not break, so I might change that in the (near) future for Catch 2.

> Also, can I call these macros on a header file?

I am going to assume that you mean __in__ a header file. The answer should be yes, but I would not recommend it, as you will have to take care not to register the test case multiple times.

**Comment by dvirtz** [comment]
Thanks. I'll try using one of these macros.

**Comment by philsquared** [comment]
The purpose of `REGISTER_TEST_CASE` is to be a manual alternative to `TEST_CASE` - i.e. *not* self registering!
See #421 - in particular the second comment, for more context.

As ever this probably means the docs need improving :-)

**Comment by philsquared** [comment]
(or in this case "adding")
